import type { ArchitecturePatterns } from '@dotfiles/schemas';

/**
 * Represents a set of regular expression patterns derived from {@link ArchitecturePatterns}.
 * These regex patterns are used to robustly match against asset names or other strings
 * to determine architecture compatibility.
 */
export interface ArchitectureRegex {
  /**
   * A combined regular expression pattern string for matching operating system identifiers.
   * This is typically generated by joining the patterns from `ArchitecturePatterns.system` with `|`.
   * Example: `(apple|darwin|macos|osx)`
   */
  systemPattern: string;
  /**
   * A combined regular expression pattern string for matching CPU architecture identifiers.
   * This is typically generated by joining the patterns from `ArchitecturePatterns.cpu` with `|`.
   * Example: `(arm64|aarch64)`
   */
  cpuPattern: string;
  /**
   * A combined regular expression pattern string for matching OS variant identifiers.
   * This is typically generated by joining the patterns from `ArchitecturePatterns.variants` with `|`.
   * Example: `(musl|gnu)`
   */
  variantPattern: string;
}
