import type { ArchitecturePatterns, ArchitectureRegex } from './types';

/**
 * Creates a set of combined regular expression patterns from architecture patterns.
 *
 * These patterns can be used to match against GitHub release asset names to find
 * compatible binaries. The function escapes special regex characters in the input
 * patterns to ensure they are treated as literal strings.
 *
 * @param patterns - The architecture patterns generated by `getArchitecturePatterns`.
 * @returns An object containing combined regex patterns for system, CPU, and variants.
 *
 * @public
 */
export function createArchitectureRegex(patterns: ArchitecturePatterns): ArchitectureRegex {
  // Escape special regex characters in pattern strings
  const escapeRegex = (str: string): string => {
    return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  };

  // Create alternations for each pattern group
  const systemPattern = patterns.system.length > 0 ? `(${patterns.system.map(escapeRegex).join('|')})` : '';
  const cpuPattern = patterns.cpu.length > 0 ? `(${patterns.cpu.map(escapeRegex).join('|')})` : '';
  const variantPattern = patterns.variants.length > 0 ? `(${patterns.variants.map(escapeRegex).join('|')})` : '';

  const result: ArchitectureRegex = {
    systemPattern,
    cpuPattern,
    variantPattern,
  };

  return result;
}
