/**
 * Defines a set of string patterns used for matching system and CPU
 * architectures, often found in the names of release assets (e.g., on GitHub
 * Releases).
 *
 * These patterns help in identifying compatible binaries or installers for the
 * current system and are based on Zinit's architecture detection logic.
 *
 * @public
 */
export interface ArchitecturePatterns {
  /**
   * An array of string patterns representing different ways an operating system
   * might be named.
   *
   * @example For macOS, this could include `['apple', 'darwin', 'macos', 'osx']`.
   */
  system: string[];

  /**
   * An array of string patterns representing different ways a CPU architecture
   * might be named.
   *
   * @example For ARM64, this could include `['arm64', 'aarch64']`.
   */
  cpu: string[];

  /**
   * An array of additional OS-specific patterns or variants that might be used
   * in asset naming.
   *
   * These are used for disambiguation when multiple assets match the primary
   * system and CPU patterns. The order of variants is important, as earlier
   * variants are preferred over later ones during selection.
   *
   * @example For Linux, this could be `['musl', 'gnu']`, where `musl` is preferred.
   */
  variants: string[];
}

/**
 * Represents a set of regular expression patterns derived from
 * {@link ArchitecturePatterns}.
 *
 * These regex patterns are used to robustly match against asset names or other
 * strings to determine architecture compatibility.
 *
 * @public
 */
export interface ArchitectureRegex {
  /**
   * A combined regular expression pattern string for matching operating system
   * identifiers.
   *
   * This is typically generated by joining the patterns from
   * `ArchitecturePatterns.system` with `|`.
   *
   * @example `(apple|darwin|macos|osx)`
   */
  systemPattern: string;

  /**
   * A combined regular expression pattern string for matching CPU architecture
   * identifiers.
   *
   * This is typically generated by joining the patterns from
   * `ArchitecturePatterns.cpu` with `|`.
   *
   * @example `(arm64|aarch64)`
   */
  cpuPattern: string;

  /**
   * A combined regular expression pattern string for matching OS variant
   * identifiers.
   *
   * This is typically generated by joining the patterns from
   * `ArchitecturePatterns.variants` with `|`.
   *
   * @example `(musl|gnu)`
   */
  variantPattern: string;
}
