/**
 * Defines a set of string patterns used for matching system and CPU architectures,
 * often found in the names of release assets (e.g., on GitHub Releases).
 * These patterns help in identifying compatible binaries or installers for the current system.
 *
 * Based on zinit's architecture detection logic.
 */
export interface ArchitecturePatterns {
  /**
   * An array of string patterns representing different ways an operating system might be named.
   * For example, for macOS, this could include `['apple', 'darwin', 'macos', 'osx']`.
   */
  system: string[];
  /**
   * An array of string patterns representing different ways a CPU architecture might be named.
   * For example, for ARM64, this could include `['arm64', 'aarch64']`.
   */
  cpu: string[];
  /**
   * An array of additional OS-specific patterns or variants that might be used in asset naming.
   * For example, `['musl']` for Linux distributions using musl libc, or `['gnu']` for glibc.
   *
   * These are used for disambiguation when multiple assets match the system and CPU patterns.
   * Variants are tried IN ORDER - earlier variants are preferred over later ones.
   * For example, for Linux: ['musl', 'gnu', 'unknown-linux'] means musl is preferred over gnu.
   */
  variants: string[];
}

/**
 * Represents a set of regular expression patterns derived from {@link ArchitecturePatterns}.
 * These regex patterns are used to robustly match against asset names or other strings
 * to determine architecture compatibility.
 */
export interface ArchitectureRegex {
  /**
   * A combined regular expression pattern string for matching operating system identifiers.
   * This is typically generated by joining the patterns from `ArchitecturePatterns.system` with `|`.
   * Example: `(apple|darwin|macos|osx)`
   */
  systemPattern: string;
  /**
   * A combined regular expression pattern string for matching CPU architecture identifiers.
   * This is typically generated by joining the patterns from `ArchitecturePatterns.cpu` with `|`.
   * Example: `(arm64|aarch64)`
   */
  cpuPattern: string;
  /**
   * A combined regular expression pattern string for matching OS variant identifiers.
   * This is typically generated by joining the patterns from `ArchitecturePatterns.variants` with `|`.
   * Example: `(musl|gnu)`
   */
  variantPattern: string;
}
