#
# 🐚 Hermit manages isolated, self-bootstrapping sets of tools in software projects.
# https://github.com/cashapp/hermit
#
alias-installer hermit

# Generated by Hermit
HERMIT_ROOT_BIN="${HERMIT_ROOT_BIN:-"$HOME/bin/hermit"}"
eval "$(test -x $HERMIT_ROOT_BIN && $HERMIT_ROOT_BIN shell-hooks --print --zsh)"
