targetDir: ~/.dotfiles/generator/.generated/bin
dotfilesDir: ~/.dotfiles/generator
generatedDir: ~/.dotfiles/generator/.generated
toolConfigsDir: ~/.dotfiles/generator/actual-tool-configs
generatedArtifactsManifestPath: ~/.dotfiles/generator/.generated/generated-manifest.json
debug: ""
cacheEnabled: true
githubApiCacheEnabled: true
checkUpdatesOnRun: false
