import type { IBinaryConfig, ToolConfig } from '@dotfiles/core';
import type { IFileSystem } from '@dotfiles/file-system';
import { getBuiltPackageName } from './getBuiltPackageName';

/**
 * Header comment shared by all generated tool-types.d.ts files.
 */
const TOOL_TYPES_HEADER: string = `/**
 * Type-safe binary names for tool dependencies.
 *
 * This file is automatically generated by the build system and the \`generate\` command.
 * It extracts binary names from loaded tool configurations to provide autocomplete
 * for the \`dependsOn()\` method.
 */`;

/**
 * Extracts all binary names from loaded tool configurations.
 *
 * @param toolConfigs - Record of loaded tool configurations
 * @returns Set of unique binary names from all tool configurations
 */
export function extractBinaryNames(toolConfigs: Record<string, ToolConfig>): Set<string> {
  const binaryNames: Set<string> = new Set();

  for (const [toolName, toolConfig] of Object.entries(toolConfigs)) {
    if (toolConfig.binaries && toolConfig.binaries.length > 0) {
      for (const binary of toolConfig.binaries) {
        if (typeof binary === 'string') {
          binaryNames.add(binary);
        } else {
          const binaryConfig: IBinaryConfig = binary;
          binaryNames.add(binaryConfig.name);
        }
      }
    } else {
      binaryNames.add(toolName);
    }
  }

  return binaryNames;
}

/**
 * Generates the TypeScript union type string from binary names.
 * Falls back to 'string' if no binary names are provided.
 *
 * @param binaryNames - Set of binary names to include in the union
 * @returns TypeScript union type string
 */
export function generateUnionType(binaryNames: Set<string>): string {
  if (binaryNames.size === 0) {
    return 'string';
  }

  const sortedNames: string[] = Array.from(binaryNames).sort();
  const quotedNames: string[] = sortedNames.map((name: string): string => `'${name}'`);
  return quotedNames.join(' | ');
}

export function generateToolTypesContent(toolConfigs: Record<string, ToolConfig>): string {
  const binaryNames: Set<string> = extractBinaryNames(toolConfigs);
  const unionType: string = generateUnionType(binaryNames);
  const sortedNames: string[] = unionType === 'string' ? [] : Array.from(binaryNames).sort();
  const registryEntries: string = sortedNames.map((name: string): string => `    '${name}': never;`).join('\n');
  const hasEntries: boolean = registryEntries.length > 0;
  const registryBody: string = hasEntries
    ? `  interface IKnownBinNameRegistry {\n${registryEntries}\n  }`
    : '  interface IKnownBinNameRegistry {}';
  const moduleBlock: string = `declare module '${getBuiltPackageName()}' {\n${registryBody}\n}`;
  const contentParts: string[] = [TOOL_TYPES_HEADER, moduleBlock, 'export {};', ''];
  const content: string = contentParts.join('\n\n');
  return content;
}

/**
 * Generates and writes the tool-types.d.ts file.
 *
 * @param toolConfigs - Record of loaded tool configurations
 * @param outputPath - Path where the tool-types.d.ts file should be written
 * @param fs - File system interface for writing the file
 */
export async function generateToolTypes(
  toolConfigs: Record<string, ToolConfig>,
  outputPath: string,
  fs: IFileSystem
): Promise<void> {
  const content: string = generateToolTypesContent(toolConfigs);
  await fs.writeFile(outputPath, content, 'utf8');
}
