import type { BinaryConfig, ToolConfig } from '@dotfiles/core';
import type { IFileSystem } from '@dotfiles/file-system';

/**
 * Template for the tool-types.d.ts file.
 * The {BINARY_NAMES} placeholder will be replaced with actual binary names.
 */
const TOOL_TYPES_TEMPLATE = `/**
 * Type-safe binary names for tool dependencies.
 * 
 * This file is automatically generated by the build system and the \`generate\` command.
 * It extracts binary names from loaded tool configurations to provide autocomplete
 * for the \`dependsOn()\` method.
 */

/**
 * Known binary names extracted from tool configurations.
 * Falls back to \`string\` when no tool configs are available.
 */
export type KnownBinName = {BINARY_NAMES};

declare module '@dotfiles/core' {
  interface ToolConfigBuilder {
    /**
     * Declares that this tool depends on other tools' binaries being available.
     * 
     * @param binaryNames - Names of binaries this tool requires
     * @returns The builder instance for chaining
     */
    dependsOn(...binaryNames: KnownBinName[]): this;
  }

  interface PlatformConfigBuilder {
    /**
     * Declares that this tool depends on other tools' binaries being available.
     * 
     * @param binaryNames - Names of binaries this tool requires
     * @returns The builder instance for chaining
     */
    dependsOn(...binaryNames: KnownBinName[]): this;
  }
}
`;

/**
 * Extracts all binary names from loaded tool configurations.
 *
 * @param toolConfigs - Record of loaded tool configurations
 * @returns Set of unique binary names from all tool configurations
 */
export function extractBinaryNames(toolConfigs: Record<string, ToolConfig>): Set<string> {
  const binaryNames: Set<string> = new Set();

  for (const [toolName, toolConfig] of Object.entries(toolConfigs)) {
    if (toolConfig.binaries && toolConfig.binaries.length > 0) {
      for (const binary of toolConfig.binaries) {
        if (typeof binary === 'string') {
          binaryNames.add(binary);
        } else {
          const binaryConfig: BinaryConfig = binary;
          binaryNames.add(binaryConfig.name);
        }
      }
    } else {
      binaryNames.add(toolName);
    }
  }

  return binaryNames;
}

/**
 * Generates the TypeScript union type string from binary names.
 * Falls back to 'string' if no binary names are provided.
 *
 * @param binaryNames - Set of binary names to include in the union
 * @returns TypeScript union type string
 */
export function generateUnionType(binaryNames: Set<string>): string {
  if (binaryNames.size === 0) {
    return 'string';
  }

  const sortedNames: string[] = Array.from(binaryNames).sort();
  const quotedNames: string[] = sortedNames.map((name: string): string => `'${name}'`);
  return quotedNames.join(' | ');
}

/**
 * Generates the complete tool-types.d.ts content.
 *
 * @param toolConfigs - Record of loaded tool configurations
 * @returns Content for the tool-types.d.ts file
 */
export function generateToolTypesContent(toolConfigs: Record<string, ToolConfig>): string {
  const binaryNames: Set<string> = extractBinaryNames(toolConfigs);
  const unionType: string = generateUnionType(binaryNames);
  const content: string = TOOL_TYPES_TEMPLATE.replace('{BINARY_NAMES}', unionType);
  return content;
}

/**
 * Generates and writes the tool-types.d.ts file.
 *
 * @param toolConfigs - Record of loaded tool configurations
 * @param outputPath - Path where the tool-types.d.ts file should be written
 * @param fs - File system interface for writing the file
 */
export async function generateToolTypes(
  toolConfigs: Record<string, ToolConfig>,
  outputPath: string,
  fs: IFileSystem
): Promise<void> {
  const content: string = generateToolTypesContent(toolConfigs);
  await fs.writeFile(outputPath, content, 'utf8');
}
