#!/bin/bash

# Shim for {{TOOL_NAME}}
# Generated by dotfiles-generator

TOOL_NAME="{{TOOL_NAME}}"
BINARY_NAME="{{BINARY_NAME}}" # The actual binary executable name
INSTALL_DIR_BASE="$HOME/.dotfiles/.generated/binaries"
TOOL_INSTALL_DIR="$INSTALL_DIR_BASE/$TOOL_NAME"
EXPECTED_BINARY_PATH="$TOOL_INSTALL_DIR/bin/$BINARY_NAME"
INSTALL_SCRIPT_PATH="$HOME/.dotfiles/install-tool.sh" # Path to the central installation script

# Function to log messages
log_message() {
  echo "Shim ($TOOL_NAME): $1"
}

# Check if the binary exists
if [ ! -x "$EXPECTED_BINARY_PATH" ]; then
  log_message "Binary not found at $EXPECTED_BINARY_PATH. Attempting installation..."

  # Call the central installation script
  if [ -f "$INSTALL_SCRIPT_PATH" ]; then
    # Ensure the script is executable, though it should be by design
    chmod +x "$INSTALL_SCRIPT_PATH"

    log_message "Running installation script: $INSTALL_SCRIPT_PATH $TOOL_NAME $BINARY_NAME"
    if "$INSTALL_SCRIPT_PATH" "$TOOL_NAME" "$BINARY_NAME"; then
      log_message "Installation script completed successfully."
      if [ ! -x "$EXPECTED_BINARY_PATH" ]; then
        log_message "ERROR: Installation script ran, but binary still not found at $EXPECTED_BINARY_PATH."
        exit 1
      fi
    else
      log_message "ERROR: Installation script failed for $TOOL_NAME."
      exit 1
    fi
  else
    log_message "ERROR: Central installation script not found at $INSTALL_SCRIPT_PATH."
    exit 1
  fi
else
  log_message "Binary found at $EXPECTED_BINARY_PATH. Executing..."
fi

# Execute the actual tool binary, passing all arguments
exec "$EXPECTED_BINARY_PATH" "$@"
