import { loadToolConfigsFromDirectory } from '@modules/config-loader';
import type { Stats } from '@modules/file-system';
import type { TsLogger } from '@modules/logger';
import { ErrorTemplates, WarningTemplates } from '@modules/shared/ErrorTemplates';
import type { ToolConfig } from '@types';
import path from 'path';
import { type GlobalProgram, type Services } from '../../cli';
import { exitCli } from './exitCli';

export async function detectConflictsActionLogic(
  parentLogger: TsLogger,
  _options: {}, // No specific options for this command yet
  services: Services,
): Promise<void> {
  const logger = parentLogger.getSubLogger({ name: 'detectConflictsActionLogic' });
  const { yamlConfig, fs } = services;
  const conflictMessages: string[] = [];

  let toolConfigsArray: ToolConfig[] = [];
  try {
    const toolConfigsRecord = await loadToolConfigsFromDirectory(logger, yamlConfig.paths.toolConfigsDir, fs);
    toolConfigsArray = Object.values(toolConfigsRecord);
  } catch (error: any) {
    logger.error(ErrorTemplates.config.loadFailed('tool configurations', error.message));
    exitCli(1);
  }

  if (toolConfigsArray.length === 0) {
    logger.info('No tool configurations found. Nothing to check for conflicts.');
    exitCli(0);
  }

  for (const toolConfig of toolConfigsArray) {
    // Check for shim conflicts
    if (toolConfig.binaries) {
      for (const binaryName of toolConfig.binaries) {
        const shimPath = path.join(yamlConfig.paths.targetDir, binaryName);
        if (await fs.exists(shimPath)) {
          try {
            const content = await fs.readFile(shimPath);
            if (!content.includes('# Generated by Dotfiles Management Tool')) {
              conflictMessages.push(
                `[${toolConfig.name}]: ${shimPath} (exists but is not a generator shim)`,
              );
            }
          } catch (readError: any) {
            logger.warn(WarningTemplates.fs.readFailed(shimPath, readError.message));
            conflictMessages.push(
              `[${toolConfig.name}]: ${shimPath} (exists but could not be read/verified)`,
            );
          }
        }
      }
    }

    // Check for symlink conflicts
    if (toolConfig.symlinks) {
      for (const symlink of toolConfig.symlinks) {
        const targetPath = path.join(yamlConfig.paths.homeDir, symlink.target);
        const sourcePath = path.join(yamlConfig.paths.dotfilesDir, symlink.source);

        logger.debug(`Checking symlink: ${targetPath} -> ${sourcePath}`);

        try {
          const stats: Stats | null = await fs.lstat(targetPath);
          if (stats) {
            if (stats.isSymbolicLink()) {
              const linkString = await fs.readlink(targetPath);
              const resolvedLinkTarget = path.resolve(path.dirname(targetPath), linkString);
              if (resolvedLinkTarget !== sourcePath) {
                conflictMessages.push(
                  `[${toolConfig.name}]: ${targetPath} (points to '${linkString}', expected '${sourcePath}')`,
                );
              }
            } else {
              conflictMessages.push(
                `[${toolConfig.name}]: ${targetPath} (exists but is not a symlink)`,
              );
            }
          }
        } catch (error: any) {
          if (error.code !== 'ENOENT') {
            logger.warn(WarningTemplates.fs.readFailed(targetPath, error.message));
          }
        }
      }
    }
  }

  if (conflictMessages.length > 0) {
    const header = 'Conflicts detected with files not owned by the generator:';
    const formattedConflicts = conflictMessages.map((msg) => `  - ${msg}`).join('\n');
    logger.warn(WarningTemplates.tool.conflictsDetected(header, formattedConflicts));
    logger.info('Please review the warnings above.');
    exitCli(1);
    return;
  } else {
    logger.info('No conflicts detected.');
    exitCli(0);
    return;
  }
}

export function registerDetectConflictsCommand(
  parentLogger: TsLogger,
  program: GlobalProgram,
  services: Services,
): void {
  const logger = parentLogger.getSubLogger({ name: 'registerDetectConflictsCommand' });
  program
    .command('detect-conflicts')
    .description(
      'Detects conflicts between potential generated artifacts and existing system files.',
    )
    .action(async (options) => {
      const combinedOptions = { ...options, ...program.opts() };
      logger.debug('detect-conflicts command: Action called with options: %o', combinedOptions);
      try {
        await detectConflictsActionLogic(logger, combinedOptions, services);
      } catch (error) {
        // If this is an error from exitCli, rethrow it to preserve the exit code
        if ((error as Error).message.startsWith('MOCK_EXIT_CLI_CALLED_WITH_')) {
          throw error;
        }

        logger.fatal(ErrorTemplates.command.executionFailed('detect-conflicts', 1, 'Unhandled error in action handler'));
        logger.debug('Fatal error details: %O', error);
        logger.error(ErrorTemplates.command.executionFailed('detect-conflicts', 1, (error as Error).message));
        logger.debug('Error details: %O', error);
        exitCli(1);
      }
    });
}