import path from 'node:path';
import type { GlobalProgram, Services } from '@cli';
import type { YamlConfig } from '@modules/config';
import { loadToolConfigsFromDirectory } from '@modules/config-loader';
import type { IFileSystem, Stats } from '@modules/file-system';
import type { TsLogger } from '@modules/logger';
import { logs } from '@modules/logger';
import type { ToolConfig } from '@types';
import { exitCli } from './exitCli';

async function loadToolConfigs(logger: TsLogger, yamlConfig: YamlConfig, fs: IFileSystem): Promise<ToolConfig[]> {
  try {
    const toolConfigsRecord = await loadToolConfigsFromDirectory(
      logger,
      yamlConfig.paths.toolConfigsDir,
      fs,
      yamlConfig
    );
    return Object.values(toolConfigsRecord);
  } catch (error: unknown) {
    logger.error(logs.config.error.loadFailed('tool configurations', (error as Error).message));
    exitCli(1);
  }
}

async function checkShimConflicts(
  logger: TsLogger,
  fs: IFileSystem,
  toolConfig: ToolConfig,
  targetDir: string,
  conflictMessages: string[]
): Promise<void> {
  if (!toolConfig.binaries) return;

  for (const binaryName of toolConfig.binaries) {
    const shimPath = path.join(targetDir, binaryName);
    if (await fs.exists(shimPath)) {
      try {
        const content = await fs.readFile(shimPath);
        if (!content.includes('# Generated by Dotfiles Management Tool')) {
          conflictMessages.push(`[${toolConfig.name}]: ${shimPath} (exists but is not a generator shim)`);
        }
      } catch (readError: unknown) {
        logger.warn(logs.fs.warning.readFailed(shimPath, (readError as Error).message));
        conflictMessages.push(`[${toolConfig.name}]: ${shimPath} (exists but could not be read/verified)`);
      }
    }
  }
}

async function checkSymlinkConflicts(
  logger: TsLogger,
  fs: IFileSystem,
  toolConfig: ToolConfig,
  homeDir: string,
  dotfilesDir: string,
  conflictMessages: string[]
): Promise<void> {
  if (!toolConfig.symlinks) return;

  for (const symlink of toolConfig.symlinks) {
    const targetPath = path.join(homeDir, symlink.target);
    const sourcePath = path.join(dotfilesDir, symlink.source);

    try {
      const stats: Stats | null = await fs.lstat(targetPath);
      if (stats) {
        if (stats.isSymbolicLink()) {
          const linkString = await fs.readlink(targetPath);
          const resolvedLinkTarget = path.resolve(path.dirname(targetPath), linkString);
          if (resolvedLinkTarget !== sourcePath) {
            conflictMessages.push(
              `[${toolConfig.name}]: ${targetPath} (points to '${linkString}', expected '${sourcePath}')`
            );
          }
        } else {
          conflictMessages.push(`[${toolConfig.name}]: ${targetPath} (exists but is not a symlink)`);
        }
      }
    } catch (error: unknown) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        logger.warn(logs.fs.warning.readFailed(targetPath, (error as Error).message));
      }
    }
  }
}

function reportConflicts(logger: TsLogger, conflictMessages: string[]): void {
  if (conflictMessages.length > 0) {
    const header = 'Conflicts detected with files not owned by the generator:';
    const formattedConflicts = conflictMessages.map((msg) => `  - ${msg}`).join('\n');
    logger.warn(logs.tool.warning.conflictsDetected(header, formattedConflicts));
    exitCli(1);
  } else {
    logger.info(logs.general.success.noConflictsDetected());
    exitCli(0);
  }
}

export async function detectConflictsActionLogic(
  parentLogger: TsLogger,
  _options: Record<string, unknown>, // No specific options for this command yet
  services: Services
): Promise<void> {
  const logger = parentLogger.getSubLogger({ name: 'detectConflictsActionLogic' });
  const { yamlConfig, fs } = services;
  const conflictMessages: string[] = [];

  const toolConfigsArray = await loadToolConfigs(logger, yamlConfig, fs);

  if (toolConfigsArray.length === 0) {
    logger.info(logs.general.success.noToolsFound(yamlConfig.paths.toolConfigsDir));
    exitCli(0);
  }

  for (const toolConfig of toolConfigsArray) {
    // Check for shim conflicts
    await checkShimConflicts(logger, fs, toolConfig, yamlConfig.paths.targetDir, conflictMessages);

    // Check for symlink conflicts
    await checkSymlinkConflicts(
      logger,
      fs,
      toolConfig,
      yamlConfig.paths.homeDir,
      yamlConfig.paths.dotfilesDir,
      conflictMessages
    );
  }

  reportConflicts(logger, conflictMessages);
}

export function registerDetectConflictsCommand(
  parentLogger: TsLogger,
  program: GlobalProgram,
  servicesFactory: () => Promise<Services>
): void {
  const logger = parentLogger.getSubLogger({ name: 'registerDetectConflictsCommand' });
  program
    .command('detect-conflicts')
    .description('Detects conflicts between potential generated artifacts and existing system files.')
    .action(async (options) => {
      const combinedOptions = { ...options, ...program.opts() };
      logger.debug(logs.command.debug.errorDetails(), combinedOptions);
      try {
        const services = await servicesFactory();
        await detectConflictsActionLogic(logger, combinedOptions, services);
      } catch (error) {
        // If this is an error from exitCli, rethrow it to preserve the exit code
        if ((error as Error).message.startsWith('MOCK_EXIT_CLI_CALLED_WITH_')) {
          throw error;
        }

        logger.fatal(logs.command.error.executionFailed('detect-conflicts', 1, 'Unhandled error in action handler'));
        logger.debug(logs.command.debug.errorDetails(), error);
        logger.error(logs.command.error.executionFailed('detect-conflicts', 1, (error as Error).message));
        logger.debug(logs.command.debug.errorDetails(), error);
        exitCli(1);
      }
    });
}
