import type { YamlConfig } from '@modules/config';
import { createYamlConfigFromObject } from '@modules/config-loader';
import { createMemFileSystem, type FileSystemSpies, TestLogger } from '@testing-helpers';
import type { ToolConfig } from '@types';
import { beforeEach, describe, expect, it, spyOn } from 'bun:test';
import path from 'node:path';
import { ShimGenerator } from '../ShimGenerator';

import '@testing-helpers/matchers';

describe('ShimGenerator', () => {
  let mockConfig: YamlConfig;
  let shimGenerator: ShimGenerator;
  let fsMocks: FileSystemSpies;
  let logger: TestLogger;

  beforeEach(async () => {
    const { fs, spies } = await createMemFileSystem({});
    fsMocks = spies;
    logger = new TestLogger();

    mockConfig = await createYamlConfigFromObject(
      logger,
      fs,
      {}, 
      { platform: 'linux', arch: 'x64', homeDir: '/home/test' },
      {}
    );
    shimGenerator = new ShimGenerator(logger, fs, mockConfig);
  });

  describe('constructor', () => {
    it('should initialize correctly', () => {
      expect(shimGenerator).toBeInstanceOf(ShimGenerator);
    });
  });

  describe('generateForTool', () => {
    const toolName = 'my-tool';
    const toolConfig: ToolConfig = {
      name: toolName,
      binaries: ['my-tool-binary'],
      version: '1.0.0',
      installationMethod: 'none',
      installParams: undefined,
    };
    let expectedShimPath: string;
    let expectedBinaryPath: string;

    beforeEach(() => {
      expectedShimPath = path.join(mockConfig.paths.targetDir, toolName);
      expectedBinaryPath = path.join(
        mockConfig.paths.binariesDir,
        toolConfig.name,
        toolConfig.binaries![0]!
      );
    });

    it('should generate correct shim content, write file, and return shim path', async () => {
      const result = await shimGenerator.generateForTool(toolName, toolConfig);

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.ensureDir).toHaveBeenCalledWith(mockConfig.paths.targetDir);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      expect(fsMocks.writeFile.mock.calls[0]).toBeDefined();
      expect(fsMocks.chmod).toHaveBeenCalledWith(expectedShimPath, 0o755);

      const writtenContent = fsMocks.writeFile.mock.calls[0]![1];
      expect(writtenContent).toMatchLooseInlineSnapshot`
        #!/usr/bin/env bash
        # Shim for my-tool
        # Generated by Dotfiles Management Tool

        set -euo pipefail

        TOOL_NAME="my-tool"
        TOOL_EXECUTABLE="${expectedBinaryPath}"
        GENERATOR_CLI_EXECUTABLE="${expect.anything}"
        CONFIG_PATH="/path/to/config.yaml"

        if [ -x "$TOOL_EXECUTABLE" ]; then
          exec "$TOOL_EXECUTABLE" "$@"
          exit $?
        else
          # Capture both stdout and stderr from the install command
          install_output=$("$GENERATOR_CLI_EXECUTABLE" install --shim-mode --config "$CONFIG_PATH" "$TOOL_NAME" 2>&1)
          install_exit_code=$?
          
          if [ $install_exit_code -eq 0 ]; then
            # Installation successful, check if binary now exists
            if [ -x "$TOOL_EXECUTABLE" ]; then
              exec "$TOOL_EXECUTABLE" "$@"
              exit $?
            else
              echo "Installation completed but binary not found at '$TOOL_EXECUTABLE'."
              exit 1
            fi
          else
            # Installation failed, show the actual error message
            echo "$install_output"
            exit $install_exit_code
          fi
        fi
      `;
    });

    it('should use toolName as binary name if toolConfig.binaries is empty and return path', async () => {
      const configNoBinaries: ToolConfig = {
        name: toolName,
        version: '1.0.0',
        binaries: [],
        installationMethod: 'none',
        installParams: undefined,
      };
      const expectedBinaryPathFallback = path.join(
        mockConfig.paths.binariesDir,
        configNoBinaries.name,
        toolName
      );
      const result = await shimGenerator.generateForTool(toolName, configNoBinaries);

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      expect(fsMocks.writeFile.mock.calls[0]).toBeDefined();
      const writtenContent = fsMocks.writeFile.mock.calls[0]![1];
      expect(writtenContent).toContain(`TOOL_EXECUTABLE="${expectedBinaryPathFallback}"`);
    });

    it('should use toolName as binary name if toolConfig.binaries is undefined', async () => {
      const configUndefinedBinaries: ToolConfig = {
        name: toolName,
        version: '1.0.0',
        binaries: undefined,
        installationMethod: 'none',
        installParams: undefined,
      };
      const expectedBinaryPathFallback = path.join(
        mockConfig.paths.binariesDir,
        configUndefinedBinaries.name,
        toolName
      );
      const result = await shimGenerator.generateForTool(toolName, configUndefinedBinaries);

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      expect(fsMocks.writeFile.mock.calls[0]).toBeDefined();
      const writtenContent = fsMocks.writeFile.mock.calls[0]![1];
      expect(writtenContent).toContain(`TOOL_EXECUTABLE="${expectedBinaryPathFallback}"`);
    });

    it('should attempt file operations and return path (simulating dry run with mock FS)', async () => {
      const result = await shimGenerator.generateForTool(toolName, toolConfig, {});

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.ensureDir).toHaveBeenCalledWith(mockConfig.paths.targetDir);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      expect(fsMocks.chmod).toHaveBeenCalledWith(expectedShimPath, 0o755);
    });

    it('should skip if shim exists and overwrite is false, returning empty array', async () => {
      fsMocks.exists.mockResolvedValue(true);
      const result = await shimGenerator.generateForTool(toolName, toolConfig, {
        overwrite: false,
      });

      expect(result).toEqual([]);
      expect(fsMocks.writeFile).not.toHaveBeenCalled();
      expect(fsMocks.chmod).not.toHaveBeenCalled();
    });

    it('should overwrite if shim exists and overwrite is true, returning path', async () => {
      fsMocks.exists.mockResolvedValue(true);
      // Mock that the existing file is our shim with wrong permissions
      fsMocks.readFile.mockResolvedValueOnce('#!/usr/bin/env bash\n# Generated by Dotfiles Management Tool');
      fsMocks.stat.mockResolvedValueOnce({ mode: 0o100644 } as any); // Wrong permissions
      
      const result = await shimGenerator.generateForTool(toolName, toolConfig, { overwrite: true });

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      expect(fsMocks.chmod).toHaveBeenCalledTimes(1);
    });
  });

  describe('generate', () => {
    it('should call generateForTool for each tool config and return all paths including generator shim', async () => {
      const configs: Record<string, ToolConfig> = {
        'tool-a': {
          name: 'tool-a',
          binaries: ['tool-a-bin'],
          version: '1.0',
          installationMethod: 'none',
          installParams: undefined,
        },
        'tool-b': {
          name: 'tool-b',
          binaries: ['tool-b-bin'],
          version: '2.0',
          installationMethod: 'none',
          installParams: undefined,
        },
      };
      const expectedPathA = path.join(mockConfig.paths.targetDir, 'tool-a');
      const expectedPathB = path.join(mockConfig.paths.targetDir, 'tool-b');

      const generateForToolSpy = spyOn(shimGenerator, 'generateForTool')
        .mockResolvedValueOnce([expectedPathA])
        .mockResolvedValueOnce([expectedPathB]);

      const result = await shimGenerator.generate(configs);

      expect(result).toEqual([expectedPathA, expectedPathB]);
      expect(generateForToolSpy).toHaveBeenCalledTimes(2);
      expect(generateForToolSpy).toHaveBeenCalledWith('tool-a', configs['tool-a'], undefined);
      expect(generateForToolSpy).toHaveBeenCalledWith('tool-b', configs['tool-b'], undefined);

      generateForToolSpy.mockRestore();
    });

    it('should handle empty toolConfigs object', async () => {
      const generateForToolSpy = spyOn(shimGenerator, 'generateForTool');

      const result = await shimGenerator.generate({});
      expect(result).toEqual([]);
      expect(generateForToolSpy).not.toHaveBeenCalled();

      generateForToolSpy.mockRestore();
    });

    it('should pass options (like overwrite) to generateForTool and generateShim, returning all paths', async () => {
      const configs: Record<string, ToolConfig> = {
        'tool-a': {
          name: 'tool-a',
          binaries: ['tool-a-bin'],
          version: '1.0',
          installationMethod: 'none',
          installParams: undefined,
        },
      };
      const options = { overwrite: true };
      const expectedPathA = path.join(mockConfig.paths.targetDir, 'tool-a');

      const generateForToolSpy = spyOn(shimGenerator, 'generateForTool').mockResolvedValueOnce([
        expectedPathA,
      ]);

      const result = await shimGenerator.generate(configs, options);

      expect(result).toEqual([expectedPathA]);
      expect(generateForToolSpy).toHaveBeenCalledWith('tool-a', configs['tool-a'], options);

      generateForToolSpy.mockRestore();
    });
  });

  describe('chmod optimization', () => {
    it('should skip chmod when file already has correct permissions', async () => {
      const expectedShimPath = path.join(mockConfig.paths.targetDir, 'test-tool');
      
      // Mock stat to return the desired permissions (755)
      fsMocks.stat.mockResolvedValueOnce({
        mode: 0o100755, // File with 755 permissions (0o100000 is regular file flag)
      } as any);

      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        installationMethod: 'none',
        installParams: undefined,
      };

      await shimGenerator.generateForTool('test-tool', toolConfig);

      // Should write file but skip chmod since permissions are already correct
      expect(fsMocks.writeFile).toHaveBeenCalledWith(expectedShimPath, expect.any(String));
      expect(fsMocks.stat).toHaveBeenCalledWith(expectedShimPath);
      expect(fsMocks.chmod).not.toHaveBeenCalled();
    });

    it('should call chmod when file has incorrect permissions', async () => {
      const expectedShimPath = path.join(mockConfig.paths.targetDir, 'test-tool');
      
      // Mock stat to return different permissions (644)
      fsMocks.stat.mockResolvedValueOnce({
        mode: 0o100644, // File with 644 permissions
      } as any);

      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        installationMethod: 'none',
        installParams: undefined,
      };

      await shimGenerator.generateForTool('test-tool', toolConfig);

      // Should write file and call chmod to fix permissions
      expect(fsMocks.writeFile).toHaveBeenCalledWith(expectedShimPath, expect.any(String));
      expect(fsMocks.stat).toHaveBeenCalledWith(expectedShimPath);
      expect(fsMocks.chmod).toHaveBeenCalledWith(expectedShimPath, 0o755);
    });

    it('should call chmod when stat fails', async () => {
      const expectedShimPath = path.join(mockConfig.paths.targetDir, 'test-tool');
      
      // Mock stat to throw an error
      fsMocks.stat.mockRejectedValueOnce(new Error('Stat failed'));

      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        installationMethod: 'none',
        installParams: undefined,
      };

      await shimGenerator.generateForTool('test-tool', toolConfig);

      // Should write file and call chmod as fallback
      expect(fsMocks.writeFile).toHaveBeenCalledWith(expectedShimPath, expect.any(String));
      expect(fsMocks.stat).toHaveBeenCalledWith(expectedShimPath);
      expect(fsMocks.chmod).toHaveBeenCalledWith(expectedShimPath, 0o755);
    });
  });

  describe('conflicting files', () => {
    const toolName = 'test-tool';
    const toolConfig: ToolConfig = {
      name: toolName,
      binaries: ['test-tool'],
      version: '1.0.0',
      installationMethod: 'none',
      installParams: undefined,
    };

    it('should skip and log error when non-shim file exists at target location', async () => {
      // Mock file exists but is not our shim
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockResolvedValueOnce('some other content');

      const result = await shimGenerator.generateForTool(toolName, toolConfig);

      expect(result).toEqual([]);
      expect(fsMocks.writeFile).not.toHaveBeenCalled();
      expect(fsMocks.chmod).not.toHaveBeenCalled();
      
      // Should log error about conflicting file
      logger.expect(['ERROR'], ['ShimGenerator'], [/Cannot create shim for "test-tool": conflicting file exists/]);
    });

    it('should skip silently when our shim exists and overwrite is false', async () => {
      // Mock file exists and is our shim
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockResolvedValueOnce('#!/usr/bin/env bash\n# Generated by Dotfiles Management Tool');

      const result = await shimGenerator.generateForTool(toolName, toolConfig, { overwrite: false });

      expect(result).toEqual([]);
      expect(fsMocks.writeFile).not.toHaveBeenCalled();
      expect(fsMocks.chmod).not.toHaveBeenCalled();
      
      // Should not log error - only check that no error was logged by not calling logger.expect with ERROR
    });

    it('should overwrite when our shim exists and overwrite is true', async () => {
      const expectedShimPath = path.join(mockConfig.paths.targetDir, toolName);
      
      // Mock file exists and is our shim
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockResolvedValueOnce('#!/usr/bin/env bash\n# Generated by Dotfiles Management Tool');
      fsMocks.stat.mockResolvedValueOnce({ mode: 0o100755 } as any);

      const result = await shimGenerator.generateForTool(toolName, toolConfig, { overwrite: true });

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      
      // Should not log error - only check that no error was logged by not calling logger.expect with ERROR
    });

    it('should log error and skip when non-shim file exists even with overwrite true', async () => {
      // Mock file exists but is not our shim
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockResolvedValueOnce('some other content');

      const result = await shimGenerator.generateForTool(toolName, toolConfig, { overwrite: true });

      expect(result).toEqual([]);
      expect(fsMocks.writeFile).not.toHaveBeenCalled();
      expect(fsMocks.chmod).not.toHaveBeenCalled();
      
      // Should log error about conflicting file
      logger.expect(['ERROR'], ['ShimGenerator'], [/Cannot create shim for "test-tool": conflicting file exists/]);
    });

    it('should treat unreadable files as non-shims', async () => {
      // Mock file exists but can't be read
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockRejectedValueOnce(new Error('Permission denied'));

      const result = await shimGenerator.generateForTool(toolName, toolConfig);

      expect(result).toEqual([]);
      expect(fsMocks.writeFile).not.toHaveBeenCalled();
      
      // Should log error about conflicting file
      logger.expect(['ERROR'], ['ShimGenerator'], [/Cannot create shim for "test-tool": conflicting file exists/]);
    });
  });
});
