import { describe, expect, it, beforeEach } from 'bun:test';
import { BashGenerator } from '../BashGenerator';
import type { YamlConfig } from '@modules/config';
import type { ToolConfig } from '@types';
import { always } from '@types';
import { createSectionHeader } from '../../shellTemplates';

describe('BashGenerator', () => {
  let generator: BashGenerator;
  let mockAppConfig: YamlConfig;

  beforeEach(() => {
    mockAppConfig = {
      paths: {
        homeDir: '/home/test',
        dotfilesDir: '/home/test/.dotfiles',
        generatedDir: '/home/test/.dotfiles/.generated',
        shellScriptsDir: '/home/test/.dotfiles/.generated/shell-scripts',
        binariesDir: '/home/test/.dotfiles/.generated/bin',
        targetDir: '/usr/local/bin',
        toolConfigsDir: '/home/test/.dotfiles/configs/tools',
        manifestPath: '/home/test/.dotfiles/.generated/manifest.json',
      },
    } as YamlConfig;
    generator = new BashGenerator(mockAppConfig);
  });

  it('should have correct shell type and file extension', () => {
    expect(generator.shellType).toBe('bash');
    expect(generator.fileExtension).toBe('.bash');
  });

  it('should process native bash syntax', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test'],
      version: '1.0.0',
      shellConfigs: {
        bash: {
          scripts: [
            always`export TEST_VAR="value"`,
            always`export PATH="/opt/test/bin:$PATH"`,
            always`declare -U PATH`,
            always`# Bash-specific completion setup`,
          ],
        },
      },
      installationMethod: 'none',
      installParams: undefined,
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    // With the new branded types system, scripts are stored in alwaysScripts
    expect(content.alwaysScripts).toHaveLength(4);
    expect(content.onceScripts).toHaveLength(0);
    expect(content.environmentVariables).toHaveLength(0);
    expect(content.pathModifications).toHaveLength(0);
    expect(content.toolInit).toHaveLength(0);
  });

  it('should process completions for bash', () => {
    const completions = {
      bash: { source: 'test-tool.bash' },
    };

    const result = generator.processCompletions('test-tool', completions);

    expect(result).toContain('[[ -f "/home/test/.dotfiles/.generated/shell-scripts/bash/test-tool.bash" ]] && source "/home/test/.dotfiles/.generated/shell-scripts/bash/test-tool.bash"');
  });

  it('should generate complete file content with bash syntax', () => {
    const toolContents = new Map([
      ['tool1', {
        toolInit: ['alias t1="tool1"'],
        pathModifications: ['PATH="$PATH:/opt/tool1/bin"'],
        environmentVariables: ['export TOOL1_ENV="value"'],
        completionSetup: ['[[ -f "/completions/tool1.bash" ]] && source "/completions/tool1.bash"'],
        onceScripts: [],
        alwaysScripts: [],
      }],
    ]);

    const content = generator.generateFileContent(toolContents);

    expect(content).toContain('# THIS FILE IS AUTOMATICALLY GENERATED');
    expect(content).toContain(createSectionHeader('bash', 'PATH Modifications'));
    expect(content).toContain('export PATH="/home/test/.dotfiles/.generated/bin:$PATH"');
    expect(content).toContain('PATH="$PATH:/opt/tool1/bin"');
    expect(content).toContain(createSectionHeader('bash', 'Environment Variables'));
    expect(content).toContain('export TOOL1_ENV="value"');
    expect(content).toContain(createSectionHeader('bash', 'Shell Completions Setup'));
    expect(content).toContain('[[ -f "/completions/tool1.bash" ]] && source "/completions/tool1.bash"');
  });

  it('should return correct default output path', () => {
    const path = generator.getDefaultOutputPath();
    expect(path).toBe('/home/test/.dotfiles/.generated/shell-scripts/main.bash');
  });
});