import { describe, expect, it, beforeEach } from 'bun:test';
import { PowerShellGenerator } from '../PowerShellGenerator';
import type { YamlConfig } from '@modules/config';
import type { ToolConfig } from '@types';
import { createSectionHeader } from '../../shellTemplates';

describe('PowerShellGenerator', () => {
  let generator: PowerShellGenerator;
  let mockAppConfig: YamlConfig;

  beforeEach(() => {
    mockAppConfig = {
      paths: {
        homeDir: '/home/test',
        dotfilesDir: '/home/test/.dotfiles',
        generatedDir: '/home/test/.dotfiles/.generated',
        shellScriptsDir: '/home/test/.dotfiles/.generated/shell-scripts',
        binariesDir: '/home/test/.dotfiles/.generated/bin',
        targetDir: '/usr/local/bin',
        toolConfigsDir: '/home/test/.dotfiles/configs/tools',
        manifestPath: '/home/test/.dotfiles/.generated/manifest.json',
      },
    } as YamlConfig;
    generator = new PowerShellGenerator(mockAppConfig);
  });

  it('should have correct shell type and file extension', () => {
    expect(generator.shellType).toBe('powershell');
    expect(generator.fileExtension).toBe('.ps1');
  });

  it('should process native PowerShell syntax', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test'],
      version: '1.0.0',
      powershellInit: [
        '$env:TEST_VAR = "value"',
        '$env:PATH = "/opt/test/bin;$env:PATH"',
        'function test { test-tool --verbose }',
        '. ~/.testrc',
      ],
      installationMethod: 'none',
      installParams: undefined,
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    expect(content.environmentVariables).toContain('$env:TEST_VAR = "value"');
    expect(content.pathModifications).toContain('$env:PATH = "/opt/test/bin;$env:PATH"');
    expect(content.toolInit).toContain('function test { test-tool --verbose }');
    expect(content.toolInit).toContain('. ~/.testrc');
  });

  it('should process completions for PowerShell', () => {
    const completions = {
      powershell: { source: 'test-tool.ps1' },
    };

    const result = generator.processCompletions('test-tool', completions);

    expect(result).toContain('if (Test-Path "/home/test/.dotfiles/.generated/shell-scripts/powershell/test-tool.ps1") { . "/home/test/.dotfiles/.generated/shell-scripts/powershell/test-tool.ps1" }');
  });

  it('should generate complete file content with PowerShell syntax', () => {
    const toolContents = new Map([
      ['tool1', {
        toolInit: ['function t1 { tool1 }'],
        pathModifications: ['$env:PATH = "/opt/tool1/bin;$env:PATH"'],
        environmentVariables: ['$env:TOOL1_ENV = "value"'],
        completionSetup: ['if (Test-Path "/completions/tool1.ps1") { . "/completions/tool1.ps1" }'],
      }],
    ]);

    const content = generator.generateFileContent(toolContents);

    expect(content).toContain('# THIS FILE IS AUTOMATICALLY GENERATED');
    expect(content).toContain(createSectionHeader('powershell', 'PATH Modifications'));
    expect(content).toContain('$env:PATH = "/home/test/.dotfiles/.generated/bin;$env:PATH"');
    expect(content).toContain('$env:PATH = "/opt/tool1/bin;$env:PATH"');
    expect(content).toContain(createSectionHeader('powershell', 'Environment Variables'));
    expect(content).toContain('$env:TOOL1_ENV = "value"');
    expect(content).toContain(createSectionHeader('powershell', 'Shell Completions Setup'));
    expect(content).toContain('if (Test-Path "/completions/tool1.ps1") { . "/completions/tool1.ps1" }');
  });

  it('should return correct default output path', () => {
    const path = generator.getDefaultOutputPath();
    expect(path).toBe('/home/test/.dotfiles/.generated/shell-scripts/main.ps1');
  });
});