import { describe, expect, it, beforeEach } from 'bun:test';
import { ZshGenerator } from '../ZshGenerator';
import type { YamlConfig } from '@modules/config';
import type { ToolConfig } from '@types';
import { createSectionHeader } from '../../shellTemplates';

describe('ZshGenerator', () => {
  let generator: ZshGenerator;
  let mockAppConfig: YamlConfig;

  beforeEach(() => {
    mockAppConfig = {
      paths: {
        homeDir: '/home/test',
        dotfilesDir: '/home/test/.dotfiles',
        generatedDir: '/home/test/.dotfiles/.generated',
        shellScriptsDir: '/home/test/.dotfiles/.generated/shell-scripts',
        binariesDir: '/home/test/.dotfiles/.generated/bin',
        targetDir: '/usr/local/bin',
        toolConfigsDir: '/home/test/.dotfiles/configs/tools',
        manifestPath: '/home/test/.dotfiles/.generated/manifest.json',
      },
    } as YamlConfig;
    generator = new ZshGenerator(mockAppConfig);
  });

  it('should have correct shell type and file extension', () => {
    expect(generator.shellType).toBe('zsh');
    expect(generator.fileExtension).toBe('.zsh');
  });

  it('should extract shell content from tool config with zshInit', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test'],
      version: '1.0.0',
      zshInit: [
        'export TEST_VAR="value"',
        'export PATH="/opt/test/bin:$PATH"',
        'alias test="test-tool --verbose"',
      ],
      installationMethod: 'none',
      installParams: undefined,
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    expect(content.environmentVariables).toContain('export TEST_VAR="value"');
    expect(content.pathModifications).toContain('export PATH="/opt/test/bin:$PATH"');
    expect(content.toolInit).toContain('alias test="test-tool --verbose"');
  });

  it('should process completions for zsh', () => {
    const completions = {
      zsh: { source: '_test-tool' },
    };

    const result = generator.processCompletions('test-tool', completions);

    expect(result).toContain('fpath=("/home/test/.dotfiles/.generated/shell-scripts/zsh" $fpath)');
  });

  it('should generate complete file content', () => {
    const toolContents = new Map([
      ['tool1', {
        toolInit: ['alias t1="tool1"'],
        pathModifications: ['export PATH="/opt/tool1/bin:$PATH"'],
        environmentVariables: ['export TOOL1_ENV="value"'],
        completionSetup: ['fpath=("/completions/zsh" $fpath)'],
      }],
      ['tool2', {
        toolInit: ['source ~/.tool2rc'],
        pathModifications: [],
        environmentVariables: ['export TOOL2_DEBUG=true'],
        completionSetup: [],
      }],
    ]);

    const content = generator.generateFileContent(toolContents);

    expect(content).toContain('# THIS FILE IS AUTOMATICALLY GENERATED');
    expect(content).toContain(createSectionHeader('zsh', 'PATH Modifications'));
    expect(content).toContain('export PATH="/home/test/.dotfiles/.generated/bin:$PATH"');
    expect(content).toContain('export PATH="/opt/tool1/bin:$PATH"');
    expect(content).toContain(createSectionHeader('zsh', 'Environment Variables'));
    expect(content).toContain('export TOOL1_ENV="value"');
    expect(content).toContain('export TOOL2_DEBUG=true');
    expect(content).toContain(createSectionHeader('zsh', 'Tool-Specific Initializations'));
    expect(content).toContain('alias t1="tool1"');
    expect(content).toContain('source ~/.tool2rc');
    expect(content).toContain(createSectionHeader('zsh', 'Shell Completions Setup'));
    expect(content).toContain('typeset -U fpath');
    expect(content).toContain('fpath=("/completions/zsh" $fpath)');
    expect(content).toContain(createSectionHeader('zsh', 'End of Generated File'));
  });

  it('should return correct default output path', () => {
    const path = generator.getDefaultOutputPath();
    expect(path).toBe('/home/test/.dotfiles/.generated/shell-scripts/main.zsh');
  });
});