export const HTTP_PIPELINE_ERROR_CODES = [
  'GITHUB_RELEASE_NOT_FOUND',
  'GITHUB_ASSET_NOT_FOUND',
  'GITHUB_RATE_LIMIT_EXCEEDED',
  'GITHUB_INVALID_RELEASE_SCHEMA',
  'CARGO_CRATE_NOT_FOUND',
  'CARGO_INVALID_METADATA_SCHEMA',
  'DOWNLOAD_NETWORK_FAILURE',
  'DOWNLOAD_TIMEOUT',
  'ARCHIVE_UNPACK_FAILED',
  'ARCHIVE_PATH_TRAVERSAL_BLOCKED',
  'BINARY_NOT_FOUND_IN_ARCHIVE',
  'HOOK_EXECUTION_FAILED',
  'BINARY_SETUP_FAILED',
] as const;

export type HttpPipelineErrorCode = (typeof HTTP_PIPELINE_ERROR_CODES)[number];
