import { beforeEach, describe, expect, it, spyOn } from 'bun:test';
import path from 'node:path';
import type { ProjectConfig } from '@dotfiles/config';
import type { ToolConfig } from '@dotfiles/core';
import { createMemFileSystem, type FileSystemSpies, type Stats } from '@dotfiles/file-system';
import { TestLogger } from '@dotfiles/logger';
import { createMockProjectConfig, createTestDirectories, type ITestDirectories } from '@dotfiles/testing-helpers';
import { ShimGenerator } from '../ShimGenerator';

import '@dotfiles/testing-helpers';

describe('ShimGenerator', () => {
  let mockConfig: ProjectConfig;
  let shimGenerator: ShimGenerator;
  let fsMocks: FileSystemSpies;
  let logger: TestLogger;
  let testDirs: ITestDirectories;

  beforeEach(async () => {
    const { fs, spies } = await createMemFileSystem({});
    fsMocks = spies;
    logger = new TestLogger();

    testDirs = await createTestDirectories(logger, fs, { testName: 'shim-generator' });

    mockConfig = await createMockProjectConfig({
      config: {
        paths: testDirs.paths,
      },
      filePath: path.join(testDirs.paths.dotfilesDir, 'config.yaml'),
      fileSystem: fs,
      logger,
      systemInfo: { platform: 'linux', arch: 'x64', homeDir: testDirs.paths.homeDir },
      env: {},
    });

    shimGenerator = new ShimGenerator(logger, fs, mockConfig);

    // Clear all mock calls from the setup phase (createMockProjectConfig writes config file)
    Object.values(fsMocks).forEach((mock) => {
      if (typeof mock.mockClear === 'function') {
        mock.mockClear();
      }
    });
  });

  describe('constructor', () => {
    it('should initialize correctly', () => {
      expect(shimGenerator).toBeInstanceOf(ShimGenerator);
    });
  });

  describe('generateForTool', () => {
    const toolName = 'my-tool';
    const toolConfig: ToolConfig = {
      name: toolName,
      binaries: ['my-tool-binary'],
      version: '1.0.0',
      installationMethod: 'manual',
      installParams: {},
    };
    let expectedShimPath: string;
    let expectedBinaryPath: string;

    beforeEach(() => {
      const firstBinary = toolConfig.binaries![0]!;
      const binaryName = typeof firstBinary === 'string' ? firstBinary : firstBinary.name;
      expectedShimPath = path.join(mockConfig.paths.targetDir, binaryName);
      expectedBinaryPath = path.join(mockConfig.paths.binariesDir, toolConfig.name, binaryName);
    });

    it('should generate correct shim content, write file, and return shim path', async () => {
      const result = await shimGenerator.generateForTool(toolName, toolConfig);

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.ensureDir).toHaveBeenCalledWith(mockConfig.paths.targetDir);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      expect(fsMocks.writeFile.mock.calls[0]).toBeDefined();
      expect(fsMocks.chmod).toHaveBeenCalledWith(expectedShimPath, 0o755);

      const writtenContent = String(fsMocks.writeFile.mock.calls[0]![1]);

      expect(writtenContent).toMatchLooseInlineSnapshot`
        #!/usr/bin/env bash
        # Shim for my-tool-binary
        # Generated by Dotfiles Management Tool

        set -euo pipefail

        TOOL_NAME="my-tool"
        TOOL_EXECUTABLE="${expectedBinaryPath}"
        GENERATOR_CLI_EXECUTABLE="${expect.anything}"
        CONFIG_PATH="${/.+\/config\.yaml/}"

        # Check for recursion
        RECURSION_ENV_VAR="DOTFILES_INSTALLING_MY_TOOL"

        if [ -n "\${!RECURSION_ENV_VAR:-}" ]; then
          echo "Recursive installation detected for $TOOL_NAME. Aborting to prevent infinite loop." >&2
          exit 1
        fi

        # Check if the first argument is @update
        if [ $# -gt 0 ] && [ "$1" = "@update" ]; then
          echo "Updating $TOOL_NAME to latest version..."
          # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
          eval "$GENERATOR_CLI_EXECUTABLE" update --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"'
          exit $?
        fi

        # Check if tool exists and execute it
        if [ -x "$TOOL_EXECUTABLE" ]; then
          exec "$TOOL_EXECUTABLE" "$@"
        else
          # Tool not found, try to install it
          # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
          # Let stderr (progress bars) pass through to the user
          # Temporarily disable set -e to handle install failures gracefully
          set +e
          eval "$GENERATOR_CLI_EXECUTABLE" install --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"'
          install_exit_code=$?
          set -e
          
          if [ $install_exit_code -eq 0 ]; then
            # Installation successful, try to execute binary again
            if [ -x "$TOOL_EXECUTABLE" ]; then
              exec "$TOOL_EXECUTABLE" "$@"
            else
              echo "Installation completed but binary not found at: $TOOL_EXECUTABLE" >&2
              exit 1
            fi
          else
            # Installation failed, exit with the same code
            exit $install_exit_code
          fi
        fi
      `;
    });

    it('should use toolName as binary name if toolConfig.binaries is empty and return path', async () => {
      const configNoBinaries: ToolConfig = {
        name: toolName,
        version: '1.0.0',
        binaries: [],
        installationMethod: 'manual',
        installParams: {},
      };
      const expectedBinaryPathFallback = path.join(mockConfig.paths.binariesDir, configNoBinaries.name, toolName);
      const result = await shimGenerator.generateForTool(toolName, configNoBinaries);
      const fallbackShimPath = path.join(mockConfig.paths.targetDir, toolName);

      expect(result).toEqual([fallbackShimPath]);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      expect(fsMocks.writeFile.mock.calls[0]).toBeDefined();
      const writtenContent = fsMocks.writeFile.mock.calls[0]![1];
      expect(writtenContent).toContain(`TOOL_EXECUTABLE="${expectedBinaryPathFallback}"`);
    });

    it('should use toolName as binary name if toolConfig.binaries is undefined', async () => {
      const configUndefinedBinaries: ToolConfig = {
        name: toolName,
        version: '1.0.0',
        binaries: undefined,
        installationMethod: 'manual',
        installParams: {},
      };
      const expectedBinaryPathFallback = path.join(
        mockConfig.paths.binariesDir,
        configUndefinedBinaries.name,
        toolName
      );
      const result = await shimGenerator.generateForTool(toolName, configUndefinedBinaries);
      const fallbackShimPath = path.join(mockConfig.paths.targetDir, toolName);

      expect(result).toEqual([fallbackShimPath]);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      expect(fsMocks.writeFile.mock.calls[0]).toBeDefined();
      const writtenContent = fsMocks.writeFile.mock.calls[0]![1];
      expect(writtenContent).toContain(`TOOL_EXECUTABLE="${expectedBinaryPathFallback}"`);
    });

    it('should attempt file operations and return path (simulating dry run with mock FS)', async () => {
      const result = await shimGenerator.generateForTool(toolName, toolConfig, {});

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.ensureDir).toHaveBeenCalledWith(mockConfig.paths.targetDir);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      expect(fsMocks.chmod).toHaveBeenCalledWith(expectedShimPath, 0o755);
    });

    it('should skip if shim exists and overwrite is false, returning empty array', async () => {
      fsMocks.exists.mockResolvedValue(true);
      const result = await shimGenerator.generateForTool(toolName, toolConfig, {
        overwrite: false,
      });

      expect(result).toEqual([]);
      expect(fsMocks.writeFile).not.toHaveBeenCalled();
      expect(fsMocks.chmod).not.toHaveBeenCalled();
    });

    it('should overwrite if shim exists and overwrite is true, returning path', async () => {
      fsMocks.exists.mockResolvedValue(true);
      // Mock that the existing file is our shim with wrong permissions
      fsMocks.readFile.mockResolvedValueOnce('#!/usr/bin/env bash\n# Generated by Dotfiles Management Tool');
      fsMocks.stat.mockResolvedValueOnce({ mode: 0o100644, isFile: () => true, isDirectory: () => false } as Stats);

      const result = await shimGenerator.generateForTool(toolName, toolConfig, { overwrite: true });

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      expect(fsMocks.chmod).toHaveBeenCalledTimes(1);
    });
  });

  describe('generate', () => {
    it('should call generateForTool for each tool config and return all paths including generator shim', async () => {
      const configs: Record<string, ToolConfig> = {
        'tool-a': {
          name: 'tool-a',
          binaries: ['tool-a-bin'],
          version: '1.0',
          installationMethod: 'manual',
          installParams: {},
        },
        'tool-b': {
          name: 'tool-b',
          binaries: ['tool-b-bin'],
          version: '2.0',
          installationMethod: 'manual',
          installParams: {},
        },
      };
      const expectedPathA = path.join(mockConfig.paths.targetDir, 'tool-a');
      const expectedPathB = path.join(mockConfig.paths.targetDir, 'tool-b');

      const generateForToolSpy = spyOn(shimGenerator, 'generateForTool')
        .mockResolvedValueOnce([expectedPathA])
        .mockResolvedValueOnce([expectedPathB]);

      const result = await shimGenerator.generate(configs);

      expect(result).toEqual([expectedPathA, expectedPathB]);
      expect(generateForToolSpy).toHaveBeenCalledTimes(2);
      expect(generateForToolSpy).toHaveBeenCalledWith('tool-a', configs['tool-a'], undefined);
      expect(generateForToolSpy).toHaveBeenCalledWith('tool-b', configs['tool-b'], undefined);

      generateForToolSpy.mockRestore();
    });

    it('should handle empty toolConfigs object', async () => {
      const generateForToolSpy = spyOn(shimGenerator, 'generateForTool');

      const result = await shimGenerator.generate({});
      expect(result).toEqual([]);
      expect(generateForToolSpy).not.toHaveBeenCalled();

      generateForToolSpy.mockRestore();
    });

    it('should pass options (like overwrite) to generateForTool and generateShim, returning all paths', async () => {
      const configs: Record<string, ToolConfig> = {
        'tool-a': {
          name: 'tool-a',
          binaries: ['tool-a-bin'],
          version: '1.0',
          installationMethod: 'manual',
          installParams: {},
        },
      };
      const options = { overwrite: true };
      const expectedPathA = path.join(mockConfig.paths.targetDir, 'tool-a');

      const generateForToolSpy = spyOn(shimGenerator, 'generateForTool').mockResolvedValueOnce([expectedPathA]);

      const result = await shimGenerator.generate(configs, options);

      expect(result).toEqual([expectedPathA]);
      expect(generateForToolSpy).toHaveBeenCalledWith('tool-a', configs['tool-a'], options);

      generateForToolSpy.mockRestore();
    });
  });

  describe('chmod optimization', () => {
    it('should skip chmod when file already has correct permissions', async () => {
      const expectedShimPath = path.join(mockConfig.paths.targetDir, 'test-tool');

      // Mock stat to return the desired permissions (755)
      fsMocks.stat.mockResolvedValueOnce({
        mode: 0o100755,
        isFile: () => true,
        isDirectory: () => false,
      } as Stats);

      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        installationMethod: 'manual',
        installParams: {},
      };

      await shimGenerator.generateForTool('test-tool', toolConfig);

      // Should write file but skip chmod since permissions are already correct
      expect(fsMocks.writeFile).toHaveBeenCalledWith(expectedShimPath, expect.any(String));
      expect(fsMocks.stat).toHaveBeenCalledWith(expectedShimPath);
      expect(fsMocks.chmod).not.toHaveBeenCalled();
    });

    it('should call chmod when file has incorrect permissions', async () => {
      const expectedShimPath = path.join(mockConfig.paths.targetDir, 'test-tool');

      // Mock stat to return different permissions (644)
      fsMocks.stat.mockResolvedValueOnce({
        mode: 0o100644, // File with 644 permissions
      } as Stats);

      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        installationMethod: 'manual',
        installParams: {},
      };

      await shimGenerator.generateForTool('test-tool', toolConfig);

      // Should write file and call chmod to fix permissions
      expect(fsMocks.writeFile).toHaveBeenCalledWith(expectedShimPath, expect.any(String));
      expect(fsMocks.stat).toHaveBeenCalledWith(expectedShimPath);
      expect(fsMocks.chmod).toHaveBeenCalledWith(expectedShimPath, 0o755);
    });

    it('should call chmod when stat fails', async () => {
      const expectedShimPath = path.join(mockConfig.paths.targetDir, 'test-tool');

      // Mock stat to throw an error
      fsMocks.stat.mockRejectedValueOnce(new Error('Stat failed'));

      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        installationMethod: 'manual',
        installParams: {},
      };

      await shimGenerator.generateForTool('test-tool', toolConfig);

      // Should write file and call chmod as fallback
      expect(fsMocks.writeFile).toHaveBeenCalledWith(expectedShimPath, expect.any(String));
      expect(fsMocks.stat).toHaveBeenCalledWith(expectedShimPath);
      expect(fsMocks.chmod).toHaveBeenCalledWith(expectedShimPath, 0o755);
    });
  });

  describe('conflicting files', () => {
    const toolName = 'test-tool';
    const toolConfig: ToolConfig = {
      name: toolName,
      binaries: ['test-tool'],
      version: '1.0.0',
      installationMethod: 'manual',
      installParams: {},
    };

    it('should skip and log error when non-shim file exists at target location', async () => {
      // Mock file exists but is not our shim
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockResolvedValueOnce('some other content');

      const result = await shimGenerator.generateForTool(toolName, toolConfig);

      expect(result).toEqual([]);
      expect(fsMocks.writeFile).not.toHaveBeenCalled();
      expect(fsMocks.chmod).not.toHaveBeenCalled();

      // Should log error about conflicting file
      logger.expect(
        ['ERROR'],
        ['ShimGenerator', 'generateShimForBinary'],
        [/Cannot create shim for "test-tool": conflicting file exists/]
      );
    });

    it('should skip silently when our shim exists and overwrite is false', async () => {
      // Mock file exists and is our shim
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockResolvedValueOnce('#!/usr/bin/env bash\n# Generated by Dotfiles Management Tool');

      const result = await shimGenerator.generateForTool(toolName, toolConfig, { overwrite: false });

      expect(result).toEqual([]);
      expect(fsMocks.writeFile).not.toHaveBeenCalled();
      expect(fsMocks.chmod).not.toHaveBeenCalled();

      // Should not log error - only check that no error was logged by not calling logger.expect with ERROR
    });

    it('should overwrite when our shim exists and overwrite is true', async () => {
      const expectedShimPath = path.join(mockConfig.paths.targetDir, toolName);

      // Mock file exists and is our shim
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockResolvedValueOnce('#!/usr/bin/env bash\n# Generated by Dotfiles Management Tool');
      fsMocks.stat.mockResolvedValueOnce({ mode: 0o100755, isFile: () => true, isDirectory: () => false } as Stats);

      const result = await shimGenerator.generateForTool(toolName, toolConfig, { overwrite: true });

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);

      // Should not log error - only check that no error was logged by not calling logger.expect with ERROR
    });

    it('should log error and skip when non-shim file exists even with overwrite true', async () => {
      // Mock file exists but is not our shim
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockResolvedValueOnce('some other content');

      const result = await shimGenerator.generateForTool(toolName, toolConfig, { overwrite: true });

      expect(result).toEqual([]);
      expect(fsMocks.writeFile).not.toHaveBeenCalled();
      expect(fsMocks.chmod).not.toHaveBeenCalled();

      // Should log error about conflicting file
      logger.expect(
        ['ERROR'],
        ['ShimGenerator', 'generateShimForBinary'],
        [/Cannot create shim for "test-tool": conflicting file exists/]
      );
    });

    it('should overwrite non-shim file when overwriteConflicts is true', async () => {
      const expectedShimPath = path.join(mockConfig.paths.targetDir, toolName);

      // Mock file exists but is not our shim
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockResolvedValueOnce('some other content');
      fsMocks.stat.mockResolvedValueOnce({ mode: 0o100755, isFile: () => true, isDirectory: () => false } as Stats);

      const result = await shimGenerator.generateForTool(toolName, toolConfig, { overwriteConflicts: true });

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
      // Behavior verified: shim was created despite conflicting file existing
    });

    it('should overwrite non-shim file when both overwrite and overwriteConflicts are true', async () => {
      const expectedShimPath = path.join(mockConfig.paths.targetDir, toolName);

      // Mock file exists but is not our shim
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockResolvedValueOnce('some other content');
      fsMocks.stat.mockResolvedValueOnce({ mode: 0o100755, isFile: () => true, isDirectory: () => false } as Stats);

      const result = await shimGenerator.generateForTool(toolName, toolConfig, {
        overwrite: true,
        overwriteConflicts: true,
      });

      expect(result).toEqual([expectedShimPath]);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);
    });

    it('should treat unreadable files as non-shims', async () => {
      // Mock file exists but can't be read
      fsMocks.exists.mockResolvedValueOnce(true);
      fsMocks.readFile.mockRejectedValueOnce(new Error('Permission denied'));

      const result = await shimGenerator.generateForTool(toolName, toolConfig);

      expect(result).toEqual([]);
      expect(fsMocks.writeFile).not.toHaveBeenCalled();

      // Should log error about conflicting file
      logger.expect(
        ['ERROR'],
        ['ShimGenerator', 'generateShimForBinary'],
        [/Cannot create shim for "test-tool": conflicting file exists/]
      );
    });
  });

  describe('@update functionality', () => {
    const toolName = 'test-tool';
    const toolConfig: ToolConfig = {
      name: toolName,
      binaries: ['test-binary'],
      version: '1.0.0',
      installationMethod: 'github-release',
      installParams: { repo: 'owner/repo' },
    };

    it('should include @update detection logic in generated shim', async () => {
      const result = await shimGenerator.generateForTool(toolName, toolConfig);

      expect(result).toHaveLength(1);
      expect(fsMocks.writeFile).toHaveBeenCalledTimes(1);

      const writtenContent = fsMocks.writeFile.mock.calls[0]![1];

      // Should contain the @update detection block
      expect(writtenContent).toContain('# Check if the first argument is @update');
      expect(writtenContent).toContain('if [ $# -gt 0 ] && [ "$1" = "@update" ]; then');
      expect(writtenContent).toContain('echo "Updating $TOOL_NAME to latest version..."');
      expect(writtenContent).toContain('eval "$GENERATOR_CLI_EXECUTABLE" update --shim-mode --config');
      expect(writtenContent).toContain('exit $?');
    });

    it('should include tool name and config path in update command', async () => {
      const result = await shimGenerator.generateForTool(toolName, toolConfig);

      expect(result).toHaveLength(1);
      const writtenContent = fsMocks.writeFile.mock.calls[0]![1];

      // Should use the correct tool name and config path
      expect(writtenContent).toContain(`TOOL_NAME="${toolName}"`);
      expect(writtenContent).toContain(`CONFIG_PATH="${mockConfig.configFilePath}"`);
      expect(writtenContent).toContain('\'"$CONFIG_PATH"\' \'"$TOOL_NAME"\'');
    });

    it('should place @update check before normal execution logic', async () => {
      const result = await shimGenerator.generateForTool(toolName, toolConfig);

      expect(result).toHaveLength(1);
      const writtenContent = fsMocks.writeFile.mock.calls[0]![1];

      // @update check should come before the tool execution logic
      const content = String(writtenContent);
      const updateCheckIndex = content.indexOf('if [ $# -gt 0 ] && [ "$1" = "@update" ]');
      const toolExecutionIndex = content.indexOf('if [ -x "$TOOL_EXECUTABLE" ]; then');

      expect(updateCheckIndex).toBeGreaterThan(-1);
      expect(toolExecutionIndex).toBeGreaterThan(-1);
      expect(updateCheckIndex).toBeLessThan(toolExecutionIndex);
    });

    it('should use --shim-mode flag in update command', async () => {
      const result = await shimGenerator.generateForTool(toolName, toolConfig);

      expect(result).toHaveLength(1);
      const writtenContent = fsMocks.writeFile.mock.calls[0]![1];

      // Should include --shim-mode flag for suppressed logging
      expect(writtenContent).toContain('update --shim-mode --config');
      expect(writtenContent).toContain('install --shim-mode --config');
    });
  });
});
