// oxlint-disable-next-line import/no-unassigned-import
import "@dotfiles/testing-helpers";
import { describe, expect, it } from "bun:test";
import { generateSourceScript } from "../generateSourceScript";

describe("generateSourceScript", () => {
  it("should generate complete source script", () => {
    const script = generateSourceScript("/home/user/project/env", "env");

    expect(script).toMatchInlineSnapshot(`
      "#!/bin/sh
      # ==============================================================================
      # Dotfiles Virtual Environment Activation Script
      # ==============================================================================
      # This file is automatically generated. Do not edit directly.
      #
      # Usage:
      #   source env/source
      #   . ./env/source
      #
      # To deactivate:
      #   dotfiles-deactivate
      # ==============================================================================

      # Deactivate function to clean up environment
      dotfiles-deactivate() {
        if [ -n "\${DOTFILES_ENV_DIR:-}" ]; then
          # Restore original XDG_CONFIG_HOME
          if [ -n "\${_DOTFILES_OLD_XDG_CONFIG_HOME:-}" ]; then
            export XDG_CONFIG_HOME="\${_DOTFILES_OLD_XDG_CONFIG_HOME}"
            unset _DOTFILES_OLD_XDG_CONFIG_HOME
          else
            unset XDG_CONFIG_HOME
          fi
          unset DOTFILES_ENV_DIR
          unset DOTFILES_ENV_NAME
          unset -f dotfiles-deactivate 2>/dev/null
          echo "Deactivated dotfiles environment"
        fi
      }

      # If already active, deactivate first
      if [ -n "\${DOTFILES_ENV_DIR:-}" ]; then
        dotfiles-deactivate
      fi

      # Resolve the directory containing this script
      # Support both sourced and direct execution
      if [ -n "\${BASH_SOURCE[0]:-}" ]; then
        _dotfiles_script_dir="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
      elif [ -n "\${ZSH_VERSION:-}" ]; then
        _dotfiles_script_dir="$(cd "$(dirname "\${(%):-%x}")" && pwd)"
      else
        # Fallback to the hardcoded path
        _dotfiles_script_dir="/home/user/project/env"
      fi

      # Save old XDG_CONFIG_HOME for restoration on deactivate
      if [ -n "\${XDG_CONFIG_HOME:-}" ]; then
        export _DOTFILES_OLD_XDG_CONFIG_HOME="\${XDG_CONFIG_HOME}"
      fi

      # Export environment variables
      export DOTFILES_ENV_DIR="\${_dotfiles_script_dir}"
      export DOTFILES_ENV_NAME="env"
      export XDG_CONFIG_HOME="\${_dotfiles_script_dir}/.config"

      # Clean up temporary variable
      unset _dotfiles_script_dir

      echo "Activated dotfiles environment: env"
      echo "  Directory: \${DOTFILES_ENV_DIR}"
      echo "  Config: \${DOTFILES_ENV_DIR}/dotfiles.config.ts""
    `);
  });

  it("should include usage instructions with environment name", () => {
    const script = generateSourceScript("/path/to/my-project", "my-project");

    expect(script).toMatchLooseInlineSnapshot`
      # Usage:
      #   source my-project/source
      #   . ./my-project/source
    `;
  });

  it("should use fallback path in script when shell detection fails", () => {
    const script = generateSourceScript("/custom/fallback/path", "custom-env");

    expect(script).toMatchLooseInlineSnapshot`
      else
        # Fallback to the hardcoded path
        _dotfiles_script_dir="/custom/fallback/path"
      fi
    `;
  });

  it("should export environment variables with correct values", () => {
    const script = generateSourceScript("/any/path", "test-env");

    expect(script).toMatchLooseInlineSnapshot`
      # Export environment variables
      export DOTFILES_ENV_DIR="\${_dotfiles_script_dir}"
      export DOTFILES_ENV_NAME="test-env"
      export XDG_CONFIG_HOME="\${_dotfiles_script_dir}/.config"
    `;
  });

  it("should display activation message with environment name", () => {
    const script = generateSourceScript("/any/path", "dev-env");

    expect(script).toMatchLooseInlineSnapshot`
      echo "Activated dotfiles environment: dev-env"
      echo "  Directory: \${DOTFILES_ENV_DIR}"
      echo "  Config: \${DOTFILES_ENV_DIR}/dotfiles.config.ts"
    `;
  });
});
