// oxlint-disable-next-line import/no-unassigned-import
import '@dotfiles/testing-helpers';
import { describe, expect, it } from 'bun:test';
import { generatePowerShellSourceScript } from '../generatePowerShellSourceScript';

describe('generatePowerShellSourceScript', () => {
  it('should generate complete PowerShell source script', () => {
    const script = generatePowerShellSourceScript('/home/user/project/env', 'env');

    expect(script).toMatchInlineSnapshot(`
      "# ==============================================================================
      # Dotfiles Virtual Environment Activation Script (PowerShell)
      # ==============================================================================
      # This file is automatically generated. Do not edit directly.
      #
      # Usage:
      #   . .\\env\\source.ps1
      #   . env/source.ps1
      #
      # To deactivate:
      #   dotfiles-deactivate
      # ==============================================================================

      function global:dotfiles-deactivate {
        if ($env:DOTFILES_ENV_DIR) {
          # Restore original XDG_CONFIG_HOME
          if ($env:_DOTFILES_OLD_XDG_CONFIG_HOME) {
            $env:XDG_CONFIG_HOME = $env:_DOTFILES_OLD_XDG_CONFIG_HOME
            Remove-Item Env:_DOTFILES_OLD_XDG_CONFIG_HOME -ErrorAction SilentlyContinue
          } else {
            Remove-Item Env:XDG_CONFIG_HOME -ErrorAction SilentlyContinue
          }
          Remove-Item Env:DOTFILES_ENV_DIR -ErrorAction SilentlyContinue
          Remove-Item Env:DOTFILES_ENV_NAME -ErrorAction SilentlyContinue
          Remove-Item Function:dotfiles-deactivate -ErrorAction SilentlyContinue
          Write-Host "Deactivated dotfiles environment"
        }
      }

      # If already active, deactivate first
      if ($env:DOTFILES_ENV_DIR) {
        dotfiles-deactivate
      }

      # Resolve the directory containing this script
      $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
      if (-not $scriptDir) {
        # Fallback to hardcoded path
        $scriptDir = "/home/user/project/env"
      }

      # Save old XDG_CONFIG_HOME for restoration on deactivate
      if ($env:XDG_CONFIG_HOME) {
        $env:_DOTFILES_OLD_XDG_CONFIG_HOME = $env:XDG_CONFIG_HOME
      }

      # Export environment variables
      $env:DOTFILES_ENV_DIR = $scriptDir
      $env:DOTFILES_ENV_NAME = "env"
      $env:XDG_CONFIG_HOME = "$scriptDir\\.config"

      Write-Host "Activated dotfiles environment: env"
      Write-Host "  Directory: $env:DOTFILES_ENV_DIR"
      Write-Host "  Config: $env:DOTFILES_ENV_DIR\\dotfiles.config.ts""
    `);
  });

  it('should include usage instructions with environment name', () => {
    const script = generatePowerShellSourceScript('/path/to/my-project', 'my-project');

    expect(script).toMatchLooseInlineSnapshot`
      # Usage:
      #   . .\\my-project\\source.ps1
      #   . my-project/source.ps1
    `;
  });

  it('should use fallback path in script when detection fails', () => {
    const script = generatePowerShellSourceScript('/custom/fallback/path', 'custom-env');

    expect(script).toMatchLooseInlineSnapshot`
      if (-not $scriptDir) {
        # Fallback to hardcoded path
        $scriptDir = "/custom/fallback/path"
      }
    `;
  });

  it('should export environment variables with correct values', () => {
    const script = generatePowerShellSourceScript('/any/path', 'test-env');

    expect(script).toMatchLooseInlineSnapshot`
      # Export environment variables
      $env:DOTFILES_ENV_DIR = $scriptDir
      $env:DOTFILES_ENV_NAME = "test-env"
      $env:XDG_CONFIG_HOME = "$scriptDir\\.config"
    `;
  });

  it('should display activation message with environment name', () => {
    const script = generatePowerShellSourceScript('/any/path', 'dev-env');

    expect(script).toMatchLooseInlineSnapshot`
      Write-Host "Activated dotfiles environment: dev-env"
      Write-Host "  Directory: $env:DOTFILES_ENV_DIR"
      Write-Host "  Config: $env:DOTFILES_ENV_DIR\\dotfiles.config.ts"
    `;
  });
});
