import { defineTool } from "@alexgorbatchev/dotfiles";

export default defineTool((install) =>
  install("github-release", { repo: "BurntSushi/ripgrep" })
    .bin("rg")
    .zsh((shell) =>
      // Completions are generated by the installed binary itself.
      shell.completions({ cmd: "rg --generate complete-zsh", bin: "rg" }),
    ),
);
