import type { ProjectConfig } from "@dotfiles/config";
import { Architecture, type ISystemInfo, Platform, type ToolConfig } from "@dotfiles/core";
import type { IFileSystem } from "@dotfiles/file-system";
import { createMemFileSystem } from "@dotfiles/file-system";
import { TestLogger } from "@dotfiles/logger";
import type { TrackedFileSystem } from "@dotfiles/registry/file";
import type { ICompletionGenerator, IShellInitGenerator } from "@dotfiles/shell-init-generator";
import type { IShimGenerator } from "@dotfiles/shim-generator";
import type {
  CopyOperationResult,
  ICopyGenerator,
  ISymlinkGenerator,
  SymlinkOperationResult,
} from "@dotfiles/symlink-generator";
import {
  createMockFileRegistry,
  createMockProjectConfig,
  createTestDirectories,
  type ITestDirectories,
} from "@dotfiles/testing-helpers";
import { beforeEach, describe, expect, it, mock } from "bun:test";
import assert from "node:assert";
import path from "node:path";
import { GeneratorOrchestrator } from "../GeneratorOrchestrator";

function createMockTrackedFileSystem(fs: IFileSystem): TrackedFileSystem {
  const mockTrackedFs: TrackedFileSystem = {
    ...fs,
    withContext: mock(() => mockTrackedFs),
    setSuppressLogging: mock(() => {}),
  } as unknown as TrackedFileSystem;

  return mockTrackedFs;
}

describe("GeneratorOrchestrator - Stale Shim Cleanup", () => {
  let mockShimGenerator: IShimGenerator;
  let mockShellInitGenerator: IShellInitGenerator;
  let mockSymlinkGenerator: ISymlinkGenerator;
  let mockCopyGenerator: ICopyGenerator;
  let mockCompletionGenerator: ICompletionGenerator;
  let mockFileSystem: IFileSystem;
  let mockProjectConfig: ProjectConfig;
  let orchestrator: GeneratorOrchestrator;
  let logger: TestLogger;
  let testDirs: ITestDirectories;
  let systemInfo: ISystemInfo;
  let fileRegistry: ReturnType<typeof createMockFileRegistry>;

  beforeEach(async () => {
    mock.restore();
    logger = new TestLogger();

    mockShimGenerator = {
      generate: mock(async () => Promise.resolve([] as string[])),
      generateForTool: mock(async () => Promise.resolve([])),
    };
    mockShellInitGenerator = {
      generate: mock(async () =>
        Promise.resolve({
          files: new Map(),
          primaryPath: null,
        }),
      ),
    };
    mockSymlinkGenerator = {
      generate: mock(async () => Promise.resolve([] as SymlinkOperationResult[])),
      createBinarySymlink: mock(async () => {}),
    };
    mockCopyGenerator = {
      generate: mock(async () => Promise.resolve([] as CopyOperationResult[])),
    };
    mockCompletionGenerator = {
      generateCompletionFile: mock(async () =>
        Promise.resolve({
          content: "# completion",
          filename: "_tool",
          targetPath: "/path/_tool",
          generatedBy: "command" as const,
        }),
      ),
      generateAndWriteCompletionFile: mock(async () =>
        Promise.resolve({
          content: "# completion",
          filename: "_tool",
          targetPath: "/path/_tool",
          generatedBy: "command" as const,
        }),
      ),
    };

    const { fs } = await createMemFileSystem({});
    mockFileSystem = fs;

    testDirs = await createTestDirectories(logger, mockFileSystem, {
      testName: "generator-orchestrator-stale-shim",
    });

    systemInfo = {
      platform: Platform.Linux,
      arch: Architecture.X86_64,
      homeDir: testDirs.paths.homeDir,
      hostname: "test-host",
    };

    mockProjectConfig = await createMockProjectConfig({
      config: {
        paths: testDirs.paths,
      },
      filePath: path.join(testDirs.paths.dotfilesDir, "dotfiles.config.ts"),
      fileSystem: mockFileSystem,
      logger,
      systemInfo,
      env: {},
    });

    fileRegistry = createMockFileRegistry();

    orchestrator = new GeneratorOrchestrator(
      logger,
      mockShimGenerator,
      mockShellInitGenerator,
      mockSymlinkGenerator,
      mockCopyGenerator,
      mockCompletionGenerator,
      systemInfo,
      mockProjectConfig,
      fileRegistry,
      mockFileSystem,
      createMockTrackedFileSystem(mockFileSystem),
    );
  });

  it("should remove a shim when its .bin() declaration is removed from an active tool", async () => {
    const staleShimPath = path.join(testDirs.paths.targetDir, "foo");

    await mockFileSystem.ensureDir(path.dirname(staleShimPath));
    await mockFileSystem.writeFile(
      staleShimPath,
      "#!/usr/bin/env bash\n# Generated by Dotfiles Management Tool\nexec foo-real\n",
    );

    fileRegistry.setFileState({
      toolName: "myTool",
      fileType: "shim",
      filePath: staleShimPath,
      lastOperation: "chmod",
    });

    const toolConfig: ToolConfig = {
      name: "myTool",
      binaries: [],
      version: "1.0",
      installationMethod: "manual",
      installParams: {},
    };

    await orchestrator.generateAll({ myTool: toolConfig });

    expect(await mockFileSystem.exists(staleShimPath)).toBe(false);
  });

  it("should preserve a conflicting user-owned file at a previously tracked shim path", async () => {
    const conflictingFilePath = path.join(testDirs.paths.targetDir, "foo");

    await mockFileSystem.ensureDir(path.dirname(conflictingFilePath));
    await mockFileSystem.writeFile(conflictingFilePath, "#!/usr/bin/env bash\necho user-owned\n");

    fileRegistry.setFileState({
      toolName: "myTool",
      fileType: "shim",
      filePath: conflictingFilePath,
      lastOperation: "chmod",
    });

    const toolConfig: ToolConfig = {
      name: "myTool",
      binaries: [],
      version: "1.0",
      installationMethod: "manual",
      installParams: {},
    };

    await orchestrator.generateAll({ myTool: toolConfig });

    expect(await mockFileSystem.readFile(conflictingFilePath, "utf8")).toBe("#!/usr/bin/env bash\necho user-owned\n");
    expect(fileRegistry.recordOperation).not.toHaveBeenCalledWith(
      expect.objectContaining({
        toolName: "myTool",
        operationType: "rm",
        filePath: conflictingFilePath,
        fileType: "shim",
      }),
    );
  });

  it("should preserve a user-owned symlink at a previously tracked shim path", async () => {
    const conflictingSymlinkPath = path.join(testDirs.paths.targetDir, "foo");
    const userOwnedTargetPath = path.join(testDirs.paths.dotfilesDir, "user-foo");

    await mockFileSystem.ensureDir(path.dirname(conflictingSymlinkPath));
    await mockFileSystem.writeFile(userOwnedTargetPath, "user-owned target\n");
    await mockFileSystem.symlink(userOwnedTargetPath, conflictingSymlinkPath);

    fileRegistry.setFileState({
      toolName: "myTool",
      fileType: "shim",
      filePath: conflictingSymlinkPath,
      lastOperation: "chmod",
    });

    const toolConfig: ToolConfig = {
      name: "myTool",
      binaries: [],
      version: "1.0",
      installationMethod: "manual",
      installParams: {},
    };

    await orchestrator.generateAll({ myTool: toolConfig });

    const conflictingShimStats = await mockFileSystem.lstat(conflictingSymlinkPath);
    expect(conflictingShimStats.isSymbolicLink()).toBe(true);
    expect(await mockFileSystem.readlink(conflictingSymlinkPath)).toBe(userOwnedTargetPath);
    expect(fileRegistry.recordOperation).not.toHaveBeenCalledWith(
      expect.objectContaining({
        toolName: "myTool",
        operationType: "rm",
        filePath: conflictingSymlinkPath,
        fileType: "shim",
      }),
    );
  });

  it("should not record shim removal when deleting the stale shim fails", async () => {
    const staleShimPath = path.join(testDirs.paths.targetDir, "foo");

    await mockFileSystem.ensureDir(path.dirname(staleShimPath));
    await mockFileSystem.writeFile(
      staleShimPath,
      "#!/usr/bin/env bash\n# Generated by Dotfiles Management Tool\nexec foo-real\n",
    );

    fileRegistry.setFileState({
      toolName: "myTool",
      fileType: "shim",
      filePath: staleShimPath,
      lastOperation: "chmod",
    });

    const originalRm = mockFileSystem.rm.bind(mockFileSystem);
    mockFileSystem.rm = mock(async (filePath, options) => {
      assert.notStrictEqual(filePath, staleShimPath, "permission denied");
      await originalRm(filePath, options);
    });

    const toolConfig: ToolConfig = {
      name: "myTool",
      binaries: [],
      version: "1.0",
      installationMethod: "manual",
      installParams: {},
    };

    await orchestrator.generateAll({ myTool: toolConfig });

    expect(await mockFileSystem.exists(staleShimPath)).toBe(true);
    expect(fileRegistry.recordOperation).not.toHaveBeenCalledWith(
      expect.objectContaining({
        toolName: "myTool",
        operationType: "rm",
        filePath: staleShimPath,
        fileType: "shim",
      }),
    );
  });

  it("should not remove shims that are still declared", async () => {
    const activeShimPath = path.join(testDirs.paths.targetDir, "foo");

    await mockFileSystem.ensureDir(path.dirname(activeShimPath));
    await mockFileSystem.writeFile(activeShimPath, "active shim content");

    fileRegistry.setFileState({
      toolName: "myTool",
      fileType: "shim",
      filePath: activeShimPath,
      lastOperation: "chmod",
    });

    (mockShimGenerator.generate as ReturnType<typeof mock>).mockResolvedValue([activeShimPath]);

    const toolConfig: ToolConfig = {
      name: "myTool",
      binaries: ["foo"],
      version: "1.0",
      installationMethod: "manual",
      installParams: {
        binaryPath: "./foo-real",
      },
    };

    await orchestrator.generateAll({ myTool: toolConfig });

    expect(await mockFileSystem.exists(activeShimPath)).toBe(true);
  });
});
