import path from 'node:path';
import { type TsLogger } from '@modules/logger';
import type { IFileSystem } from '@modules/file-system';
import type { YamlConfig } from '@modules/config';
import type { ToolConfig } from '@types';
import type { GenerateShimsOptions, IShimGenerator } from './IShimGenerator';
import { TrackedFileSystem } from '@modules/file-registry';
import { getCliBinPath } from '../../utils';
import { DebugTemplates } from '@modules/shared/ErrorTemplates';


/**
 * Generates executable shims for tools.
 *
 * The core logic of the generated Bash shims is to first check for the
 * existence of the target binary. If it's not found, the shim executes the main
 * generator CLI's `install` command to perform an on-demand installation.
 * After a successful installation, it proceeds to execute the actual tool.
 * This ensures that tools are available when needed without requiring
 * them to be installed beforehand.
 */
export class ShimGenerator implements IShimGenerator {
  private readonly fs: IFileSystem;
  private readonly config: YamlConfig;
  private readonly logger: TsLogger;

  constructor(parentLogger: TsLogger, fileSystem: IFileSystem, config: YamlConfig) {
    const logger = parentLogger.getSubLogger({ name: 'ShimGenerator' });
    this.logger = logger;
    logger.debug(DebugTemplates.shim.constructorDebug(), fileSystem, config);
    this.fs = fileSystem;
    this.config = config;
  }

  async generate(
    toolConfigs: Record<string, ToolConfig>,
    options?: GenerateShimsOptions
  ): Promise<string[]> {
    this.logger.debug(DebugTemplates.shim.generateDebug(), toolConfigs, options);
    const generatedShimPaths: string[] = [];

    for (const toolName in toolConfigs) {
      if (Object.prototype.hasOwnProperty.call(toolConfigs, toolName)) {
        const toolConfig = toolConfigs[toolName];
        if (toolConfig) {
          const shimPaths = await this.generateForTool(toolName, toolConfig, options);
          generatedShimPaths.push(...shimPaths);
        } else {
          this.logger.debug(DebugTemplates.shim.toolConfigUndefined(), toolName);
        }
      }
    }
    return generatedShimPaths;
  }

  async generateForTool(
    toolName: string,
    toolConfig: ToolConfig,
    options?: GenerateShimsOptions
  ): Promise<string[]> {
    // Create a tool-specific TrackedFileSystem if we have a TrackedFileSystem instance
    const toolFs = this.fs instanceof TrackedFileSystem 
      ? this.fs.withToolName(toolName)
      : this.fs;

    this.logger.debug(DebugTemplates.shim.generateForToolDebug(), toolName, toolConfig, options, toolFs.constructor.name);

    // dryRun is removed; IFileSystem handles behavior
    const overwrite = options?.overwrite ?? false;
    const shimDir = this.config.paths.targetDir;
    const shimFilePath = path.join(shimDir, toolName);

    this.logger.debug(DebugTemplates.shim.shimFilePath(), shimFilePath);

    if (!overwrite && (await toolFs.exists(shimFilePath))) {
      this.logger.debug(DebugTemplates.shim.shimExists(), shimFilePath);
      return [];
    }

    // Ensure toolConfig.binaries is defined and is an array
    const primaryBinaryName =
      toolConfig.binaries && Array.isArray(toolConfig.binaries) && toolConfig.binaries.length > 0
        ? toolConfig.binaries[0]! // Added non-null assertion
        : toolName; // Fallback to toolName if binaries are not well-defined

    const toolBinPath = path.join(
      this.config.paths.binariesDir,
      toolConfig.name, // Use toolConfig.name for the tool-specific subdirectory
      primaryBinaryName
    );

    this.logger.debug(DebugTemplates.shim.toolBinPath(), toolBinPath);

    const shimContent = `#!/usr/bin/env bash
# Shim for ${toolName}
# Generated by Dotfiles Management Tool

set -euo pipefail

TOOL_NAME="${toolName}"
TOOL_EXECUTABLE="${toolBinPath}"
GENERATOR_CLI_EXECUTABLE="${getCliBinPath()}"
CONFIG_PATH="${this.config.userConfigPath}"

if [ -x "$TOOL_EXECUTABLE" ]; then
  exec "$TOOL_EXECUTABLE" "$@"
  exit $?
else
  $GENERATOR_CLI_EXECUTABLE --quiet --config "$CONFIG_PATH" install "$TOOL_NAME"
  # Re-check after installation attempt
  if [ -x "$TOOL_EXECUTABLE" ]; then
    exec "$TOOL_EXECUTABLE" "$@"
    exit $?
  else
    echo "Failed to install '${toolName}' via '$GENERATOR_CLI_EXECUTABLE' or it's still not found at '$TOOL_EXECUTABLE'. Please check the installation."
    exit 1
  fi
fi
`;
    this.logger.debug(DebugTemplates.shim.shimContent(), shimContent);

    // File system operations' behavior (dry or real) is determined by the injected IFileSystem.
    await toolFs.ensureDir(path.dirname(shimFilePath));
    await toolFs.writeFile(shimFilePath, shimContent);
    await toolFs.chmod(shimFilePath, 0o755); // rwxr-xr-x
    this.logger.debug(DebugTemplates.shim.shimSuccess(), toolName, shimFilePath, toolFs.constructor.name);
    return [shimFilePath];
  }
}
