import path from 'node:path';
import { type TsLogger } from '@modules/logger';
import type { IFileSystem } from '@modules/file-system';
import type { YamlConfig } from '@modules/config';
import type { ToolConfig } from '@types';
import type { GenerateShimsOptions, IShimGenerator } from './IShimGenerator';
import { TrackedFileSystem } from '@modules/file-registry';
import { dedentString, getCliBinPath } from '../../utils';
import { DebugTemplates, ErrorTemplates } from '@modules/shared/ErrorTemplates';


/**
 * Generates executable shims for tools.
 *
 * The core logic of the generated Bash shims is to first check for the
 * existence of the target binary. If it's not found, the shim executes the main
 * generator CLI's `install` command to perform an on-demand installation.
 * After a successful installation, it proceeds to execute the actual tool.
 * This ensures that tools are available when needed without requiring
 * them to be installed beforehand.
 */
export class ShimGenerator implements IShimGenerator {
  private readonly fs: IFileSystem;
  private readonly config: YamlConfig;
  private readonly logger: TsLogger;

  constructor(parentLogger: TsLogger, fileSystem: IFileSystem, config: YamlConfig) {
    const logger = parentLogger.getSubLogger({ name: 'ShimGenerator' });
    this.logger = logger;
    logger.debug(DebugTemplates.shim.constructorDebug(), fileSystem, config);
    this.fs = fileSystem;
    this.config = config;
  }

  async generate(
    toolConfigs: Record<string, ToolConfig>,
    options?: GenerateShimsOptions
  ): Promise<string[]> {
    this.logger.debug(DebugTemplates.shim.generateDebug(), toolConfigs, options);
    const generatedShimPaths: string[] = [];

    for (const toolName in toolConfigs) {
      if (Object.prototype.hasOwnProperty.call(toolConfigs, toolName)) {
        const toolConfig = toolConfigs[toolName];
        if (toolConfig) {
          const shimPaths = await this.generateForTool(toolName, toolConfig, options);
          generatedShimPaths.push(...shimPaths);
        } else {
          this.logger.debug(DebugTemplates.shim.toolConfigUndefined(), toolName);
        }
      }
    }
    return generatedShimPaths;
  }

  async generateForTool(
    toolName: string,
    toolConfig: ToolConfig,
    options?: GenerateShimsOptions
  ): Promise<string[]> {
    // Create a tool-specific TrackedFileSystem if we have a TrackedFileSystem instance
    const toolFs = this.fs instanceof TrackedFileSystem 
      ? this.fs.withToolName(toolName)
      : this.fs;

    this.logger.debug(DebugTemplates.shim.generateForToolDebug(), toolName, toolConfig, options, toolFs.constructor.name);

    // dryRun is removed; IFileSystem handles behavior
    const overwrite = options?.overwrite ?? false;
    const shimDir = this.config.paths.targetDir;
    const shimFilePath = path.join(shimDir, toolName);

    this.logger.debug(DebugTemplates.shim.shimFilePath(), shimFilePath);

    if (await toolFs.exists(shimFilePath)) {
      // Check if the existing file is one of our shims
      const isOurShim = await this.isGeneratedShim(toolFs, shimFilePath);
      
      if (!isOurShim) {
        // Not our shim - log error and skip
        this.logger.error(ErrorTemplates.tool.shimConflict(toolName, shimFilePath));
        return [];
      }
      
      if (!overwrite) {
        // It's our shim but overwrite is false - skip silently
        this.logger.debug(DebugTemplates.shim.shimExists(), shimFilePath);
        return [];
      }
      
      // It's our shim and overwrite is true - continue to overwrite
    }

    // Ensure toolConfig.binaries is defined and is an array
    const primaryBinaryName =
      toolConfig.binaries && Array.isArray(toolConfig.binaries) && toolConfig.binaries.length > 0
        ? toolConfig.binaries[0]! // Added non-null assertion
        : toolName; // Fallback to toolName if binaries are not well-defined

    // Binary location after installation (installer now moves binary to direct location)
    const toolDir = path.join(this.config.paths.binariesDir, toolConfig.name);
    const binaryPath = path.join(toolDir, primaryBinaryName);

    this.logger.debug(DebugTemplates.shim.toolBinPath(), binaryPath);

    const shimContent = dedentString(`
      #!/usr/bin/env bash
      # Shim for ${toolName}
      # Generated by Dotfiles Management Tool

      set -euo pipefail

      TOOL_NAME="${toolName}"
      TOOL_EXECUTABLE="${binaryPath}"
      GENERATOR_CLI_EXECUTABLE="${getCliBinPath()}"
      CONFIG_PATH="${this.config.userConfigPath}"

      # Check if the first argument is @update
      if [ $# -gt 0 ] && [ "$1" = "@update" ]; then
        echo "Updating $TOOL_NAME to latest version..."
        # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
        eval "$GENERATOR_CLI_EXECUTABLE" update --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"'
        exit $?
      fi

      # Check if the tool is already installed and execute it
      if [ -x "$TOOL_EXECUTABLE" ]; then
        exec "$TOOL_EXECUTABLE" "$@"
        exit $?
      else
        # Tool not found, try to install it
        # Capture both stdout and stderr from the install command
        # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
        install_output=$(eval "$GENERATOR_CLI_EXECUTABLE" install --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"' 2>&1)
        install_exit_code=$?
        
        if [ $install_exit_code -eq 0 ]; then
          # Installation successful, try to execute the tool
          if [ -x "$TOOL_EXECUTABLE" ]; then
            exec "$TOOL_EXECUTABLE" "$@"
            exit $?
          else
            echo "Installation completed but binary not found at: $TOOL_EXECUTABLE"
            exit 1
          fi
        else
          # Installation failed, show the actual error message
          echo "$install_output"
          exit $install_exit_code
        fi
      fi
    `);
    this.logger.debug(DebugTemplates.shim.shimContent(), shimContent);

    // File system operations' behavior (dry or real) is determined by the injected IFileSystem.
    await toolFs.ensureDir(path.dirname(shimFilePath));
    await toolFs.writeFile(shimFilePath, shimContent);
    
    // Only chmod if file doesn't already have the correct permissions
    const desiredMode = 0o755; // rwxr-xr-x
    try {
      const stats = await toolFs.stat(shimFilePath);
      const currentMode = stats.mode & 0o777; // Extract permission bits
      if (currentMode !== desiredMode) {
        await toolFs.chmod(shimFilePath, desiredMode);
      }
    } catch (error) {
      // If we can't check permissions, try to set them anyway
      await toolFs.chmod(shimFilePath, desiredMode);
    }
    this.logger.debug(DebugTemplates.shim.shimSuccess(), toolName, shimFilePath, toolFs.constructor.name);
    return [shimFilePath];
  }

  /**
   * Checks if a file is a shim generated by our dotfiles management tool.
   * @param fs The filesystem interface to use
   * @param filePath The path to the file to check
   * @returns true if the file is one of our generated shims, false otherwise
   */
  private async isGeneratedShim(fs: IFileSystem, filePath: string): Promise<boolean> {
    try {
      const content = await fs.readFile(filePath, 'utf8');
      // Check for our distinctive header comment
      return content.includes('# Generated by Dotfiles Management Tool');
    } catch (error) {
      // If we can't read the file, assume it's not our shim
      return false;
    }
  }
}
