package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateTypes(t *testing.T) {
	tmpDir := t.TempDir()
	outputPath := filepath.Join(tmpDir, "types.gen.ts")

	err := generateTypes(outputPath)
	if err != nil {
		t.Fatalf("generateTypes failed: %v", err)
	}

	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	strContent := string(content)
	expectedTypes := []string{
		"interface ToolConfig",
		"interface ProjectConfig",
		"interface BinaryConfig",
		"interface SymlinkConfig",
	}

	for _, expected := range expectedTypes {
		if !strings.Contains(strContent, expected) {
			t.Errorf("generated types missing expected declaration %q", expected)
		}
	}
}

func TestRunMainDefaultDoesNotTouchDist(t *testing.T) {
	tmpDir := t.TempDir()
	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get current working dir: %v", err)
	}
	defer func() { _ = os.Chdir(originalWd) }()

	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("failed to chdir to temp dir: %v", err)
	}

	distDir := filepath.Join(tmpDir, ".dist")
	if err := os.MkdirAll(distDir, 0755); err != nil {
		t.Fatalf("failed to create .dist dir: %v", err)
	}
	distIndexPath := filepath.Join(distDir, "index.d.ts")
	sentinel := "// original dsl definitions"
	if err := os.WriteFile(distIndexPath, []byte(sentinel), 0644); err != nil {
		t.Fatalf("failed to write sentinel index.d.ts: %v", err)
	}

	// Create packages/dashboard/src/shared so runMain default output succeeds
	dashDir := filepath.Join(tmpDir, "packages", "dashboard", "src", "shared")
	if err := os.MkdirAll(dashDir, 0755); err != nil {
		t.Fatalf("failed to create dashboard dir: %v", err)
	}

	if err := runMain([]string{}); err != nil {
		t.Fatalf("runMain([]) failed: %v", err)
	}

	content, err := os.ReadFile(distIndexPath)
	if err != nil {
		t.Fatalf("failed to read .dist/index.d.ts: %v", err)
	}
	if string(content) != sentinel {
		t.Fatalf(".dist/index.d.ts was modified by typegen runMain([]): got %q, want %q", string(content), sentinel)
	}
}

func TestMainFunc(t *testing.T) {
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, "main_out.d.ts")

	oldArgs := os.Args
	defer func() { os.Args = oldArgs }()

	os.Args = []string{"typegen", outPath}
	main()

	if _, err := os.Stat(outPath); err != nil {
		t.Fatalf("expected output file to be generated by main(): %v", err)
	}

	if err := runMain([]string{}); err != nil {
		t.Fatalf("expected runMain() default to succeed: %v", err)
	}
}

func TestErrors(t *testing.T) {
	tmpDir := t.TempDir()

	if err := runMain([]string{"-invalid-flag-xyz"}); err == nil {
		t.Fatal("expected error on invalid flag")
	}

	if err := runMain([]string{"-out", "\x00invalid"}); err == nil {
		t.Fatal("expected error on -out invalid path in runMain")
	}

	invalidPath := "\x00invalid"
	if err := generateTypes(invalidPath); err == nil {
		t.Fatal("expected error on invalid output path in generateTypes")
	}

	// Create a file and try to use it as a directory to trigger MkdirAll error
	filePath := filepath.Join(tmpDir, "file_as_dir")
	if err := os.WriteFile(filePath, []byte("not a dir"), 0644); err != nil {
		t.Fatalf("failed to create temp file: %v", err)
	}
	mkdirErrPath := filepath.Join(filePath, "sub", "out.d.ts")
	if err := generateTypes(mkdirErrPath); err == nil {
		t.Fatal("expected MkdirAll error in generateTypes")
	}
}
