package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateTypes(t *testing.T) {
	tmpDir := t.TempDir()
	outputPath := filepath.Join(tmpDir, "types.gen.ts")

	err := generateTypes(outputPath)
	if err != nil {
		t.Fatalf("generateTypes failed: %v", err)
	}

	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	strContent := string(content)
	expectedTypes := []string{
		"interface ToolConfig",
		"interface ProjectConfig",
		"interface BinaryConfig",
		"interface SymlinkConfig",
	}

	for _, expected := range expectedTypes {
		if !strings.Contains(strContent, expected) {
			t.Errorf("generated types missing expected declaration %q", expected)
		}
	}
}

func TestRunMainDefaultDoesNotTouchDist(t *testing.T) {
	tmpDir := t.TempDir()
	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get current working dir: %v", err)
	}
	defer func() { _ = os.Chdir(originalWd) }()

	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("failed to chdir to temp dir: %v", err)
	}

	distDir := filepath.Join(tmpDir, ".dist")
	if err := os.MkdirAll(distDir, 0755); err != nil {
		t.Fatalf("failed to create .dist dir: %v", err)
	}
	distIndexPath := filepath.Join(distDir, "index.d.ts")
	sentinel := "// original dsl definitions"
	if err := os.WriteFile(distIndexPath, []byte(sentinel), 0644); err != nil {
		t.Fatalf("failed to write sentinel index.d.ts: %v", err)
	}

	// Create packages/dashboard/src/shared so runMain default output succeeds
	dashDir := filepath.Join(tmpDir, "packages", "dashboard", "src", "shared")
	if err := os.MkdirAll(dashDir, 0755); err != nil {
		t.Fatalf("failed to create dashboard dir: %v", err)
	}

	if err := runMain([]string{}); err != nil {
		t.Fatalf("runMain([]) failed: %v", err)
	}

	content, err := os.ReadFile(distIndexPath)
	if err != nil {
		t.Fatalf("failed to read .dist/index.d.ts: %v", err)
	}
	if string(content) != sentinel {
		t.Fatalf(".dist/index.d.ts was modified by typegen runMain([]): got %q, want %q", string(content), sentinel)
	}
}

func TestRunMainDefaultResolvesRepoRoot(t *testing.T) {
	mockRepoRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(mockRepoRoot, "go.mod"), []byte("module mockrepo\n"), 0644); err != nil {
		t.Fatalf("failed to create mock go.mod: %v", err)
	}

	mockDashboardDir := filepath.Join(mockRepoRoot, "packages", "dashboard", "src", "shared")
	if err := os.MkdirAll(mockDashboardDir, 0755); err != nil {
		t.Fatalf("failed to create mock dashboard dir: %v", err)
	}

	mockSubDir := filepath.Join(mockRepoRoot, "scripts", "typegen")
	if err := os.MkdirAll(mockSubDir, 0755); err != nil {
		t.Fatalf("failed to create mock scripts/typegen dir: %v", err)
	}

	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get current working dir: %v", err)
	}
	defer func() { _ = os.Chdir(originalWd) }()

	if err := os.Chdir(mockSubDir); err != nil {
		t.Fatalf("failed to chdir to mock scripts/typegen: %v", err)
	}

	if err := runMain([]string{}); err != nil {
		t.Fatalf("runMain([]) failed: %v", err)
	}

	expectedPath := filepath.Join(mockRepoRoot, "packages", "dashboard", "src", "shared", "types.gen.ts")
	if _, err := os.Stat(expectedPath); err != nil {
		t.Fatalf("expected types.gen.ts at %s, but stat failed: %v", expectedPath, err)
	}

	strayPath := filepath.Join(mockSubDir, "packages")
	if _, err := os.Stat(strayPath); err == nil {
		t.Fatalf("untracked directory created at %s", strayPath)
	}
}

func TestMainFunc(t *testing.T) {
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, "main_out.d.ts")

	oldArgs := os.Args
	defer func() { os.Args = oldArgs }()

	os.Args = []string{"typegen", outPath}
	main()

	if _, err := os.Stat(outPath); err != nil {
		t.Fatalf("expected output file to be generated by main(): %v", err)
	}

	// When run in a directory without go.mod, runMain falls back to resolving
	// relative to the working directory.
	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get current working dir: %v", err)
	}
	defer func() { _ = os.Chdir(originalWd) }()
	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("failed to chdir to temp dir: %v", err)
	}

	if err := runMain([]string{}); err != nil {
		t.Fatalf("expected runMain() default to succeed: %v", err)
	}
	defaultPath := filepath.Join(tmpDir, "packages", "dashboard", "src", "shared", "types.gen.ts")
	if _, err := os.Stat(defaultPath); err != nil {
		t.Fatalf("expected runMain() default to write %s: %v", defaultPath, err)
	}
}

func TestGetRepoRoot(t *testing.T) {
	// In the actual repository, getRepoRoot finds the root containing go.mod
	root, err := getRepoRoot()
	if err != nil {
		t.Fatalf("getRepoRoot() failed: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		t.Fatalf("expected go.mod in repo root %s: %v", root, err)
	}

	// In a simulated repository hierarchy
	mockRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(mockRoot, "go.mod"), []byte("module test\n"), 0644); err != nil {
		t.Fatalf("failed to create go.mod: %v", err)
	}
	mockSub := filepath.Join(mockRoot, "scripts", "typegen")
	if err := os.MkdirAll(mockSub, 0755); err != nil {
		t.Fatalf("failed to create mock subdir: %v", err)
	}

	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get current working dir: %v", err)
	}
	defer func() { _ = os.Chdir(originalWd) }()

	if err := os.Chdir(mockSub); err != nil {
		t.Fatalf("failed to chdir to mock subdir: %v", err)
	}

	resolved, err := getRepoRoot()
	if err != nil {
		t.Fatalf("getRepoRoot() failed in mock repo: %v", err)
	}
	if resolved != mockRoot {
		t.Fatalf("expected mock repo root %q, got %q", mockRoot, resolved)
	}

	// In a standalone directory without go.mod in any ancestor, it falls back to cwd
	isolatedDir := t.TempDir()
	if err := os.Chdir(isolatedDir); err != nil {
		t.Fatalf("failed to chdir to isolated dir: %v", err)
	}
	fallbackRoot, err := getRepoRoot()
	if err != nil {
		t.Fatalf("getRepoRoot() fallback failed: %v", err)
	}
	realIsolated, err := filepath.EvalSymlinks(isolatedDir)
	if err == nil {
		realFallback, _ := filepath.EvalSymlinks(fallbackRoot)
		if realFallback != realIsolated {
			t.Fatalf("expected fallback to %q, got %q", realIsolated, realFallback)
		}
	} else if fallbackRoot != isolatedDir {
		t.Fatalf("expected fallback to %q, got %q", isolatedDir, fallbackRoot)
	}
}

func TestErrors(t *testing.T) {
	tmpDir := t.TempDir()

	if err := runMain([]string{"-invalid-flag-xyz"}); err == nil {
		t.Fatal("expected error on invalid flag")
	}

	if err := runMain([]string{"-out", "\x00invalid"}); err == nil {
		t.Fatal("expected error on -out invalid path in runMain")
	}

	invalidPath := "\x00invalid"
	if err := generateTypes(invalidPath); err == nil {
		t.Fatal("expected error on invalid output path in generateTypes")
	}

	// Create a file and try to use it as a directory to trigger MkdirAll error
	filePath := filepath.Join(tmpDir, "file_as_dir")
	if err := os.WriteFile(filePath, []byte("not a dir"), 0644); err != nil {
		t.Fatalf("failed to create temp file: %v", err)
	}
	mkdirErrPath := filepath.Join(filePath, "sub", "out.d.ts")
	if err := generateTypes(mkdirErrPath); err == nil {
		t.Fatal("expected MkdirAll error in generateTypes")
	}
}
