package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateTypes(t *testing.T) {
	tmpDir := t.TempDir()
	outputPath := filepath.Join(tmpDir, "types.gen.ts")

	err := generateTypes(outputPath)
	if err != nil {
		t.Fatalf("generateTypes failed: %v", err)
	}

	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	strContent := string(content)
	expectedTypes := []string{
		"interface ToolConfig",
		"interface ProjectConfig",
		"interface PlatformConfigEntry",
		"interface BinaryConfig",
		"interface SymlinkConfig",
	}

	for _, expected := range expectedTypes {
		if !strings.Contains(strContent, expected) {
			t.Errorf("generated types missing expected declaration %q", expected)
		}
	}
}

func TestTypegenEmitIndexDts(t *testing.T) {
	tmpDir := t.TempDir()
	distDir := filepath.Join(tmpDir, ".dist")
	if err := os.MkdirAll(distDir, 0755); err != nil {
		t.Fatalf("failed to create .dist dir: %v", err)
	}

	distIndexPath := filepath.Join(distDir, "index.d.ts")
	if err := generateTypes(distIndexPath); err != nil {
		t.Fatalf("generateTypes to .dist/index.d.ts failed: %v", err)
	}

	content, err := os.ReadFile(distIndexPath)
	if err != nil {
		t.Fatalf("failed to read .dist/index.d.ts: %v", err)
	}

	if len(content) == 0 {
		t.Errorf("expected .dist/index.d.ts to be non-empty")
	}

	strContent := string(content)
	if !strings.Contains(strContent, "interface ToolConfig") {
		t.Errorf("expected .dist/index.d.ts to contain interface ToolConfig")
	}
}

func TestMainFunc(t *testing.T) {
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, "main_out.d.ts")

	oldArgs := os.Args
	defer func() { os.Args = oldArgs }()

	os.Args = []string{"typegen", outPath}
	main()

	if _, err := os.Stat(outPath); err != nil {
		t.Fatalf("expected output file to be generated by main(): %v", err)
	}

	if err := runMain([]string{}); err != nil {
		t.Fatalf("expected runMain() default to succeed: %v", err)
	}
}

func TestErrors(t *testing.T) {
	tmpDir := t.TempDir()

	if err := runMain([]string{"-invalid-flag-xyz"}); err == nil {
		t.Fatal("expected error on invalid flag")
	}

	if err := runMain([]string{"-out", "\x00invalid"}); err == nil {
		t.Fatal("expected error on -out invalid path in runMain")
	}

	invalidPath := "\x00invalid"
	if err := generateTypes(invalidPath); err == nil {
		t.Fatal("expected error on invalid output path in generateTypes")
	}

	// Create a file and try to use it as a directory to trigger MkdirAll error
	filePath := filepath.Join(tmpDir, "file_as_dir")
	if err := os.WriteFile(filePath, []byte("not a dir"), 0644); err != nil {
		t.Fatalf("failed to create temp file: %v", err)
	}
	mkdirErrPath := filepath.Join(filePath, "sub", "out.d.ts")
	if err := generateTypes(mkdirErrPath); err == nil {
		t.Fatal("expected MkdirAll error in generateTypes")
	}
}
