
import {
  createFile,
  createMockGitHubServer,
  createMockYamlConfig,
  createTestDirectories,
  createToolConfig,
  executeCliCommand,
  TestLogger,
  type MockGitHubServerResult,
  type TestDirectories,
} from '@testing-helpers';
import { afterAll, beforeAll, describe, expect, it } from 'bun:test';
import * as path from 'node:path';
import { $ } from 'zx';
import { NodeFileSystem } from '@modules/file-system';

import '@testing-helpers/matchers'; 

describe('E2E: bun run cli generate', () => {
  describe('generating shims, shell init, and symlinks', () => {
    let testDirs: TestDirectories;
    let fs: NodeFileSystem;

    // Paths for generated artifacts
    let fzfShimPath: string;
    let lazygitShimPath: string;
    let zshInitFilePath: string;
    let lazygitSourceConfigPath: string;
    let cliExitCode: number | null;
    let cliStderr: string;

    beforeAll(async () => {
      fs = new NodeFileSystem();
      const logger = new TestLogger();
      testDirs = await createTestDirectories(logger, fs,{
        testName: 'cli-generate-e2e',
      });

      // Define paths for generated artifacts
      fzfShimPath = path.join(testDirs.paths.targetDir, 'fzf');
      lazygitShimPath = path.join(testDirs.paths.targetDir, 'lazygit');
      zshInitFilePath = path.join(testDirs.paths.shellScriptsDir, 'init.zsh');
      lazygitSourceConfigPath = path.join(
        testDirs.paths.toolConfigsDir,
        '02-configs',
        'lazygit',
        'config.yml'
      );

      // Create mock lazygit config file at the location expected by the tool config
      await createFile(fs, lazygitSourceConfigPath, '# Sample lazygit config for E2E test');

      await createMockYamlConfig({
        config: {
          paths: testDirs.paths,
        },
        filePath: path.join(testDirs.paths.dotfilesDir, 'config.yaml'),
        fileSystem: fs,
        logger,
        systemInfo: {
          platform: 'linux',
          arch: 'x64',
          homeDir: testDirs.paths.homeDir,
        },
        env: {},
      });

      // Create tool configs
      createToolConfig({
        toolConfigsDir: testDirs.paths.toolConfigsDir,
        name: 'fzf',
        fixturePath: path.resolve(__dirname, 'fixtures', 'fzf.tool.ts'),
      });
      createToolConfig({
        toolConfigsDir: testDirs.paths.toolConfigsDir,
        name: 'lazygit',
        fixturePath: path.resolve(__dirname, 'fixtures', 'lazygit.tool.ts'),
      });

      // Execute CLI command
      const result = executeCliCommand({
        command: ['generate'],
        cwd: testDirs.paths.dotfilesDir,
        homeDir: testDirs.paths.homeDir,
      });

      cliExitCode = result.exitCode;
      cliStderr = result.stderr;
    });

    it('should execute the CLI successfully', () => {
      expect(cliStderr).toEqual('');
      expect(cliExitCode).toEqual(0);
    });

    it('creates manifest file', async () => {
      expect(await fs.exists(testDirs.paths.manifestPath)).toBe(true);
    });

    it('should generate the correct shim files for fzf and lazygit', async () => {
      expect(await fs.exists(fzfShimPath)).toBe(true);
      expect(await fs.exists(lazygitShimPath)).toBe(true);

      for (const shimP of [fzfShimPath, lazygitShimPath]) {
        const stat = await fs.stat(shimP);
        expect(stat.mode & 0o100).toBeGreaterThan(0); // Check executable
      }

      const fzfContent = await fs.readFile(fzfShimPath);
      expect(fzfContent).toMatchLooseInlineSnapshot`
        #!/usr/bin/env bash
        # Shim for fzf
        # Generated by Dotfiles Management Tool

        set -euo pipefail

        TOOL_NAME="fzf"
        TOOL_EXECUTABLE="${path.join(testDirs.paths.binariesDir, 'fzf', 'fzf')}"
        GENERATOR_CLI_EXECUTABLE="${expect.anything}"
        CONFIG_PATH="${path.join(testDirs.paths.dotfilesDir, 'config.yaml')}"

        if [ -x "$TOOL_EXECUTABLE" ]; then
          exec "$TOOL_EXECUTABLE" "$@"
          exit $?
        else
          # Capture both stdout and stderr from the install command
          # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
          install_output=$(eval "$GENERATOR_CLI_EXECUTABLE" install --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"' 2>&1)
          install_exit_code=$?
          
          if [ $install_exit_code -eq 0 ]; then
            # Installation successful, check if binary now exists
            if [ -x "$TOOL_EXECUTABLE" ]; then
              exec "$TOOL_EXECUTABLE" "$@"
              exit $?
            else
              echo "Installation completed but binary not found at '$TOOL_EXECUTABLE'."
              exit 1
            fi
          else
            # Installation failed, show the actual error message
            echo "$install_output"
            exit $install_exit_code
          fi
        fi
      `;

      const lazygitContent = await fs.readFile(lazygitShimPath);
      expect(lazygitContent).toMatchLooseInlineSnapshot`
        #!/usr/bin/env bash
        # Shim for lazygit
        # Generated by Dotfiles Management Tool

        set -euo pipefail

        TOOL_NAME="lazygit"
        TOOL_EXECUTABLE="${path.join(testDirs.paths.binariesDir, 'lazygit', 'lazygit')}"
        GENERATOR_CLI_EXECUTABLE="${expect.anything}"
        CONFIG_PATH="${path.join(testDirs.paths.dotfilesDir, 'config.yaml')}"

        if [ -x "$TOOL_EXECUTABLE" ]; then
          exec "$TOOL_EXECUTABLE" "$@"
          exit $?
        else
          # Capture both stdout and stderr from the install command
          # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
          install_output=$(eval "$GENERATOR_CLI_EXECUTABLE" install --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"' 2>&1)
          install_exit_code=$?
          
          if [ $install_exit_code -eq 0 ]; then
            # Installation successful, check if binary now exists
            if [ -x "$TOOL_EXECUTABLE" ]; then
              exec "$TOOL_EXECUTABLE" "$@"
              exit $?
            else
              echo "Installation completed but binary not found at '$TOOL_EXECUTABLE'."
              exit 1
            fi
          else
            # Installation failed, show the actual error message
            echo "$install_output"
            exit $install_exit_code
          fi
        fi
      `;
    });

    it('should generate the correct shell initialization file content', async () => {
      expect(await fs.exists(zshInitFilePath)).toBe(true);
      const content = await fs.readFile(zshInitFilePath);
      expect(content).toContain('# --- fzf ---');
      expect(content).toContain('export FZF_DEFAULT_OPTS=');
      expect(content).toContain('# --- lazygit ---');
      expect(content).toContain('alias g="lazygit"');
    });

    describe('manifest file', () => {
      let parsedManifest: any;

      beforeAll(async () => {
        parsedManifest = JSON.parse(await fs.readFile(testDirs.paths.manifestPath));
        expect(parsedManifest).not.toBeNull();
      });

      it('should verify symlinks in the manifest', async () => {
        expect(parsedManifest.symlinks.length).toBeGreaterThan(0);
        expect(parsedManifest.symlinks[0].sourcePath).toBe(lazygitSourceConfigPath);
      });

      it('should generate a manifest file with correct entries', async () => {
        expect(parsedManifest.shims).toContain(fzfShimPath);
        expect(parsedManifest.shims).toContain(lazygitShimPath);
        expect(parsedManifest.symlinks[0].sourcePath).toBe(lazygitSourceConfigPath);
        expect(parsedManifest.symlinks[0].targetPath).toContain('lazygit/config.yml');
      });

      it('should verify the symlink', async () => {
        const stat = await fs.lstat(parsedManifest.symlinks[0].targetPath);
        expect(stat.isSymbolicLink()).toBeTrue();

        const symlinkTarget = await fs.readlink(parsedManifest.symlinks[0].targetPath);
        expect(path.resolve(path.dirname(parsedManifest.symlinks[0].targetPath), symlinkTarget)).toBe(lazygitSourceConfigPath);
      });
    });
  });

  describe('executing a generated shim for an uninstalled tool', () => {
    let testDirs: TestDirectories;
    let fs: NodeFileSystem;
    let mockServer: MockGitHubServerResult;
    let fzfShimPath: string;
    let localArchiveFilePath: string;
    let manifestPath: string;

    const mockToolName = 'fzf';
    const mockToolVersion = '0.54.0'; // from fzf.tool.ts fixture
    const mockAssetFileName = `fzf-${mockToolVersion}-darwin_arm64.tar.gz`;

    beforeAll(async () => {
      fs = new NodeFileSystem();
      const logger = new TestLogger();
      testDirs = await createTestDirectories(logger, fs,{
        testName: 'cli-generate-shim-execution',
        additionalDirs: {
          'temp-archive-source': { path: 'temp-archive-source' },
        },
      });

      fzfShimPath = path.join(testDirs.paths.targetDir, mockToolName);
      manifestPath = path.join(testDirs.paths.generatedDir, 'manifest.json');

      // 1. Create a mock binary and archive it
      await createFile(
        fs,
        path.join(testDirs.getDir('temp-archive-source'), mockToolName),
        `#!/bin/sh\necho "Mock fzf v${mockToolVersion}"`,
        true
      );

      localArchiveFilePath = path.join(testDirs.paths.homeDir, mockAssetFileName);
      await $`tar -czf ${localArchiveFilePath} -C ${testDirs.getDir('temp-archive-source')} ${mockToolName}`.quiet();

      // 2. Setup mock github server
      mockServer = await createMockGitHubServer({
        apiPaths: [
          {
            path: `/repos/junegunn/fzf/releases/tags/${mockToolVersion}`,
            response: {
              tag_name: mockToolVersion,
              assets: [{ name: mockAssetFileName, browser_download_url: `/${mockAssetFileName}` }],
            },
          },
          {
            path: `/repos/junegunn/fzf/releases/latest`,
            response: {
              tag_name: mockToolVersion,
              assets: [{ name: mockAssetFileName, browser_download_url: `/${mockAssetFileName}` }],
            },
          },
        ],
        binaryPaths: [{ path: `/${mockAssetFileName}`, filePath: localArchiveFilePath }],
      });

      // 3. Create mock YAML config
      await createMockYamlConfig({
        config: {
          paths: {
            ...testDirs.paths,
            manifestPath: manifestPath,
          },
          github: {
            host: mockServer.baseUrl,
          },
        },
        filePath: path.join(testDirs.paths.dotfilesDir, 'config.yaml'),
        fileSystem: fs,
        logger,
        systemInfo: { platform: 'darwin', arch: 'arm64', homeDir: testDirs.paths.homeDir },
        env: {},
      });

      // 4. Create tool config
      createToolConfig({
        toolConfigsDir: testDirs.paths.toolConfigsDir,
        name: mockToolName,
        fixturePath: path.resolve(__dirname, 'fixtures', 'fzf.tool.ts'),
      });

      // 5. Generate shims and symlinks
      const generateResult = executeCliCommand({
        command: ['generate'],
        cwd: testDirs.paths.dotfilesDir,
        homeDir: testDirs.paths.homeDir,
      });

      expect(generateResult.stderr).toEqual('');
      expect(generateResult.exitCode).toEqual(0);
    });

    afterAll(async () => {
      await mockServer.close();
    });

    it('should automatically install and execute the tool when it is not present', async () => {
      const shimResult = executeCliCommand({
        command: ['--version'],
        cwd: testDirs.paths.homeDir,
        homeDir: testDirs.paths.homeDir,
        customCmd: [fzfShimPath],
        env: {},
      });
      
      expect(shimResult.stderr).toBe('');
      expect(shimResult.stdout).toContain(`Mock fzf v${mockToolVersion}`);
      expect(shimResult.exitCode).toBe(0);
    });
  });
});
