/**
 * @file src/types/appConfig.types.ts
 * @description Types related to application configuration.
 *
 * ## Development Plan
 *
 * ### Tasks
 * - [x] Define types for application configuration.
 * - [x] Add JSDoc comments to all types and properties.
 * - [x] Correct JSDoc for targetDir, generatedDir, binariesDir, binDir and add @example tags.
 * - [ ] Ensure all necessary imports are present.
 * - [ ] Ensure all types are exported.
 * - [ ] (No dedicated tests needed for this file as it only contains type definitions - correctness verified by TSC and consuming code's tests, as per techContext.md and .roorules)
 * - [ ] Cleanup all linting errors and warnings.
 * - [ ] Cleanup all comments that are no longer relevant (leaving development plan).
 * - [ ] Update the memory bank with the new information when all tasks are complete.
 */

// ============================================
// AppConfig Types
// ============================================

/**
 * Defines the overall configuration structure for the application.
 * This configuration is typically loaded from environment variables (`.env` file)
 * and command-line arguments, then processed and validated by `src/modules/config/config.ts`.
 *
 * @remarks
 * When adding new properties to this interface, ensure that `src/modules/config/config.ts`
 * (specifically the `EnvSchema` and the `createAppConfig` function)
 * and its tests (`src/modules/config/__tests__/config.test.ts`) are updated accordingly
 * to handle loading, validation, and default values for the new properties.
 */
export interface AppConfig {
  /**
   * The primary user-specified output directory. This is often the user's home directory
   * (e.g., `~`) or a project root (e.g., `/home/user/my-project`).
   * Shims are *not* directly placed here by default, but rather within a subdirectory
   * like `appConfig.binDir` (e.g., `${targetDir}/.generated/bin`).
   * @example /usr/bin
   */
  targetDir: string;
  /**
   * The root directory of the dotfiles project itself.
   * This is used to locate source files, templates, and other project assets.
   * @example /home/user/.dotfiles
   */
  dotfilesDir: string;
  /**
   * The user's home directory.
   * This is automatically detected and used for various path resolutions.
   * @example /home/user
   */
  homeDir: string;
  /**
   * The main directory *within `targetDir`* for all generated content
   * (e.g., binaries, symlinks, scripts, cache).
   * Typically `${targetDir}/.generated`.
   * @example /home/user/.dotfiles/.generated
   */
  generatedDir: string;
  /**
   * The directory path where individual tool configuration files (e.g., `fzf.tool.ts`) are located within the dotfiles project.
   * This was the original path for tool configurations.
   * @deprecated Prefer `toolConfigsDir` for clarity and consistency.
   * @example /home/user/.dotfiles/src/tools
   */
  toolConfigDir: string;
  /**
   * The directory path where tool configuration files (e.g., `fzf.tool.ts`) are located within the dotfiles project.
   * This is the preferred, more clearly named path for the directory containing multiple tool configurations.
   * @example /home/user/.dotfiles/generator/configs/tools
   */
  toolConfigsDir: string;
  /**
   * The debug string used to enable specific logging namespaces for the `debug` library.
   * For example, `generator:*` enables all logs from the generator.
   */
  debug: string;
  /**
   * A boolean flag indicating whether caching mechanisms (e.g., for downloads, API responses) should be enabled.
   * @default true
   */
  cacheEnabled: boolean;
  /**
   * An optional custom prompt message to be displayed when `sudo` is required for an operation.
   * If not provided, the system's default `sudo` prompt will be used.
   */
  sudoPrompt?: string;

  // Derived paths
  /**
   * The absolute path to the directory used for caching application data, such as downloaded files or API responses.
   * This path is derived from other configuration values (e.g., `generatedDir`).
   * @example /home/user/.dotfiles/.generated/cache
   */
  cacheDir: string;
  /**
   * The directory where *actual downloaded tool binaries* are stored.
   * This is typically located within `generatedDir`.
   * @example /home/user/.dotfiles/.generated/binaries
   */
  binariesDir: string;
  /**
   * The directory where *shims (symlinks to binaries in `binariesDir`)* are created.
   * This directory should be added to the user's `PATH` environment variable to make tools accessible.
   * Typically located within `generatedDir`.
   * @example /home/user/.dotfiles/.generated/bin
   */
  binDir: string;
  /**
   * The directory where Zsh initialization scripts and configurations generated by the application are stored.
   * Typically `.generated/zsh` within `targetDir`.
   * @example /home/user/.dotfiles/.generated/zsh
   */
  zshInitDir: string;
  /**
   * The absolute path to the main manifest file that tracks installed tools and their versions.
   * Typically `.generated/manifest.json` within `targetDir`.
   * @example /home/user/.dotfiles/.generated/manifest.json
   */
  manifestPath: string;
  /**
   * The base directory where shell completion scripts for various tools are generated and stored.
   * Typically `.generated/completions` within `targetDir`.
   * @example /home/user/.dotfiles/.generated/completions
   */
  completionsDir: string;
  /**
   * The path to the manifest file used by the `GeneratorOrchestrator` to track generated artifacts like symlinks and scripts.
   * This helps in cleaning up artifacts when tools are uninstalled or configurations change.
   * Typically `.generated/artifacts-manifest.json` within `targetDir`.
   * @example /home/user/.dotfiles/.generated/generated-manifest.json
   */
  generatedArtifactsManifestPath: string;

  // New configuration options
  /**
   * An optional GitHub Personal Access Token (PAT) used for authenticating with the GitHub API.
   * Providing a token can help avoid rate limits and access private repositories if needed.
   */
  githubToken?: string;
  /**
   * The base URL for the GitHub API.
   * Useful for GitHub Enterprise instances or for testing against a mock server.
   * @default "https://api.github.com"
   */
  githubHost?: string;
  /**
   * A boolean flag indicating whether the application should automatically check for updates to installed tools upon execution.
   * @default false
   */
  checkUpdatesOnRun?: boolean;
  /**
   * The interval, in seconds, between automatic update checks if `checkUpdatesOnRun` is enabled.
   * @default 86400 (24 hours)
   */
  updateCheckInterval?: number;
  /**
   * The timeout duration, in milliseconds, for download operations.
   * @default 30000 (30 seconds)
   */
  downloadTimeout?: number;
  /**
   * The number of times a download operation should be retried if it fails.
   * @default 3
   */
  downloadRetryCount?: number;
  /**
   * The delay, in milliseconds, between download retry attempts.
   * @default 1000 (1 second)
   */
  downloadRetryDelay?: number;
  /**
   * An optional custom User-Agent string to be used when making requests to the GitHub API.
   * If not provided, a default User-Agent may be used by the HTTP client.
   */
  githubClientUserAgent?: string;

  /**
   * A boolean flag indicating whether caching for GitHub API responses is enabled.
   * When enabled, responses from the GitHub API are cached to reduce redundant requests and improve performance.
   * @default true
   */
  githubApiCacheEnabled?: boolean;

  /**
   * The time-to-live (TTL) for GitHub API cache entries, specified in milliseconds.
   * Defines how long a cached API response is considered valid before it needs to be refreshed.
   * @default 86400000 (24 hours)
   */
  githubApiCacheTtl?: number;
  /**
   * The directory where GitHub API cache files are stored.
   * This path is typically derived and located within the main `cacheDir`.
   * @example /home/user/.dotfiles/.generated/cache/github-api
   */
  githubApiCacheDir: string;
  /**
   * The simple name of the shim created for the main dotfiles generator CLI itself.
   * This shim resides in `appConfig.binDir` and can be used by other scripts
   * to call the main CLI in a way that's consistent with how other tools are called.
   * @example "dotfiles-shim-generator"
   */
  generatorCliShimName: string;
}
