/**
 * @file src/types/manifest.types.ts
 * @description Types related to the generated artifacts manifest.
 *
 * ## Development Plan
 *
 * ### Tasks
 * - [x] Define types for manifests.
 * - [x] Add JSDoc comments to all types and properties.
 * - [ ] Ensure all necessary imports are present.
 * - [ ] Ensure all types are exported.
 * - [ ] (No dedicated tests needed for this file as it only contains type definitions - correctness verified by TSC and consuming code's tests, as per techContext.md and .roorules)
 * - [ ] Cleanup all linting errors and warnings.
 * - [ ] Cleanup all comments that are no longer relevant (leaving development plan).
 * - [ ] Update the memory bank with the new information when all tasks are complete.
 */

import type { SymlinkOperationResult } from '@modules/generator-symlink/ISymlinkGenerator';
import type { ShellType } from './completion.types';

// ============================================
// Manifest Types
// ============================================

/**
 * Represents a single entry in the main tool manifest file (`manifest.json`).
 * Each entry tracks the installation status and metadata for a specific tool.
 */
export interface ManifestEntry {
  /** The unique name of the tool (e.g., 'fzf', 'ripgrep'). */
  toolName: string;
  /** The absolute path to the generated shim (executable script) for this tool. */
  shimPath: string;
  /**
   * The absolute path to the actual installed binary of the tool.
   * This may be undefined if the tool is not yet installed or if installation failed.
   */
  binaryPath?: string;
  /**
   * The version of the tool that is currently installed.
   * This should match the version specified in the tool's configuration or the latest fetched version.
   */
  version?: string;
  /** An ISO 8601 date string indicating when the tool was first installed or last successfully updated. */
  installedOn?: string;
  /** An ISO 8601 date string indicating the last time an update check was performed for this tool. */
  lastChecked?: string;
  /** An ISO 8601 date string indicating the last time this tool was actually updated to a new version. */
  lastUpdated?: string;
  /** The path to the tool's TypeScript configuration file (e.g., `generator/configs/tools/fzf.tool.ts`). */
  configPath: string;
  /**
   * A record of installed shell completion files for this tool.
   * The keys are {@link ShellType} (e.g., 'zsh', 'bash') and values are the paths to the installed completion scripts.
   */
  completions?: {
    [K in ShellType]?: string;
  };
}

/**
 * Represents the structure of the main tool manifest file (`manifest.json`).
 * This file acts as a database for all tools managed by the generator,
 * mapping tool names to their respective {@link ManifestEntry} data.
 */
export interface Manifest {
  /** Each key is a tool name, and the value is its {@link ManifestEntry}. */
  [toolName: string]: ManifestEntry;
}

/**
 * Represents the structure of the global manifest file for all generated artifacts (`artifacts-manifest.json`).
 * This manifest is managed by the `GeneratorOrchestrator` and tracks various files
 * created during the generation process, such as shims, shell initialization scripts, and symlinks.
 * This allows for easier cleanup and management of generated content.
 */
export interface GeneratedArtifactsManifest {
  /** An ISO 8601 date string indicating the timestamp of the last successful generation run. */
  lastGenerated: string;

  /** An array of paths to all shim files generated by the `ShimGenerator`. */
  shims?: string[];

  /**
   * Information about the aggregated shell initialization file, if one was generated.
   */
  shellInit?: {
    /**
     * The path to the generated shell initialization file (e.g., `~/.generated/zsh/init.zsh`).
     * This can be `null` if no shell initialization content was generated.
     */
    path: string | null;
  };

  /** An array of {@link SymlinkOperationResult} objects detailing the outcome of symlink creation attempts. */
  symlinks?: SymlinkOperationResult[];

  /**
   * An optional version string of the generator tool that created or last updated this manifest.
   * This can be useful for compatibility checks or migration purposes in the future.
   */
  generatorVersion?: string;
  // Future consideration: Potentially add versions of individual generators or tool configurations used
  // to create the artifacts listed in this manifest for more granular tracking.
}
