/**
 * @file generator/src/types/manifest.types.ts
 * @description Types related to the generated artifacts manifest.
 *
 * ## Development Plan
 *
 * ### Tasks
 * - [x] Define types for manifests.
 * - [ ] Add JSDoc comments to all types and properties.
 * - [ ] Ensure all necessary imports are present.
 * - [ ] Ensure all types are exported.
 * - [ ] (No dedicated tests needed for this file as it only contains type definitions - correctness verified by TSC and consuming code's tests, as per techContext.md and .roorules)
 * - [ ] Cleanup all linting errors and warnings.
 * - [ ] Cleanup all comments that are no longer relevant (leaving development plan).
 * - [ ] Update the memory bank with the new information when all tasks are complete.
 */

import type { SymlinkOperationResult } from '../modules/generator-symlink/ISymlinkGenerator';
import type { ShellType } from './completion.types';

// ============================================
// Manifest Types
// ============================================

/**
 * Represents an entry in the manifest file.
 */
export interface ManifestEntry {
  toolName: string;
  shimPath: string;
  binaryPath?: string; // Actual path to the installed binary
  version?: string;
  installedOn?: string; // ISO date string
  lastChecked?: string; // NEW: Last update check timestamp
  lastUpdated?: string; // NEW: Last actual update timestamp
  configPath: string; // Path to the tool's TypeScript config file
  completions?: {
    // NEW: Installed completion files
    [K in ShellType]?: string;
  };
}

/**
 * Represents the structure of the manifest file.
 */
export interface Manifest {
  [toolName: string]: ManifestEntry;
}

/**
 * Represents the structure of the global manifest file for all generated artifacts.
 * This manifest is managed by the GeneratorOrchestrator.
 */
export interface GeneratedArtifactsManifest {
  /** ISO date string of the last successful generation run. */
  lastGenerated: string;

  /** List of paths to all shim files generated by the ShimGenerator. */
  shims?: string[];

  /** Path to the aggregated shell initialization file, if generated. */
  shellInit?: {
    path: string | null; // Path to the shell init file
  };

  /** Detailed results of symlink operations. */
  symlinks?: SymlinkOperationResult[];

  /** Optional: Version of the generator tool that created this manifest. */
  generatorVersion?: string;
  // Potentially add versions of generators or tool configs used
}
