import type { ShellType } from '@dotfiles/core';

/**
 * Gets the comment prefix for a given shell type.
 */
function getCommentPrefix(shellType: ShellType): string {
  switch (shellType) {
    case 'zsh':
    case 'bash':
    case 'powershell':
      return '#';
    default:
      return '#';
  }
}

/**
 * Creates a commented line with shell-appropriate comment syntax.
 * @param shellType - Type of shell for comment syntax
 * @param value - The text to comment
 * @returns Formatted comment line
 */
export function commentLine(shellType: ShellType, value: string): string {
  const comment = getCommentPrefix(shellType);
  return `${comment} ${value}`;
}

/**
 * Generates a header line with repeated characters, optionally with centered text.
 * @param shellType - Type of shell for comment syntax
 * @param lineChar - Character to repeat (e.g., '=', '-')
 * @param title - Optional title to center in the line
 * @returns Formatted header line
 */
export function headerLine(shellType: ShellType, lineChar: string, title?: string): string {
  const totalWidth = 80;

  if (!title) {
    return commentLine(shellType, lineChar.repeat(totalWidth - 2));
  }

  const titleWithSpaces = ` ${title} `;
  const charsNeeded = Math.max(0, totalWidth - 1 - titleWithSpaces.length); // -1 for comment prefix
  const leftChars = lineChar.repeat(Math.floor(charsNeeded / 2));
  const rightChars = lineChar.repeat(Math.ceil(charsNeeded / 2));

  return commentLine(shellType, `${leftChars}${titleWithSpaces}${rightChars}`);
}

/**
 * Creates a centered section header with triple equals signs spanning 80 characters total.
 * Format: # === Section Title ===
 *
 * @param shellType - Type of shell for comment syntax
 * @param title - The section title to center
 * @returns A formatted header string
 */
export function createSectionHeader(shellType: ShellType, title: string): string {
  return headerLine(shellType, '=', title);
}

/**
 * Generates the file header warning users not to edit the generated file.
 * @param shellType - Type of shell for comment syntax
 * @param dotfilesDir - Path to the dotfiles directory
 * @returns File header string
 */
export function generateFileHeader(shellType: ShellType, dotfilesDir: string): string {
  return [
    headerLine(shellType, '='),
    commentLine(shellType, 'THIS FILE IS AUTOMATICALLY GENERATED BY THE DOTFILES MANAGEMENT TOOL'),
    commentLine(shellType, 'DO NOT EDIT THIS FILE DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN'),
    headerLine(shellType, '='),
    '',
    commentLine(shellType, `Dotfiles directory: ${dotfilesDir}`),
    '',
  ].join('\n');
}

/**
 * Generates a section header with consistent 80-character width.
 * @param shellType - Type of shell for comment syntax
 * @param sectionTitle - Title of the section
 * @returns Formatted section header
 */
export function generateSectionHeader(shellType: ShellType, sectionTitle: string): string {
  return createSectionHeader(shellType, sectionTitle);
}

/**
 * Generates a tool attribution header with file path information.
 * @param shellType - Type of shell for comment syntax
 * @param toolName - Name of the tool
 * @param configFilePath - Path to the tool's configuration file
 * @returns Tool header string
 */
export function generateToolHeader(shellType: ShellType, toolName: string, configFilePath?: string): string {
  const lines = ['', headerLine(shellType, '=')];

  if (configFilePath) {
    lines.push(commentLine(shellType, `Configuration from: ${configFilePath}`));
  }

  lines.push(commentLine(shellType, `Tool: ${toolName}`), headerLine(shellType, '='));

  return lines.join('\n');
}

/**
 * Generates hoisting explanation comments for sections that move content
 * from tool-specific configs to centralized sections.
 * @param shellType - Type of shell for comment syntax
 * @param sectionTitle - The section title (e.g., "PATH Modifications")
 * @returns Hoisting explanation string
 */
export function generateHoistingExplanation(shellType: ShellType, sectionTitle: string): string {
  return [
    commentLine(
      shellType,
      `The following ${sectionTitle.toLowerCase()} have been hoisted from tool-specific configurations`
    ),
    commentLine(shellType, 'for better organization and to avoid conflicts'),
    '',
  ].join('\n');
}

/**
 * Generates a comment indicating which tools contributed to a hoisted item.
 * @param shellType - Type of shell for comment syntax
 * @param sourceTools - Array of tool names that contributed the item
 * @returns Comment line or empty string if no sources
 */
export function generateHoistingAttribution(shellType: ShellType, sourceTools: string[]): string {
  if (sourceTools.length === 0) return '';
  return commentLine(shellType, `Hoisted from: ${sourceTools.join(', ')}`);
}

/**
 * Generates shell-specific default PATH modification with deduplication check.
 * @param shellType - Type of shell (zsh, bash, powershell)
 * @param targetDir - Path to the target directory (where shims are placed)
 * @returns Shell-appropriate PATH modification command with conditional check
 */
export function generateDefaultPathModification(shellType: ShellType, targetDir: string): string {
  switch (shellType) {
    case 'powershell':
      return `if ($env:PATH -notlike "*${targetDir}*") { $env:PATH = "${targetDir};$env:PATH" }`;
    case 'zsh':
    case 'bash':
      return `if [[ ":$PATH:" != *":${targetDir}:"* ]]; then\n  export PATH="${targetDir}:$PATH"\nfi`;
    default:
      return `if [[ ":$PATH:" != *":${targetDir}:"* ]]; then\n  export PATH="${targetDir}:$PATH"\nfi`;
  }
}

/**
 * Generates shell-specific completion setup commands.
 * @param shellType - Type of shell
 * @param completionDir - Directory containing completion files
 * @returns Shell-appropriate completion setup commands
 */
export function generateCompletionSetup(shellType: ShellType, completionDir: string): string[] {
  switch (shellType) {
    case 'zsh':
      return ['typeset -U fpath', `fpath=("${completionDir}/completions" $fpath)`];
    default:
      // Bash and PowerShell completions are handled per-tool
      return [];
  }
}

/**
 * Generates the end-of-file marker.
 * @param shellType - Type of shell for comment syntax
 * @returns End of file section header
 */
export function generateEndOfFile(shellType: ShellType): string {
  return generateSectionHeader(shellType, 'End of Generated File');
}

/**
 * Generates shell-specific source command for including generated scripts.
 * @param shellType - Type of shell
 * @param scriptPath - Path to the script to source
 * @returns Appropriate source command for the shell
 */
export function generateSourceLine(shellType: ShellType, scriptPath: string): string {
  switch (shellType) {
    case 'zsh':
    case 'bash':
      return `source "${scriptPath}"`;
    case 'powershell':
      return `. "${scriptPath}"`;
    default:
      throw new Error(`Unsupported shell type: ${shellType}`);
  }
}

/**
 * Generates a header comment block for profile file modifications.
 * Creates a double-line header with generator attribution and config path.
 * @param shellType - Type of shell for comment syntax
 * @param projectConfigPath - Full path to the project config file
 * @returns Multi-line header comment block
 */
export function generateProfileHeader(shellType: ShellType, projectConfigPath: string): string {
  return [
    commentLine(shellType, 'Generated via dotfiles generator - do not modify'),
    commentLine(shellType, projectConfigPath),
    headerLine(shellType, '-'),
  ].join('\n');
}
