import { afterAll, beforeAll, describe, expect, it } from 'bun:test';
import * as path from 'node:path';
import { NodeFileSystem } from '@dotfiles/file-system';
import { TestLogger } from '@dotfiles/logger';
import {
  createFile,
  createMockApiServer,
  createMockYamlConfig,
  createTestDirectories,
  createToolConfig,
  type MockApiServerResult,
  type TestDirectories,
} from '@dotfiles/testing-helpers';
import { $ } from 'bun';
import { executeCliCommand } from '../src/__tests__/executeCliCommand';

import '@dotfiles/testing-helpers';

describe('E2E: bun run cli generate', () => {
  describe('generating shims, shell init, and symlinks', () => {
    let testDirs: TestDirectories;
    let fs: NodeFileSystem;

    // Paths for generated artifacts
    let fzfShimPath: string;
    let lazygitShimPath: string;
    let zshInitFilePath: string;
    let lazygitSourceConfigPath: string;
    let cliExitCode: number | null;
    let cliStderr: string;

    beforeAll(async () => {
      fs = new NodeFileSystem();
      const logger = new TestLogger();
      testDirs = await createTestDirectories(logger, fs, {
        testName: 'cli-generate-e2e',
      });

      // Define paths for generated artifacts
      fzfShimPath = path.join(testDirs.paths.targetDir, 'fzf');
      lazygitShimPath = path.join(testDirs.paths.targetDir, 'lazygit');
      zshInitFilePath = path.join(testDirs.paths.shellScriptsDir, 'main.zsh');
      lazygitSourceConfigPath = path.join(testDirs.paths.toolConfigsDir, '02-configs', 'lazygit', 'config.yml');

      // Create mock lazygit config file at the location expected by the tool config
      await createFile(fs, lazygitSourceConfigPath, '# Sample lazygit config for E2E test');

      const configFilePath = path.join(testDirs.paths.dotfilesDir, 'config.yaml');
      await createMockYamlConfig({
        config: {
          paths: testDirs.paths,
          userConfigPath: configFilePath,
        },
        filePath: configFilePath,
        fileSystem: fs,
        logger,
        systemInfo: {
          platform: 'linux',
          arch: 'x64',
          homeDir: testDirs.paths.homeDir,
        },
        env: {},
      });

      // Create tool configs
      createToolConfig({
        toolConfigsDir: testDirs.paths.toolConfigsDir,
        name: 'fzf',
        fixturePath: path.resolve(__dirname, 'fixtures', 'fzf.tool.ts'),
      });
      createToolConfig({
        toolConfigsDir: testDirs.paths.toolConfigsDir,
        name: 'lazygit',
        fixturePath: path.resolve(__dirname, 'fixtures', 'lazygit.tool.ts'),
      });

      // Execute CLI command
      const result = executeCliCommand({
        command: ['generate', '--config', 'config.yaml'],
        cwd: testDirs.paths.dotfilesDir,
        homeDir: testDirs.paths.homeDir,
      });

      cliExitCode = result.exitCode;
      cliStderr = result.stderr;
    });

    it('should execute the CLI successfully', () => {
      expect(cliStderr).toEqual('');
      expect(cliExitCode).toEqual(0);
    });

    it('should generate the correct shim files for fzf and lazygit', async () => {
      expect(await fs.exists(fzfShimPath)).toBe(true);
      expect(await fs.exists(lazygitShimPath)).toBe(true);

      for (const shimP of [fzfShimPath, lazygitShimPath]) {
        const stat = await fs.stat(shimP);
        expect(stat.mode & 0o100).toBeGreaterThan(0); // Check executable
      }

      const fzfContent = await fs.readFile(fzfShimPath);
      expect(fzfContent).toMatchLooseInlineSnapshot`
        #!/usr/bin/env bash
        # Shim for fzf
        # Generated by Dotfiles Management Tool

        set -euo pipefail

        TOOL_NAME="fzf"
        TOOL_EXECUTABLE="${testDirs.paths.binariesDir}/fzf/fzf"
        GENERATOR_CLI_EXECUTABLE="${/.*cli\.ts/}"
        CONFIG_PATH="config.yaml"

        # Check if the first argument is @update
        if [ $# -gt 0 ] && [ "$1" = "@update" ]; then
          echo "Updating $TOOL_NAME to latest version..."
          # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
          eval "$GENERATOR_CLI_EXECUTABLE" update --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"'
          exit $?
        fi

        # Check if tool exists and execute it
        if [ -x "$TOOL_EXECUTABLE" ]; then
          exec "$TOOL_EXECUTABLE" "$@"
        else
          # Tool not found, try to install it
          # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
          # Let stderr (progress bars) pass through to the user
          # Temporarily disable set -e to handle install failures gracefully
          set +e
          eval "$GENERATOR_CLI_EXECUTABLE" install --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"'
          install_exit_code=$?
          set -e
          
          if [ $install_exit_code -eq 0 ]; then
            # Installation successful, try to execute binary again
            if [ -x "$TOOL_EXECUTABLE" ]; then
              exec "$TOOL_EXECUTABLE" "$@"
            else
              echo "Installation completed but binary not found at: $TOOL_EXECUTABLE" >&2
              exit 1
            fi
          else
            # Installation failed, exit with the same code
            exit $install_exit_code
          fi
        fi
      `;

      const lazygitContent = await fs.readFile(lazygitShimPath);
      expect(lazygitContent).toMatchLooseInlineSnapshot`
        #!/usr/bin/env bash
        # Shim for lazygit
        # Generated by Dotfiles Management Tool

        set -euo pipefail

        TOOL_NAME="lazygit"
        TOOL_EXECUTABLE="${testDirs.paths.binariesDir}/lazygit/lazygit"
        GENERATOR_CLI_EXECUTABLE="${/.*cli\.ts/}"
        CONFIG_PATH="config.yaml"

        # Check if the first argument is @update
        if [ $# -gt 0 ] && [ "$1" = "@update" ]; then
          echo "Updating $TOOL_NAME to latest version..."
          # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
          eval "$GENERATOR_CLI_EXECUTABLE" update --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"'
          exit $?
        fi

        # Check if tool exists and execute it
        if [ -x "$TOOL_EXECUTABLE" ]; then
          exec "$TOOL_EXECUTABLE" "$@"
        else
          # Tool not found, try to install it
          # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
          # Let stderr (progress bars) pass through to the user
          # Temporarily disable set -e to handle install failures gracefully
          set +e
          eval "$GENERATOR_CLI_EXECUTABLE" install --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"'
          install_exit_code=$?
          set -e
          
          if [ $install_exit_code -eq 0 ]; then
            # Installation successful, try to execute binary again
            if [ -x "$TOOL_EXECUTABLE" ]; then
              exec "$TOOL_EXECUTABLE" "$@"
            else
              echo "Installation completed but binary not found at: $TOOL_EXECUTABLE" >&2
              exit 1
            fi
          else
            # Installation failed, exit with the same code
            exit $install_exit_code
          fi
        fi
      `;
    });

    it('should generate the correct shell initialization file content', async () => {
      expect(await fs.exists(zshInitFilePath)).toBe(true);
      const content = await fs.readFile(zshInitFilePath);
      expect(content).toContain('__dotfiles_fzf_always');
      expect(content).toContain('export FZF_DEFAULT_OPTS=');
      expect(content).toContain('__dotfiles_lazygit_always');
      expect(content).toContain('alias g="lazygit"');
    });
  });

  describe('executing a generated shim for an uninstalled tool', () => {
    let testDirs: TestDirectories;
    let fs: NodeFileSystem;
    let mockServer: MockApiServerResult;
    let fzfShimPath: string;
    let localArchiveFilePath: string;

    const mockToolName = 'fzf';
    const mockToolVersion = '0.54.0'; // from fzf.tool.ts fixture
    const mockAssetFileName = `fzf-${mockToolVersion}-darwin_arm64.tar.gz`;

    beforeAll(async () => {
      fs = new NodeFileSystem();
      const logger = new TestLogger();
      testDirs = await createTestDirectories(logger, fs, {
        testName: 'cli-generate-shim-execution',
        additionalDirs: {
          'temp-archive-source': { path: 'temp-archive-source' },
        },
      });

      fzfShimPath = path.join(testDirs.paths.targetDir, mockToolName);

      // 1. Create a mock binary and archive it with realistic directory structure
      const mockBinaryDir = path.join(testDirs.getDir('temp-archive-source'), `fzf-${mockToolVersion}`);
      await fs.ensureDir(mockBinaryDir);
      await createFile(
        fs,
        path.join(mockBinaryDir, mockToolName),
        `#!/bin/sh\necho "Mock fzf v${mockToolVersion}"`,
        true
      );

      localArchiveFilePath = path.join(testDirs.paths.homeDir, mockAssetFileName);
      await $`tar -czf ${localArchiveFilePath} -C ${testDirs.getDir('temp-archive-source')} fzf-${mockToolVersion}`;

      // 2. Setup mock github server
      mockServer = await createMockApiServer({
        apiPaths: [
          {
            path: `/repos/junegunn/fzf/releases/tags/${mockToolVersion}`,
            response: {
              tag_name: mockToolVersion,
              assets: [{ name: mockAssetFileName, browser_download_url: `/${mockAssetFileName}` }],
            },
          },
          {
            path: `/repos/junegunn/fzf/releases/latest`,
            response: {
              tag_name: mockToolVersion,
              assets: [{ name: mockAssetFileName, browser_download_url: `/${mockAssetFileName}` }],
            },
          },
        ],
        binaryPaths: [{ path: `/${mockAssetFileName}`, filePath: localArchiveFilePath }],
      });

      // 3. Create mock YAML config
      const configFilePath = path.join(testDirs.paths.dotfilesDir, 'config.yaml');
      await createMockYamlConfig({
        config: {
          paths: testDirs.paths,
          github: {
            host: mockServer.baseUrl,
          },
          userConfigPath: configFilePath,
        },
        filePath: configFilePath,
        fileSystem: fs,
        logger,
        systemInfo: { platform: 'darwin', arch: 'arm64', homeDir: testDirs.paths.homeDir },
        env: {},
      });

      // 4. Create tool config
      createToolConfig({
        toolConfigsDir: testDirs.paths.toolConfigsDir,
        name: mockToolName,
        fixturePath: path.resolve(__dirname, 'fixtures', 'fzf.tool.ts'),
      });

      // 5. Generate shims and symlinks
      const generateResult = executeCliCommand({
        command: ['generate', '--config', 'config.yaml'],
        cwd: testDirs.paths.dotfilesDir,
        homeDir: testDirs.paths.homeDir,
      });

      expect(generateResult.stderr).toEqual('');
      expect(generateResult.exitCode).toEqual(0);
    });

    afterAll(async () => {
      await mockServer.close();
    });

    it('should execute pre-installed tool via shim', async () => {
      // Manually create the binary and symlink to test shim execution
      const toolDir = path.join(testDirs.paths.binariesDir, 'fzf');
      const timestampDir = path.join(toolDir, '2025-08-13-test');
      const binaryDir = path.join(timestampDir, 'fzf-0.54.0');
      const binaryPath = path.join(binaryDir, 'fzf');
      const symlinkPath = path.join(toolDir, 'fzf');

      // Create the binary
      await fs.ensureDir(binaryDir);
      await fs.writeFile(binaryPath, `#!/bin/sh\necho "Mock fzf v${mockToolVersion}"`);
      await fs.chmod(binaryPath, 0o755);

      // Create the symlink
      await fs.ensureDir(toolDir);
      const relativePath = path.relative(toolDir, binaryPath);
      await fs.symlink(relativePath, symlinkPath);

      // Verify symlink was created
      expect(await fs.exists(symlinkPath)).toBe(true);

      // Test that the shim can execute the tool
      const shimResult = executeCliCommand({
        command: ['--version'],
        cwd: testDirs.paths.dotfilesDir,
        homeDir: testDirs.paths.homeDir,
        customCmd: [fzfShimPath],
        env: {},
      });

      expect(shimResult.stderr).toBe('');
      expect(shimResult.stdout).toContain(`Mock fzf v${mockToolVersion}`);
      expect(shimResult.exitCode).toBe(0);
    });
  });
});
