import type { IBlock, IBlockMetadata, IFormatterConfig } from "@dotfiles/shell-emissions";

const DEFAULT_HEADER_WIDTH = 80;
const DEFAULT_INDENT_SIZE = 2;

/**
 * Base class for all shell emission formatters.
 * Contains shared formatting infrastructure (headers, comments, configuration)
 * that is identical across all shell types.
 *
 * Shell-specific subclasses extend this to implement:
 * - comment() method for shell-specific comment syntax
 * - Shell-specific emission formatting
 */
export abstract class BaseEmissionFormatter {
  abstract readonly fileExtension: string;

  protected readonly headerWidth: number;
  protected readonly indentSize: number;
  protected readonly onceScriptDir?: string;

  constructor(config: IFormatterConfig) {
    this.headerWidth = config.headerWidth ?? DEFAULT_HEADER_WIDTH;
    this.indentSize = config.indentSize ?? DEFAULT_INDENT_SIZE;
    this.onceScriptDir = config.onceScriptDir;
  }

  /**
   * Shell-specific comment syntax.
   * Override in subclasses if the shell uses different comment syntax.
   * Default is '#' which works for POSIX shells and PowerShell.
   */
  comment(text: string): string {
    return `# ${text}`;
  }

  commentBlock(lines: string[]): string {
    return lines.map((line) => this.comment(line)).join("\n");
  }

  formatFileHeader(metadata?: IBlockMetadata): string {
    const lines = [
      this.headerLine("="),
      this.comment("THIS FILE IS AUTOMATICALLY GENERATED BY THE DOTFILES MANAGEMENT TOOL"),
      this.comment("DO NOT EDIT THIS FILE DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN"),
      this.headerLine("="),
      "",
    ];

    if (metadata?.sourceFile) {
      lines.push(this.comment(`Dotfiles directory: ${metadata.sourceFile}`));
      lines.push("");
    }

    return lines.join("\n");
  }

  formatSectionHeader(title: string): string {
    return this.headerLine("=", title);
  }

  formatChildBlockHeader(_block: IBlock): string {
    return this.headerLine("=");
  }

  formatFileFooter(): string {
    return this.headerLine("=", "End of Generated File");
  }

  protected headerLine(char: string, title?: string): string {
    const totalWidth = this.headerWidth;

    if (!title) {
      return this.comment(char.repeat(totalWidth - 2));
    }

    const titleWithSpaces = ` ${title} `;
    const charsNeeded = Math.max(0, totalWidth - 1 - titleWithSpaces.length);
    const leftChars = char.repeat(Math.floor(charsNeeded / 2));
    const rightChars = char.repeat(Math.ceil(charsNeeded / 2));

    return this.comment(`${leftChars}${titleWithSpaces}${rightChars}`);
  }

  protected generateSourceFunctionName(filePath: string): string {
    const sanitized = filePath
      .replace(/[^a-zA-Z0-9]/g, "_")
      .replace(/^_+|_+$/g, "")
      .toLowerCase();
    return `__source_${sanitized}`;
  }
}
