import path from 'node:path';
import type { GlobalProgram, Services } from './types';
import type { YamlConfig } from '@dotfiles/config';
import { loadToolConfigs as loadAllToolConfigs } from '@dotfiles/config';
import type { IFileSystem, Stats } from '@dotfiles/file-system';
import type { TsLogger } from '@dotfiles/logger';
import type { ToolConfig } from '@dotfiles/schemas';
import { ExitCode, exitCli } from '@dotfiles/utils';
import { cliLogMessages } from './log-messages';

async function loadToolConfigs(
  logger: TsLogger,
  yamlConfig: YamlConfig,
  fs: IFileSystem
): Promise<{ toolConfigs: ToolConfig[]; exitCode: ExitCode }> {
  try {
    const toolConfigsRecord = await loadAllToolConfigs(logger, yamlConfig.paths.toolConfigsDir, fs, yamlConfig);
    return { toolConfigs: Object.values(toolConfigsRecord), exitCode: ExitCode.SUCCESS };
  } catch (error: unknown) {
    logger.error(cliLogMessages.configLoadFailed('tool configurations', (error as Error).message));
    return { toolConfigs: [], exitCode: ExitCode.ERROR };
  }
}

async function checkShimConflicts(
  logger: TsLogger,
  fs: IFileSystem,
  toolConfig: ToolConfig,
  targetDir: string,
  conflictMessages: string[]
): Promise<void> {
  if (!toolConfig.binaries) return;

  for (const binary of toolConfig.binaries) {
    const binaryName = typeof binary === 'string' ? binary : binary.name;
    const shimPath = path.join(targetDir, binaryName);
    if (await fs.exists(shimPath)) {
      try {
        const content = await fs.readFile(shimPath);
        if (!content.includes('# Generated by Dotfiles Management Tool')) {
          conflictMessages.push(`[${toolConfig.name}]: ${shimPath} (exists but is not a generator shim)`);
        }
      } catch (readError: unknown) {
        logger.warn(cliLogMessages.fsReadFailed(shimPath, (readError as Error).message));
        conflictMessages.push(`[${toolConfig.name}]: ${shimPath} (exists but could not be read/verified)`);
      }
    }
  }
}

async function checkSymlinkConflicts(
  logger: TsLogger,
  fs: IFileSystem,
  toolConfig: ToolConfig,
  homeDir: string,
  dotfilesDir: string,
  conflictMessages: string[]
): Promise<void> {
  if (!toolConfig.symlinks) return;

  for (const symlink of toolConfig.symlinks) {
    const targetPath = path.join(homeDir, symlink.target);
    const sourcePath = path.join(dotfilesDir, symlink.source);

    try {
      const stats: Stats | null = await fs.lstat(targetPath);
      if (stats) {
        if (stats.isSymbolicLink()) {
          const linkString = await fs.readlink(targetPath);
          const resolvedLinkTarget = path.resolve(path.dirname(targetPath), linkString);
          if (resolvedLinkTarget !== sourcePath) {
            conflictMessages.push(
              `[${toolConfig.name}]: ${targetPath} (points to '${linkString}', expected '${sourcePath}')`
            );
          }
        } else {
          conflictMessages.push(`[${toolConfig.name}]: ${targetPath} (exists but is not a symlink)`);
        }
      }
    } catch (error: unknown) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        logger.warn(cliLogMessages.fsReadFailed(targetPath, (error as Error).message));
      }
    }
  }
}

function reportConflicts(logger: TsLogger, conflictMessages: string[]): ExitCode {
  if (conflictMessages.length > 0) {
    const header = 'Conflicts detected with files not owned by the generator:';
    const formattedConflicts = conflictMessages.map((msg) => `  - ${msg}`).join('\n');
    logger.warn(cliLogMessages.toolConflictsDetected(header, formattedConflicts));
    return ExitCode.ERROR;
  } else {
    logger.info(cliLogMessages.noConflictsDetected());
    return ExitCode.SUCCESS;
  }
}

export async function detectConflictsActionLogic(
  parentLogger: TsLogger,
  _options: Record<string, unknown>, // No specific options for this command yet
  services: Services
): Promise<ExitCode> {
  const logger = parentLogger.getSubLogger({ name: 'detectConflictsActionLogic' });
  const { yamlConfig, fs } = services;
  const conflictMessages: string[] = [];

  const toolConfigsResult = await loadToolConfigs(logger, yamlConfig, fs);

  if (toolConfigsResult.exitCode !== ExitCode.SUCCESS) {
    return toolConfigsResult.exitCode;
  }

  const toolConfigsArray = toolConfigsResult.toolConfigs;

  if (toolConfigsArray.length === 0) {
    logger.info(cliLogMessages.toolNoConfigurationsFound(yamlConfig.paths.toolConfigsDir));
    return ExitCode.SUCCESS;
  }

  for (const toolConfig of toolConfigsArray) {
    // Check for shim conflicts
    await checkShimConflicts(logger, fs, toolConfig, yamlConfig.paths.targetDir, conflictMessages);

    // Check for symlink conflicts
    await checkSymlinkConflicts(
      logger,
      fs,
      toolConfig,
      yamlConfig.paths.homeDir,
      yamlConfig.paths.dotfilesDir,
      conflictMessages
    );
  }

  return reportConflicts(logger, conflictMessages);
}

export function registerDetectConflictsCommand(
  parentLogger: TsLogger,
  program: GlobalProgram,
  servicesFactory: () => Promise<Services>
): void {
  const logger = parentLogger.getSubLogger({ name: 'registerDetectConflictsCommand' });
  program
    .command('detect-conflicts')
    .description('Detects conflicts between potential generated artifacts and existing system files.')
    .action(async (options) => {
      const combinedOptions = { ...options, ...program.opts() };
      logger.debug(cliLogMessages.commandErrorDetails(), combinedOptions);

      let exitCode: ExitCode;
      try {
        const services = await servicesFactory();
        exitCode = await detectConflictsActionLogic(logger, combinedOptions, services);
      } catch (error) {
        logger.error(
          cliLogMessages.commandExecutionFailed('detect-conflicts', ExitCode.ERROR, (error as Error).message)
        );
        logger.debug(cliLogMessages.commandErrorDetails(), error);
        exitCode = ExitCode.ERROR;
      }

      exitCli(exitCode);
    });
}
