import path from 'node:path';
import type { IConfigService, ProjectConfig } from '@dotfiles/config';
import type { ToolConfig } from '@dotfiles/core';
import type { IFileSystem, Stats } from '@dotfiles/file-system';
import type { TsLogger } from '@dotfiles/logger';
import { ExitCode, exitCli } from '@dotfiles/utils';
import { messages } from './log-messages';
import type { IGlobalProgram, IGlobalProgramOptions, IServices } from './types';

async function loadToolConfigs(
  logger: TsLogger,
  projectConfig: ProjectConfig,
  fs: IFileSystem,
  configService: IConfigService
): Promise<{ toolConfigs: ToolConfig[]; exitCode: ExitCode }> {
  try {
    const toolConfigsRecord = await configService.loadToolConfigs(
      logger,
      projectConfig.paths.toolConfigsDir,
      fs,
      projectConfig
    );
    return { toolConfigs: Object.values(toolConfigsRecord), exitCode: ExitCode.SUCCESS };
  } catch (error: unknown) {
    logger.error(messages.configLoadFailed('tool configurations'), error);
    return { toolConfigs: [], exitCode: ExitCode.ERROR };
  }
}

async function checkShimConflicts(
  logger: TsLogger,
  fs: IFileSystem,
  toolConfig: ToolConfig,
  targetDir: string,
  conflictMessages: string[]
): Promise<void> {
  if (!toolConfig.binaries) return;

  for (const binary of toolConfig.binaries) {
    const binaryName = typeof binary === 'string' ? binary : binary.name;
    const shimPath = path.join(targetDir, binaryName);
    if (await fs.exists(shimPath)) {
      try {
        const content = await fs.readFile(shimPath);
        if (!content.includes('# Generated by Dotfiles Management Tool')) {
          conflictMessages.push(`[${toolConfig.name}]: ${shimPath} (exists but is not a generator shim)`);
        }
      } catch (readError: unknown) {
        logger.warn(messages.fsReadFailed(shimPath), readError);
        conflictMessages.push(`[${toolConfig.name}]: ${shimPath} (exists but could not be read/verified)`);
      }
    }
  }
}

async function checkSymlinkConflicts(
  logger: TsLogger,
  fs: IFileSystem,
  toolConfig: ToolConfig,
  homeDir: string,
  dotfilesDir: string,
  conflictMessages: string[]
): Promise<void> {
  if (!toolConfig.symlinks) return;

  for (const symlink of toolConfig.symlinks) {
    const targetPath = path.join(homeDir, symlink.target);
    const sourcePath = path.join(dotfilesDir, symlink.source);

    try {
      const stats: Stats | null = await fs.lstat(targetPath);
      if (stats) {
        if (stats.isSymbolicLink()) {
          const linkString = await fs.readlink(targetPath);
          const resolvedLinkTarget = path.resolve(path.dirname(targetPath), linkString);
          if (resolvedLinkTarget !== sourcePath) {
            conflictMessages.push(
              `[${toolConfig.name}]: ${targetPath} (points to '${linkString}', expected '${sourcePath}')`
            );
          }
        } else {
          conflictMessages.push(`[${toolConfig.name}]: ${targetPath} (exists but is not a symlink)`);
        }
      }
    } catch (error: unknown) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        logger.warn(messages.fsReadFailed(targetPath), error);
      }
    }
  }
}

function reportConflicts(logger: TsLogger, conflictMessages: string[]): ExitCode {
  if (conflictMessages.length > 0) {
    const header = 'Conflicts detected with files not owned by the generator:';
    const formattedConflicts = conflictMessages.map((msg) => `  - ${msg}`).join('\n');
    logger.warn(messages.toolConflictsDetected(header, formattedConflicts));
    return ExitCode.ERROR;
  } else {
    logger.info(messages.noConflictsDetected());
    return ExitCode.SUCCESS;
  }
}

export async function detectConflictsActionLogic(
  logger: TsLogger,
  _options: IGlobalProgramOptions,
  services: IServices
): Promise<ExitCode> {
  const { projectConfig, fs, configService } = services;
  const conflictMessages: string[] = [];

  const toolConfigsResult = await loadToolConfigs(logger, projectConfig, fs, configService);

  if (toolConfigsResult.exitCode !== ExitCode.SUCCESS) {
    return toolConfigsResult.exitCode;
  }

  const toolConfigsArray = toolConfigsResult.toolConfigs;

  if (toolConfigsArray.length === 0) {
    logger.info(messages.toolNoConfigurationsFound(projectConfig.paths.toolConfigsDir));
    return ExitCode.SUCCESS;
  }

  for (const toolConfig of toolConfigsArray) {
    // Check for shim conflicts
    await checkShimConflicts(logger, fs, toolConfig, projectConfig.paths.targetDir, conflictMessages);

    // Check for symlink conflicts
    await checkSymlinkConflicts(
      logger,
      fs,
      toolConfig,
      projectConfig.paths.homeDir,
      projectConfig.paths.dotfilesDir,
      conflictMessages
    );
  }

  return reportConflicts(logger, conflictMessages);
}

export function registerDetectConflictsCommand(
  parentLogger: TsLogger,
  program: IGlobalProgram,
  servicesFactory: () => Promise<IServices>
): void {
  const logger = parentLogger.getSubLogger({ name: 'registerDetectConflictsCommand' });
  program
    .command('detect-conflicts')
    .description('Detects conflicts between potential generated artifacts and existing system files.')
    .action(async () => {
      const combinedOptions = program.opts();

      let exitCode: ExitCode;
      try {
        const services = await servicesFactory();
        exitCode = await detectConflictsActionLogic(logger, combinedOptions, services);
      } catch (error) {
        logger.error(messages.commandExecutionFailed('detect-conflicts', ExitCode.ERROR), error);
        exitCode = ExitCode.ERROR;
      }

      exitCli(exitCode);
    });
}
