import type { ToolConfig } from '@dotfiles/core';
import { always } from '@dotfiles/core';
import { beforeEach, describe, expect, it } from 'bun:test';
import { createSectionHeader } from '../../shellTemplates';
import { BashGenerator } from '../BashGenerator';
import { createMockProjectConfigWithPathsOnly } from './createMockProjectConfigWithPathsOnly';

describe('BashGenerator', () => {
  let generator: BashGenerator;

  beforeEach(() => {
    generator = new BashGenerator(createMockProjectConfigWithPathsOnly());
  });

  it('should have correct shell type and file extension', () => {
    expect(generator.shellType).toBe('bash');
    expect(generator.fileExtension).toBe('.bash');
  });

  it('should process native bash syntax', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test'],
      version: '1.0.0',
      shellConfigs: {
        bash: {
          scripts: [
            always(`export TEST_VAR="value"`),
            always(`export PATH="/opt/test/bin:$PATH"`),
            always(`declare -U PATH`),
            always(`# Bash-specific completion setup`),
          ],
        },
      },
      installationMethod: 'manual',
      installParams: {},
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    // With the new branded types system, scripts are stored in alwaysScripts
    expect(content.alwaysScripts).toHaveLength(4);
    expect(content.onceScripts).toHaveLength(0);
    expect(content.environmentVariables).toHaveLength(0);
    expect(content.pathModifications).toHaveLength(0);
    expect(content.toolInit).toHaveLength(0);
  });

  it('should process completions for bash', () => {
    const completions = { source: 'test-tool.bash' };

    const result = generator.processCompletions('test-tool', completions);

    expect(result).toContain(
      '[[ -f "/home/test/.dotfiles/.generated/shell-scripts/bash/completions/test-tool.bash" ]] && source "/home/test/.dotfiles/.generated/shell-scripts/bash/completions/test-tool.bash"',
    );
  });

  it('should generate complete file content with bash syntax', () => {
    const toolContents = new Map([
      [
        'tool1',
        {
          toolInit: ['alias t1="tool1"'],
          pathModifications: ['PATH="$PATH:/opt/tool1/bin"'],
          environmentVariables: ['export TOOL1_ENV="value"'],
          completionSetup: ['[[ -f "/completions/tool1.bash" ]] && source "/completions/tool1.bash"'],
          onceScripts: [],
          alwaysScripts: [],
          functions: {},
        },
      ],
    ]);

    const content = generator.generateFileContent(toolContents);

    expect(content).toContain('# THIS FILE IS AUTOMATICALLY GENERATED');
    expect(content).toContain(createSectionHeader('bash', 'PATH Modifications'));
    expect(content).toContain('export PATH="/home/test/.local/bin:$PATH"');
    expect(content).toContain('PATH="$PATH:/opt/tool1/bin"');
    expect(content).toContain(createSectionHeader('bash', 'Environment Variables'));
    expect(content).toContain('export TOOL1_ENV="value"');
    expect(content).toContain(createSectionHeader('bash', 'Shell Completions Setup'));
    expect(content).toContain('[[ -f "/completions/tool1.bash" ]] && source "/completions/tool1.bash"');
  });

  it('should return correct default output path', () => {
    const path = generator.getDefaultOutputPath();
    expect(path).toBe('/home/test/.dotfiles/.generated/shell-scripts/main.bash');
  });

  it('should process environment variables from declarative configuration', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test-tool'],
      version: '1.0.0',
      shellConfigs: {
        bash: {
          environment: {
            TEST_TOOL_CONFIG_DIR: '/home/test/.config/test-tool',
            TEST_TOOL_DEBUG: 'true',
            TEST_TOOL_MODE: 'production',
          },
        },
      },
      installationMethod: 'manual',
      installParams: {},
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    expect(content.environmentVariables).toHaveLength(3);
    expect(content.environmentVariables).toContain('export TEST_TOOL_CONFIG_DIR="/home/test/.config/test-tool"');
    expect(content.environmentVariables).toContain('export TEST_TOOL_DEBUG="true"');
    expect(content.environmentVariables).toContain('export TEST_TOOL_MODE="production"');
  });

  it('should process aliases from declarative configuration', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test-tool'],
      version: '1.0.0',
      shellConfigs: {
        bash: {
          aliases: {
            tt: 'test-tool',
            ttd: 'test-tool --debug',
            tts: 'test-tool status',
          },
        },
      },
      installationMethod: 'manual',
      installParams: {},
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    expect(content.toolInit).toHaveLength(3);
    expect(content.toolInit).toContain('alias tt="test-tool"');
    expect(content.toolInit).toContain('alias ttd="test-tool --debug"');
    expect(content.toolInit).toContain('alias tts="test-tool status"');
  });
});
