import type { ToolConfig } from '@dotfiles/core';
import {
  isAliasEmission,
  isCompletionEmission,
  isEnvironmentEmission,
} from '@dotfiles/shell-emissions';
import { beforeEach, describe, expect, it } from 'bun:test';
import { BashGenerator } from '../BashGenerator';
import { createMockProjectConfigWithPathsOnly } from './createMockProjectConfigWithPathsOnly';

describe('BashGenerator', () => {
  let generator: BashGenerator;

  beforeEach(() => {
    generator = new BashGenerator(createMockProjectConfigWithPathsOnly());
  });

  it('should have correct shell type and file extension', () => {
    expect(generator.shellType).toBe('bash');
    expect(generator.fileExtension).toBe('.bash');
  });

  it('should return correct default output path', () => {
    const outputPath = generator.getDefaultOutputPath();
    expect(outputPath).toBe('/home/test/.dotfiles/.generated/shell-scripts/main.bash');
  });

  describe('extractEmissions', () => {
    it('should extract environment variables as emissions', () => {
      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        shellConfigs: {
          bash: {
            env: {
              MY_VAR: 'my_value',
            },
          },
        },
        installationMethod: 'manual',
        installParams: {},
      };

      const emissions = generator.extractEmissions(toolConfig);
      const envEmissions = emissions.filter(isEnvironmentEmission);

      expect(envEmissions).toHaveLength(1);
      expect(envEmissions[0]?.variables).toEqual({ MY_VAR: 'my_value' });
    });

    it('should extract aliases as emissions', () => {
      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        shellConfigs: {
          bash: {
            aliases: {
              ll: 'ls -la',
            },
          },
        },
        installationMethod: 'manual',
        installParams: {},
      };

      const emissions = generator.extractEmissions(toolConfig);
      const aliasEmissions = emissions.filter(isAliasEmission);

      expect(aliasEmissions).toHaveLength(1);
      expect(aliasEmissions[0]?.aliases).toEqual({ ll: 'ls -la' });
    });

    it('should extract completions with files instead of directories', () => {
      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        shellConfigs: {
          bash: {
            completions: { source: 'test-completion' },
          },
        },
        installationMethod: 'manual',
        installParams: {},
      };

      const emissions = generator.extractEmissions(toolConfig);
      const completionEmissions = emissions.filter(isCompletionEmission);

      expect(completionEmissions).toHaveLength(1);
      // Bash uses files, not directories
      expect(completionEmissions[0]?.files).toBeDefined();
    });

    it('should return empty array for tool with no bash config', () => {
      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        installationMethod: 'manual',
        installParams: {},
      };

      const emissions = generator.extractEmissions(toolConfig);

      expect(emissions).toHaveLength(0);
    });
  });

  describe('generateFileContent', () => {
    it('should generate valid bash file content', () => {
      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        shellConfigs: {
          bash: {
            env: { BASH_VAR: 'value' },
          },
        },
        installationMethod: 'manual',
        installParams: {},
      };

      const emissions = generator.extractEmissions(toolConfig);
      const toolEmissions = new Map([['test-tool', emissions]]);
      const content = generator.generateFileContent(toolEmissions);

      expect(content).toContain('# THIS FILE IS AUTOMATICALLY GENERATED');
      expect(content).toContain('export BASH_VAR="value"');
    });
  });
});
