import type { ToolConfig } from '@dotfiles/core';
import {
  isAliasEmission,
  isCompletionEmission,
  isEnvironmentEmission,
} from '@dotfiles/shell-emissions';
import { beforeEach, describe, expect, it } from 'bun:test';
import { PowerShellGenerator } from '../PowerShellGenerator';
import { createMockProjectConfigWithPathsOnly } from './createMockProjectConfigWithPathsOnly';

describe('PowerShellGenerator', () => {
  let generator: PowerShellGenerator;

  beforeEach(() => {
    generator = new PowerShellGenerator(createMockProjectConfigWithPathsOnly());
  });

  it('should have correct shell type and file extension', () => {
    expect(generator.shellType).toBe('powershell');
    expect(generator.fileExtension).toBe('.ps1');
  });

  it('should return correct default output path', () => {
    const outputPath = generator.getDefaultOutputPath();
    expect(outputPath).toBe('/home/test/.dotfiles/.generated/shell-scripts/main.ps1');
  });

  describe('extractEmissions', () => {
    it('should extract environment variables as emissions', () => {
      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        shellConfigs: {
          powershell: {
            environment: {
              PS_VAR: 'ps_value',
            },
          },
        },
        installationMethod: 'manual',
        installParams: {},
      };

      const emissions = generator.extractEmissions(toolConfig);
      const envEmissions = emissions.filter(isEnvironmentEmission);

      expect(envEmissions).toHaveLength(1);
      expect(envEmissions[0]?.variables).toEqual({ PS_VAR: 'ps_value' });
    });

    it('should extract aliases as emissions', () => {
      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        shellConfigs: {
          powershell: {
            aliases: {
              gci: 'Get-ChildItem',
            },
          },
        },
        installationMethod: 'manual',
        installParams: {},
      };

      const emissions = generator.extractEmissions(toolConfig);
      const aliasEmissions = emissions.filter(isAliasEmission);

      expect(aliasEmissions).toHaveLength(1);
      expect(aliasEmissions[0]?.aliases).toEqual({ gci: 'Get-ChildItem' });
    });

    it('should extract completions with files', () => {
      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        shellConfigs: {
          powershell: {
            completions: { source: 'test-completion' },
          },
        },
        installationMethod: 'manual',
        installParams: {},
      };

      const emissions = generator.extractEmissions(toolConfig);
      const completionEmissions = emissions.filter(isCompletionEmission);

      expect(completionEmissions).toHaveLength(1);
      // PowerShell uses files
      expect(completionEmissions[0]?.files).toBeDefined();
    });

    it('should return empty array for tool with no powershell config', () => {
      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        installationMethod: 'manual',
        installParams: {},
      };

      const emissions = generator.extractEmissions(toolConfig);

      expect(emissions).toHaveLength(0);
    });
  });

  describe('generateFileContent', () => {
    it('should generate valid PowerShell file content', () => {
      const toolConfig: ToolConfig = {
        name: 'test-tool',
        binaries: ['test-tool'],
        version: '1.0.0',
        shellConfigs: {
          powershell: {
            environment: { PS_VAR: 'value' },
          },
        },
        installationMethod: 'manual',
        installParams: {},
      };

      const emissions = generator.extractEmissions(toolConfig);
      const toolEmissions = new Map([['test-tool', emissions]]);
      const content = generator.generateFileContent(toolEmissions);

      expect(content).toContain('# THIS FILE IS AUTOMATICALLY GENERATED');
      expect(content).toContain('$env:PS_VAR = "value"');
    });
  });
});
