import { beforeEach, describe, expect, it } from 'bun:test';
import type { ToolConfig } from '@dotfiles/core';
import { always } from '@dotfiles/core';
import { createSectionHeader } from '../../shellTemplates';
import { PowerShellGenerator } from '../PowerShellGenerator';
import { createMockProjectConfigWithPathsOnly } from './createMockProjectConfigWithPathsOnly';

describe('PowerShellGenerator', () => {
  let generator: PowerShellGenerator;

  beforeEach(() => {
    generator = new PowerShellGenerator(createMockProjectConfigWithPathsOnly());
  });

  it('should have correct shell type and file extension', () => {
    expect(generator.shellType).toBe('powershell');
    expect(generator.fileExtension).toBe('.ps1');
  });

  it('should process native PowerShell syntax', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test'],
      version: '1.0.0',
      shellConfigs: {
        powershell: {
          scripts: [
            always`$env:TEST_VAR = "value"`,
            always`$env:PATH = "/opt/test/bin;$env:PATH"`,
            always`function test { test-tool --verbose }`,
            always`. ~/.testrc`,
          ],
        },
      },
      installationMethod: 'manual',
      installParams: {},
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    // With the new branded types system, scripts are stored in alwaysScripts
    expect(content.alwaysScripts).toHaveLength(4);
    expect(content.onceScripts).toHaveLength(0);
    expect(content.environmentVariables).toHaveLength(0);
    expect(content.pathModifications).toHaveLength(0);
    expect(content.toolInit).toHaveLength(0);
  });

  it('should process completions for PowerShell', () => {
    const completions = { source: 'test-tool.ps1' };

    const result = generator.processCompletions('test-tool', completions);

    expect(result).toContain(
      'if (Test-Path "/home/test/.dotfiles/.generated/shell-scripts/powershell/test-tool.ps1") { . "/home/test/.dotfiles/.generated/shell-scripts/powershell/test-tool.ps1" }'
    );
  });

  it('should generate complete file content with PowerShell syntax', () => {
    const toolContents = new Map([
      [
        'tool1',
        {
          toolInit: ['function t1 { tool1 }'],
          pathModifications: ['$env:PATH = "/opt/tool1/bin;$env:PATH"'],
          environmentVariables: ['$env:TOOL1_ENV = "value"'],
          completionSetup: ['if (Test-Path "/completions/tool1.ps1") { . "/completions/tool1.ps1" }'],
          onceScripts: [],
          alwaysScripts: [],
        },
      ],
    ]);

    const content = generator.generateFileContent(toolContents);

    expect(content).toContain('# THIS FILE IS AUTOMATICALLY GENERATED');
    expect(content).toContain(createSectionHeader('powershell', 'PATH Modifications'));
    expect(content).toContain('$env:PATH = "/home/test/.local/bin;$env:PATH"');
    expect(content).toContain('$env:PATH = "/opt/tool1/bin;$env:PATH"');
    expect(content).toContain(createSectionHeader('powershell', 'Environment Variables'));
    expect(content).toContain('$env:TOOL1_ENV = "value"');
    expect(content).toContain(createSectionHeader('powershell', 'Shell Completions Setup'));
    expect(content).toContain('if (Test-Path "/completions/tool1.ps1") { . "/completions/tool1.ps1" }');
  });

  it('should return correct default output path', () => {
    const path = generator.getDefaultOutputPath();
    expect(path).toBe('/home/test/.dotfiles/.generated/shell-scripts/main.ps1');
  });

  it('should process environment variables from declarative configuration', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test-tool'],
      version: '1.0.0',
      shellConfigs: {
        powershell: {
          environment: {
            TEST_TOOL_CONFIG_DIR: '/home/test/.config/test-tool',
            TEST_TOOL_DEBUG: 'true',
            TEST_TOOL_MODE: 'production',
          },
        },
      },
      installationMethod: 'manual',
      installParams: {},
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    expect(content.environmentVariables).toHaveLength(3);
    expect(content.environmentVariables).toContain('$env:TEST_TOOL_CONFIG_DIR = "/home/test/.config/test-tool"');
    expect(content.environmentVariables).toContain('$env:TEST_TOOL_DEBUG = "true"');
    expect(content.environmentVariables).toContain('$env:TEST_TOOL_MODE = "production"');
  });

  it('should process aliases from declarative configuration', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test-tool'],
      version: '1.0.0',
      shellConfigs: {
        powershell: {
          aliases: {
            tt: 'test-tool',
            ttd: 'test-tool --debug',
            tts: 'test-tool status',
          },
        },
      },
      installationMethod: 'manual',
      installParams: {},
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    expect(content.toolInit).toHaveLength(3);
    expect(content.toolInit).toContain('Set-Alias tt "test-tool"');
    expect(content.toolInit).toContain('Set-Alias ttd "test-tool --debug"');
    expect(content.toolInit).toContain('Set-Alias tts "test-tool status"');
  });
});
