import { beforeEach, describe, expect, it } from 'bun:test';
import type { ToolConfig } from '@dotfiles/core';
import { always } from '@dotfiles/core';
import { createSectionHeader } from '../../shellTemplates';
import { ZshGenerator } from '../ZshGenerator';
import { createMockProjectConfigWithPathsOnly } from './createMockProjectConfigWithPathsOnly';

describe('ZshGenerator', () => {
  let generator: ZshGenerator;

  beforeEach(() => {
    generator = new ZshGenerator(createMockProjectConfigWithPathsOnly());
  });

  it('should have correct shell type and file extension', () => {
    expect(generator.shellType).toBe('zsh');
    expect(generator.fileExtension).toBe('.zsh');
  });

  it('should extract shell content from tool config with shellConfigs', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test'],
      version: '1.0.0',
      shellConfigs: {
        zsh: {
          scripts: [
            always`export TEST_VAR="value"`,
            always`export PATH="/opt/test/bin:$PATH"`,
            always`alias test="test-tool --verbose"`,
          ],
        },
      },
      installationMethod: 'manual',
      installParams: {},
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    // With the new branded types system, scripts are stored in alwaysScripts
    expect(content.alwaysScripts).toHaveLength(3);
    expect(content.onceScripts).toHaveLength(0);
    expect(content.environmentVariables).toHaveLength(0);
    expect(content.pathModifications).toHaveLength(0);
    expect(content.toolInit).toHaveLength(0);
  });

  it('should process completions for zsh', () => {
    const completions = { source: '_test-tool' };

    const result = generator.processCompletions('test-tool', completions);

    expect(result).toContain('fpath=("/home/test/.dotfiles/.generated/shell-scripts/zsh/completions" $fpath)');
  });

  it('should generate complete file content', () => {
    const toolContents = new Map([
      [
        'tool1',
        {
          toolInit: ['alias t1="tool1"'],
          pathModifications: ['export PATH="/opt/tool1/bin:$PATH"'],
          environmentVariables: ['export TOOL1_ENV="value"'],
          completionSetup: ['fpath=("/completions/zsh" $fpath)'],
          onceScripts: [],
          alwaysScripts: [],
        },
      ],
      [
        'tool2',
        {
          toolInit: ['source ~/.tool2rc'],
          pathModifications: [],
          environmentVariables: ['export TOOL2_DEBUG=true'],
          completionSetup: [],
          onceScripts: [],
          alwaysScripts: [],
        },
      ],
    ]);

    const content = generator.generateFileContent(toolContents);

    expect(content).toContain('# THIS FILE IS AUTOMATICALLY GENERATED');
    expect(content).toContain(createSectionHeader('zsh', 'PATH Modifications'));
    expect(content).toContain('export PATH="/home/test/.local/bin:$PATH"');
    expect(content).toContain('export PATH="/opt/tool1/bin:$PATH"');
    expect(content).toContain(createSectionHeader('zsh', 'Environment Variables'));
    expect(content).toContain('export TOOL1_ENV="value"');
    expect(content).toContain('export TOOL2_DEBUG=true');
    expect(content).toContain(createSectionHeader('zsh', 'Tool-Specific Initializations'));
    expect(content).toContain('alias t1="tool1"');
    expect(content).toContain('source ~/.tool2rc');
    expect(content).toContain(createSectionHeader('zsh', 'Shell Completions Setup'));
    expect(content).toContain('typeset -U fpath');
    expect(content).toContain('fpath=("/completions/zsh" $fpath)');
    expect(content).toContain(createSectionHeader('zsh', 'End of Generated File'));
  });

  it('should return correct default output path', () => {
    const path = generator.getDefaultOutputPath();
    expect(path).toBe('/home/test/.dotfiles/.generated/shell-scripts/main.zsh');
  });

  it('should process environment variables from declarative configuration', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test-tool'],
      version: '1.0.0',
      shellConfigs: {
        zsh: {
          environment: {
            TEST_TOOL_CONFIG_DIR: '/home/test/.config/test-tool',
            TEST_TOOL_DEBUG: 'true',
            TEST_TOOL_MODE: 'production',
          },
        },
      },
      installationMethod: 'manual',
      installParams: {},
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    expect(content.environmentVariables).toHaveLength(3);
    expect(content.environmentVariables).toContain('export TEST_TOOL_CONFIG_DIR="/home/test/.config/test-tool"');
    expect(content.environmentVariables).toContain('export TEST_TOOL_DEBUG="true"');
    expect(content.environmentVariables).toContain('export TEST_TOOL_MODE="production"');
  });

  it('should process aliases from declarative configuration', () => {
    const toolConfig: ToolConfig = {
      name: 'test-tool',
      binaries: ['test-tool'],
      version: '1.0.0',
      shellConfigs: {
        zsh: {
          aliases: {
            tt: 'test-tool',
            ttd: 'test-tool --debug',
            tts: 'test-tool status',
          },
        },
      },
      installationMethod: 'manual',
      installParams: {},
    };

    const content = generator.extractShellContent('test-tool', toolConfig);

    expect(content.toolInit).toHaveLength(3);
    expect(content.toolInit).toContain('alias tt="test-tool"');
    expect(content.toolInit).toContain('alias ttd="test-tool --debug"');
    expect(content.toolInit).toContain('alias tts="test-tool status"');
  });
});
