package shim

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/alexgorbatchev/dotfiles/pkg/fs"
)

func TestGenerator_Generate(t *testing.T) {
	tests := []struct {
		name        string
		shimPath    string
		cfg         Config
		setupFS     func() fs.FS
		wantErr     bool
		wantContent string
	}{
		{
			name:     "successful generate",
			shimPath: "/home/user/bin/mytool",
			cfg: Config{
				ToolName:             "mytool",
				BinaryName:           "mytool",
				BinaryPath:           "/opt/mytool/bin/mytool",
				Sudo:                 false,
				CliCommand:           "dotfiles",
				ConfigFilePath:       "dotfiles.config.ts",
				UsageLogPath:         "usage.log",
				MissingBinaryMessage: "Custom missing msg",
			},
			setupFS: func() fs.FS {
				mem := fs.NewMemFS()
				_ = mem.MkdirAll("/home/user/bin", 0755)
				return mem
			},
			wantErr: false,
			wantContent: `#!/usr/bin/env bash
# Shim for mytool
# Generated by Dotfiles Management Tool

set -euo pipefail

TOOL_NAME="mytool"
BINARY_NAME="mytool"
TOOL_EXECUTABLE="/opt/mytool/bin/mytool"
TOOL_REQUIRES_SUDO="0"
GENERATOR_CLI_EXECUTABLE="dotfiles"
CONFIG_PATH="dotfiles.config.ts"
USAGE_LOG_PATH="usage.log"

# Prevent self-referential infinite loops
shim_self_path="${BASH_SOURCE[0]:-$0}"
if [ -n "${TOOL_EXECUTABLE:-}" ]; then
  if [ "$TOOL_EXECUTABLE" = "$shim_self_path" ] || [ "$(readlink -f "$TOOL_EXECUTABLE" 2>/dev/null)" = "$(readlink -f "$shim_self_path" 2>/dev/null)" ]; then
    echo "Error: $TOOL_NAME shim is self-referential ($TOOL_EXECUTABLE). Aborting to prevent infinite loop." >&2
    exit 1
  fi
fi

# Check for recursion
RECURSION_ENV_VAR="DOTFILES_INSTALLING_MYTOOL"`,
		},
		{
			name:     "missing shim path error",
			shimPath: "",
			cfg: Config{
				ToolName:   "mytool",
				BinaryName: "mytool",
				BinaryPath: "/opt/mytool/bin/mytool",
			},
			setupFS: func() fs.FS {
				return fs.NewMemFS()
			},
			wantErr: true,
		},
		{
			name:     "missing tool name error",
			shimPath: "/home/user/bin/mytool",
			cfg: Config{
				ToolName:   "",
				BinaryName: "mytool",
				BinaryPath: "/opt/mytool/bin/mytool",
			},
			setupFS: func() fs.FS {
				return fs.NewMemFS()
			},
			wantErr: true,
		},
		{
			name:     "missing binary name error",
			shimPath: "/home/user/bin/mytool",
			cfg: Config{
				ToolName:   "mytool",
				BinaryName: "",
				BinaryPath: "/opt/mytool/bin/mytool",
			},
			setupFS: func() fs.FS {
				return fs.NewMemFS()
			},
			wantErr: true,
		},
		{
			name:     "self referential binary path error",
			shimPath: "/home/user/bin/mytool",
			cfg: Config{
				ToolName:   "mytool",
				BinaryName: "mytool",
				BinaryPath: "/home/user/bin/mytool",
			},
			setupFS: func() fs.FS {
				return fs.NewMemFS()
			},
			wantErr: true,
		},
		{
			name:     "missing binary path error",
			shimPath: "/home/user/bin/mytool",
			cfg: Config{
				ToolName:   "mytool",
				BinaryName: "mytool",
				BinaryPath: "",
			},
			setupFS: func() fs.FS {
				return fs.NewMemFS()
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mem := tt.setupFS()
			gen := NewGenerator(mem)
			err := gen.Generate(tt.shimPath, tt.cfg)

			if (err != nil) != tt.wantErr {
				t.Fatalf("Generate() error = %v, wantErr %v", err, tt.wantErr)
			}

			if !tt.wantErr {
				bytes, err := mem.ReadFile(tt.shimPath)
				if err != nil {
					t.Fatalf("Failed to read generated shim file: %v", err)
				}
				content := string(bytes)
				// Check a key substring to verify successful generation
				if tt.wantContent != "" && content[:len(tt.wantContent)] != tt.wantContent {
					t.Errorf("Generate() content mismatch.\nGot:\n%s\nExpected to start with:\n%s", content, tt.wantContent)
				}
			}
		})
	}
}

// TestGenerator_GenerateUpdateDelegatesReporting pins that a shim's @update hands the
// whole answer to `tool update --shim-mode`. The shim cannot know whether the tool is
// pinned, already current or about to move to a new release, so a line of its own,
// such as the "Updating <tool> to latest version..." it used to print, would claim an
// update the command may refuse.
func TestGenerator_GenerateUpdateDelegatesReporting(t *testing.T) {
	mem := fs.NewMemFS()
	if err := mem.MkdirAll("/home/user/bin", 0755); err != nil {
		t.Fatalf("creating shim directory: %v", err)
	}
	cfg := Config{
		ToolName:       "mytool",
		BinaryName:     "mytool",
		BinaryPath:     "/opt/mytool/bin/mytool",
		CliCommand:     "dotfiles",
		ConfigFilePath: "dotfiles.config.ts",
		UsageLogPath:   "usage.log",
	}
	if err := NewGenerator(mem).Generate("/home/user/bin/mytool", cfg); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	content, err := mem.ReadFile("/home/user/bin/mytool")
	if err != nil {
		t.Fatalf("reading generated shim: %v", err)
	}

	const updateBranch = `if [ $# -gt 0 ] && [ "$1" = "@update" ]; then
  # tool update --shim-mode reports what became of the tool, so the shim adds nothing.
  # Use eval to properly handle GENERATOR_CLI_EXECUTABLE with spaces
  eval "$GENERATOR_CLI_EXECUTABLE" tool update --shim-mode --config '"$CONFIG_PATH"' '"$TOOL_NAME"'
  exit $?
fi`
	if !strings.Contains(string(content), updateBranch) {
		t.Errorf("generated shim's @update branch is not\n%s\n\nshim:\n%s", updateBranch, content)
	}
}

func TestGenerator_IsGeneratedShim(t *testing.T) {
	mem := fs.NewMemFS()
	_ = mem.MkdirAll("/home/user/bin", 0755)

	gen := NewGenerator(mem)

	// Case 1: File does not exist
	isShim, err := gen.IsGeneratedShim("/home/user/bin/nonexistent")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if isShim {
		t.Errorf("expected nonexistent file to not be classified as shim")
	}

	// Case 2: File exists but is not our shim
	_ = mem.WriteFile("/home/user/bin/other", []byte("#!/bin/bash\necho 123"), 0755)
	isShim, err = gen.IsGeneratedShim("/home/user/bin/other")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if isShim {
		t.Errorf("expected arbitrary script to not be classified as shim")
	}

	// Case 3: File exists and is our shim
	_ = gen.Generate("/home/user/bin/mytool", Config{
		ToolName:   "mytool",
		BinaryName: "mytool",
		BinaryPath: "/opt/mytool/bin/mytool",
	})
	isShim, err = gen.IsGeneratedShim("/home/user/bin/mytool")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if !isShim {
		t.Errorf("expected generated shim to be classified as shim")
	}

	// Case 3b: Empty 0-byte file is classified as safe-to-overwrite shim placeholder
	_ = mem.WriteFile("/home/user/bin/emptytool", []byte(""), 0755)
	isShim, err = gen.IsGeneratedShim("/home/user/bin/emptytool")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if !isShim {
		t.Errorf("expected 0-byte file to be classified as shim placeholder")
	}

	// Case 4: Symlink file without expected target
	_ = mem.Symlink("/opt/mytool/bin/mytool", "/home/user/bin/symtool")
	isShim, err = gen.IsGeneratedShim("/home/user/bin/symtool")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if isShim {
		t.Errorf("expected symlink without expected target to return false")
	}

	// Case 5: Symlink file with non-matching expected target
	isShim, err = gen.IsGeneratedShim("/home/user/bin/symtool", "/other/path")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if isShim {
		t.Errorf("expected symlink with non-matching expected target to return false")
	}

	// Case 6: Symlink file with matching expected target
	isShim, err = gen.IsGeneratedShim("/home/user/bin/symtool", "/opt/mytool/bin/mytool")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if !isShim {
		t.Errorf("expected symlink with matching expected target to return true")
	}
}

type ErroringFS struct {
	fs.FS
	errOnExists    bool
	errOnReadFile  bool
	errOnWriteFile bool
	errOnChmod     bool
	errOnReadlink  bool
}

func (e *ErroringFS) Chmod(path string, perm os.FileMode) error {
	if e.errOnChmod {
		return fmt.Errorf("mock chmod error")
	}
	return e.FS.Chmod(path, perm)
}

func (e *ErroringFS) Readlink(path string) (string, error) {
	if e.errOnReadlink {
		return "", fmt.Errorf("mock readlink error")
	}
	return e.FS.Readlink(path)
}

func (e *ErroringFS) Exists(path string) (bool, error) {
	if e.errOnExists {
		return false, fmt.Errorf("mock exists error")
	}
	return e.FS.Exists(path)
}

func (e *ErroringFS) Lstat(path string) (os.FileInfo, error) {
	if e.errOnExists {
		return nil, fmt.Errorf("mock lstat error")
	}
	return e.FS.Lstat(path)
}

func (e *ErroringFS) ReadFile(path string) ([]byte, error) {
	if e.errOnReadFile {
		return nil, fmt.Errorf("mock readfile error")
	}
	return e.FS.ReadFile(path)
}

func (e *ErroringFS) WriteFile(path string, data []byte, perm os.FileMode) error {
	if e.errOnWriteFile {
		return fmt.Errorf("mock writefile error")
	}
	return e.FS.WriteFile(path, data, perm)
}

// The shim directory and the usage-log directory are shared by every tool, so
// Generate must not create either: a caller writing through a tool-scoped tracked
// filesystem would have the directories recorded as that tool's own shims.
func TestGenerator_GenerateCreatesNoDirectories(t *testing.T) {
	cfg := Config{
		ToolName:     "mytool",
		BinaryName:   "mytool",
		BinaryPath:   "/opt/mytool/bin/mytool",
		UsageLogPath: "/home/user/.generated/usage/shim-usage.log",
	}

	t.Run("leaves the usage log directory alone", func(t *testing.T) {
		mem := fs.NewMemFS()
		_ = mem.MkdirAll("/home/user/.generated/bin", 0755)

		if err := NewGenerator(mem).Generate("/home/user/.generated/bin/mytool", cfg); err != nil {
			t.Fatalf("Generate: %v", err)
		}
		if exists, _ := mem.Exists("/home/user/.generated/usage"); exists {
			t.Error("Generate created the usage log directory; provisioning it is the caller's job")
		}
	})

	t.Run("fails when the shim directory is missing", func(t *testing.T) {
		mem := fs.NewMemFS()

		if err := NewGenerator(mem).Generate("/home/user/.generated/bin/mytool", cfg); err == nil {
			t.Fatal("expected Generate to fail when the shim directory does not exist")
		}
		if exists, _ := mem.Exists("/home/user/.generated/bin"); exists {
			t.Error("Generate created the shim directory; provisioning it is the caller's job")
		}
	})
}

func TestGenerator_Errors(t *testing.T) {
	mem := fs.NewMemFS()
	_ = mem.MkdirAll("/home/user/bin", 0755)
	cfg := Config{
		ToolName:   "mytool",
		BinaryName: "mytool",
		BinaryPath: "/opt/mytool/bin/mytool",
	}

	t.Run("Chmod error in Generate", func(t *testing.T) {
		errFS := &ErroringFS{FS: mem, errOnChmod: true}
		gen := NewGenerator(errFS)
		err := gen.Generate("/home/user/bin/mytool", cfg)
		if err == nil {
			t.Fatal("expected error on Chmod")
		}
	})

	t.Run("Readlink error in IsGeneratedShim", func(t *testing.T) {
		_ = mem.MkdirAll("/home/user/bin", 0755)
		_ = mem.Symlink("/opt/mytool/bin/mytool", "/home/user/bin/broken_symlink")

		errFS := &ErroringFS{FS: mem, errOnReadlink: true}
		gen := NewGenerator(errFS)
		isShim, err := gen.IsGeneratedShim("/home/user/bin/broken_symlink", "/opt/mytool/bin/mytool")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if isShim {
			t.Fatal("expected false on readlink error")
		}
	})

	t.Run("WriteFile error in Generate", func(t *testing.T) {
		errFS := &ErroringFS{FS: mem, errOnWriteFile: true}
		gen := NewGenerator(errFS)
		err := gen.Generate("/home/user/bin/mytool", cfg)
		if err == nil {
			t.Fatal("expected error on WriteFile")
		}
	})

	t.Run("Exists error in IsGeneratedShim", func(t *testing.T) {
		errFS := &ErroringFS{FS: mem, errOnExists: true}
		gen := NewGenerator(errFS)
		_, err := gen.IsGeneratedShim("/home/user/bin/mytool")
		if err == nil {
			t.Fatal("expected error on Exists")
		}
	})

	t.Run("ReadFile error in IsGeneratedShim", func(t *testing.T) {
		_ = mem.MkdirAll("/home/user/bin", 0755)
		_ = mem.WriteFile("/home/user/bin/mytool", []byte("some content"), 0755)

		errFS := &ErroringFS{FS: mem, errOnReadFile: true}
		gen := NewGenerator(errFS)
		_, err := gen.IsGeneratedShim("/home/user/bin/mytool")
		if err == nil {
			t.Fatal("expected error on ReadFile")
		}
	})
}

// Generating a shim that is already in place with the same content and mode is a
// no-op: the file is neither rewritten nor re-chmodded, so a repeated generate
// leaves its mtime alone. A changed configuration still rewrites it.
func TestGenerator_GenerateLeavesIdenticalShimAlone(t *testing.T) {
	dir := t.TempDir()
	shimPath := filepath.Join(dir, "bin", "mytool")
	if err := os.MkdirAll(filepath.Dir(shimPath), 0755); err != nil {
		t.Fatalf("creating shim directory: %v", err)
	}
	gen := NewGenerator(fs.NewOSFS())
	cfg := Config{
		ToolName:       "mytool",
		BinaryName:     "mytool",
		BinaryPath:     filepath.Join(dir, "binaries", "mytool", "current", "mytool"),
		CliCommand:     "dotfiles",
		ConfigFilePath: filepath.Join(dir, "dotfiles.config.ts"),
		UsageLogPath:   filepath.Join(dir, "usage", "shim-usage.log"),
	}

	if err := gen.Generate(shimPath, cfg); err != nil {
		t.Fatalf("first Generate: %v", err)
	}
	first, err := os.ReadFile(shimPath)
	if err != nil {
		t.Fatalf("reading shim: %v", err)
	}
	past := time.Date(2020, 1, 2, 3, 4, 5, 0, time.UTC)
	if err := os.Chtimes(shimPath, past, past); err != nil {
		t.Fatalf("setting mtime: %v", err)
	}

	if err := gen.Generate(shimPath, cfg); err != nil {
		t.Fatalf("second Generate: %v", err)
	}
	info, err := os.Stat(shimPath)
	if err != nil {
		t.Fatalf("stat shim: %v", err)
	}
	if !info.ModTime().Equal(past) {
		t.Errorf("an identical shim was rewritten: mtime %s, want %s", info.ModTime(), past)
	}
	if info.Mode().Perm() != 0755 {
		t.Errorf("shim mode = %v, want 0755", info.Mode().Perm())
	}
	second, _ := os.ReadFile(shimPath)
	if string(second) != string(first) {
		t.Errorf("shim content changed between identical generates")
	}

	cfg.BinaryPath = filepath.Join(dir, "elsewhere", "mytool")
	if err := gen.Generate(shimPath, cfg); err != nil {
		t.Fatalf("Generate with new binary path: %v", err)
	}
	info, _ = os.Stat(shimPath)
	if info.ModTime().Equal(past) {
		t.Errorf("a changed shim was not rewritten")
	}
	changed, _ := os.ReadFile(shimPath)
	if string(changed) == string(first) {
		t.Errorf("shim content did not follow the new binary path")
	}
}
