package shim

import (
	"fmt"
	"os"
	"testing"

	"github.com/alexgorbatchev/dotfiles/pkg/fs"
)

func TestGenerator_Generate(t *testing.T) {
	tests := []struct {
		name        string
		shimPath    string
		cfg         Config
		setupFS     func() fs.FS
		wantErr     bool
		wantContent string
	}{
		{
			name:     "successful generate",
			shimPath: "/home/user/bin/mytool",
			cfg: Config{
				ToolName:             "mytool",
				BinaryName:           "mytool",
				BinaryPath:           "/opt/mytool/bin/mytool",
				Sudo:                 false,
				CliCommand:           "dotfiles",
				ConfigFilePath:       "dotfiles.config.ts",
				UsageLogPath:         "usage.log",
				MissingBinaryMessage: "Custom missing msg",
			},
			setupFS: func() fs.FS {
				return fs.NewMemFS()
			},
			wantErr: false,
			wantContent: `#!/usr/bin/env bash
# Shim for mytool
# Generated by Dotfiles Management Tool

set -euo pipefail

TOOL_NAME="mytool"
BINARY_NAME="mytool"
TOOL_EXECUTABLE="/opt/mytool/bin/mytool"
TOOL_REQUIRES_SUDO="0"
GENERATOR_CLI_EXECUTABLE="dotfiles"
CONFIG_PATH="dotfiles.config.ts"
USAGE_LOG_PATH="usage.log"

# Check for recursion
RECURSION_ENV_VAR="DOTFILES_INSTALLING_MYTOOL"`,
		},
		{
			name:     "missing shim path error",
			shimPath: "",
			cfg: Config{
				ToolName:   "mytool",
				BinaryName: "mytool",
				BinaryPath: "/opt/mytool/bin/mytool",
			},
			setupFS: func() fs.FS {
				return fs.NewMemFS()
			},
			wantErr: true,
		},
		{
			name:     "missing tool name error",
			shimPath: "/home/user/bin/mytool",
			cfg: Config{
				ToolName:   "",
				BinaryName: "mytool",
				BinaryPath: "/opt/mytool/bin/mytool",
			},
			setupFS: func() fs.FS {
				return fs.NewMemFS()
			},
			wantErr: true,
		},
		{
			name:     "missing binary name error",
			shimPath: "/home/user/bin/mytool",
			cfg: Config{
				ToolName:   "mytool",
				BinaryName: "",
				BinaryPath: "/opt/mytool/bin/mytool",
			},
			setupFS: func() fs.FS {
				return fs.NewMemFS()
			},
			wantErr: true,
		},
		{
			name:     "missing binary path error",
			shimPath: "/home/user/bin/mytool",
			cfg: Config{
				ToolName:   "mytool",
				BinaryName: "mytool",
				BinaryPath: "",
			},
			setupFS: func() fs.FS {
				return fs.NewMemFS()
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mem := tt.setupFS()
			gen := NewGenerator(mem)
			err := gen.Generate(tt.shimPath, tt.cfg)

			if (err != nil) != tt.wantErr {
				t.Fatalf("Generate() error = %v, wantErr %v", err, tt.wantErr)
			}

			if !tt.wantErr {
				bytes, err := mem.ReadFile(tt.shimPath)
				if err != nil {
					t.Fatalf("Failed to read generated shim file: %v", err)
				}
				content := string(bytes)
				// Check a key substring to verify successful generation
				if tt.wantContent != "" && content[:len(tt.wantContent)] != tt.wantContent {
					t.Errorf("Generate() content mismatch.\nGot:\n%s\nExpected to start with:\n%s", content, tt.wantContent)
				}
			}
		})
	}
}

func TestGenerator_IsGeneratedShim(t *testing.T) {
	mem := fs.NewMemFS()
	_ = mem.MkdirAll("/home/user/bin", 0755)

	gen := NewGenerator(mem)

	// Case 1: File does not exist
	isShim, err := gen.IsGeneratedShim("/home/user/bin/nonexistent")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if isShim {
		t.Errorf("expected nonexistent file to not be classified as shim")
	}

	// Case 2: File exists but is not our shim
	_ = mem.WriteFile("/home/user/bin/other", []byte("#!/bin/bash\necho 123"), 0755)
	isShim, err = gen.IsGeneratedShim("/home/user/bin/other")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if isShim {
		t.Errorf("expected arbitrary script to not be classified as shim")
	}

	// Case 3: File exists and is our shim
	_ = gen.Generate("/home/user/bin/mytool", Config{
		ToolName:   "mytool",
		BinaryName: "mytool",
		BinaryPath: "/opt/mytool/bin/mytool",
	})
	isShim, err = gen.IsGeneratedShim("/home/user/bin/mytool")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if !isShim {
		t.Errorf("expected generated shim to be classified as shim")
	}

	// Case 4: Symlink file without expected target
	_ = mem.Symlink("/opt/mytool/bin/mytool", "/home/user/bin/symtool")
	isShim, err = gen.IsGeneratedShim("/home/user/bin/symtool")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if isShim {
		t.Errorf("expected symlink without expected target to return false")
	}

	// Case 5: Symlink file with non-matching expected target
	isShim, err = gen.IsGeneratedShim("/home/user/bin/symtool", "/other/path")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if isShim {
		t.Errorf("expected symlink with non-matching expected target to return false")
	}

	// Case 6: Symlink file with matching expected target
	isShim, err = gen.IsGeneratedShim("/home/user/bin/symtool", "/opt/mytool/bin/mytool")
	if err != nil {
		t.Fatalf("IsGeneratedShim failed: %v", err)
	}
	if !isShim {
		t.Errorf("expected symlink with matching expected target to return true")
	}
}

type ErroringFS struct {
	fs.FS
	errOnExists    bool
	errOnReadFile  bool
	errOnWriteFile bool
	errOnMkdirAll  bool
	errOnChmod     bool
	errOnReadlink  bool
}

func (e *ErroringFS) Chmod(path string, perm os.FileMode) error {
	if e.errOnChmod {
		return fmt.Errorf("mock chmod error")
	}
	return e.FS.Chmod(path, perm)
}

func (e *ErroringFS) Readlink(path string) (string, error) {
	if e.errOnReadlink {
		return "", fmt.Errorf("mock readlink error")
	}
	return e.FS.Readlink(path)
}

func (e *ErroringFS) Exists(path string) (bool, error) {
	if e.errOnExists {
		return false, fmt.Errorf("mock exists error")
	}
	return e.FS.Exists(path)
}

func (e *ErroringFS) Lstat(path string) (os.FileInfo, error) {
	if e.errOnExists {
		return nil, fmt.Errorf("mock lstat error")
	}
	return e.FS.Lstat(path)
}

func (e *ErroringFS) ReadFile(path string) ([]byte, error) {
	if e.errOnReadFile {
		return nil, fmt.Errorf("mock readfile error")
	}
	return e.FS.ReadFile(path)
}

func (e *ErroringFS) WriteFile(path string, data []byte, perm os.FileMode) error {
	if e.errOnWriteFile {
		return fmt.Errorf("mock writefile error")
	}
	return e.FS.WriteFile(path, data, perm)
}

func (e *ErroringFS) MkdirAll(path string, perm os.FileMode) error {
	if e.errOnMkdirAll {
		return fmt.Errorf("mock mkdirall error")
	}
	return e.FS.MkdirAll(path, perm)
}

func TestGenerator_Errors(t *testing.T) {
	mem := fs.NewMemFS()
	cfg := Config{
		ToolName:   "mytool",
		BinaryName: "mytool",
		BinaryPath: "/opt/mytool/bin/mytool",
	}

	t.Run("UsageLogPath MkdirAll error in Generate", func(t *testing.T) {
		errFS := &ErroringFS{FS: mem, errOnMkdirAll: true}
		gen := NewGenerator(errFS)
		cfgWithLog := cfg
		cfgWithLog.UsageLogPath = "/home/user/logs/usage.log"
		err := gen.Generate("/home/user/bin/mytool", cfgWithLog)
		if err == nil {
			t.Fatal("expected error on UsageLogPath MkdirAll")
		}
	})

	t.Run("Chmod error in Generate", func(t *testing.T) {
		errFS := &ErroringFS{FS: mem, errOnChmod: true}
		gen := NewGenerator(errFS)
		err := gen.Generate("/home/user/bin/mytool", cfg)
		if err == nil {
			t.Fatal("expected error on Chmod")
		}
	})

	t.Run("Readlink error in IsGeneratedShim", func(t *testing.T) {
		_ = mem.MkdirAll("/home/user/bin", 0755)
		_ = mem.Symlink("/opt/mytool/bin/mytool", "/home/user/bin/broken_symlink")

		errFS := &ErroringFS{FS: mem, errOnReadlink: true}
		gen := NewGenerator(errFS)
		isShim, err := gen.IsGeneratedShim("/home/user/bin/broken_symlink", "/opt/mytool/bin/mytool")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if isShim {
			t.Fatal("expected false on readlink error")
		}
	})

	t.Run("WriteFile error in Generate", func(t *testing.T) {
		errFS := &ErroringFS{FS: mem, errOnWriteFile: true}
		gen := NewGenerator(errFS)
		err := gen.Generate("/home/user/bin/mytool", cfg)
		if err == nil {
			t.Fatal("expected error on WriteFile")
		}
	})

	t.Run("Exists error in IsGeneratedShim", func(t *testing.T) {
		errFS := &ErroringFS{FS: mem, errOnExists: true}
		gen := NewGenerator(errFS)
		_, err := gen.IsGeneratedShim("/home/user/bin/mytool")
		if err == nil {
			t.Fatal("expected error on Exists")
		}
	})

	t.Run("ReadFile error in IsGeneratedShim", func(t *testing.T) {
		_ = mem.MkdirAll("/home/user/bin", 0755)
		_ = mem.WriteFile("/home/user/bin/mytool", []byte("some content"), 0755)

		errFS := &ErroringFS{FS: mem, errOnReadFile: true}
		gen := NewGenerator(errFS)
		_, err := gen.IsGeneratedShim("/home/user/bin/mytool")
		if err == nil {
			t.Fatal("expected error on ReadFile")
		}
	})
}
