package shim

import (
	"bytes"
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/alexgorbatchev/dotfiles/pkg/fs"
)

//go:embed shim.tmpl
var shimTemplateStr string

var shimTemplate = template.Must(template.New("shim").Parse(shimTemplateStr))

// Generator manages creation and identification of wrapper script shims.
type Generator struct {
	fs fs.FS
}

// NewGenerator creates a new Generator instance.
func NewGenerator(f fs.FS) *Generator {
	return &Generator{fs: f}
}

// Config represents parameters for the generated executable shim.
type Config struct {
	ToolName             string
	BinaryName           string
	BinaryPath           string
	Sudo                 bool
	CliCommand           string
	ConfigFilePath       string
	UsageLogPath         string
	MissingBinaryMessage string
}

// Generate creates an executable shell wrapper shim script at the given path.
func (g *Generator) Generate(shimPath string, cfg Config) error {
	if shimPath == "" {
		return fmt.Errorf("shim path must not be empty")
	}
	if cfg.ToolName == "" {
		return fmt.Errorf("tool name must not be empty")
	}
	if cfg.BinaryName == "" {
		return fmt.Errorf("binary name must not be empty")
	}
	if cfg.BinaryPath == "" {
		return fmt.Errorf("binary path must not be empty")
	}

	envVarSuffix := strings.ToUpper(cfg.ToolName)
	var cleanVar strings.Builder
	for _, r := range envVarSuffix {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			cleanVar.WriteRune(r)
		} else {
			cleanVar.WriteRune('_')
		}
	}
	envVarSuffix = cleanVar.String()

	missingBinaryCmd := "echo \"Installation completed but binary not found at: $TOOL_EXECUTABLE\" >&2"
	if cfg.MissingBinaryMessage != "" {
		escapedMsg := strings.ReplaceAll(cfg.MissingBinaryMessage, "\"", "\\\"")
		missingBinaryCmd = fmt.Sprintf("echo %q >&2", escapedMsg)
	}

	type templateData struct {
		Config
		EnvVarSuffix     string
		MissingBinaryCmd string
	}

	data := templateData{
		Config:           cfg,
		EnvVarSuffix:     envVarSuffix,
		MissingBinaryCmd: missingBinaryCmd,
	}

	var buf bytes.Buffer
	if err := shimTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing shim template: %w", err)
	}

	if cfg.UsageLogPath != "" {
		usageLogDir := filepath.Dir(cfg.UsageLogPath)
		if usageLogDir != "." && usageLogDir != "/" {
			if err := g.fs.MkdirAll(usageLogDir, 0755); err != nil {
				return fmt.Errorf("creating usage log directory: %w", err)
			}
		}
	}

	parentDir := filepath.Dir(shimPath)
	if parentDir != "." && parentDir != "/" {
		if err := g.fs.MkdirAll(parentDir, 0755); err != nil {
			return fmt.Errorf("creating parent directory: %w", err)
		}
	}

	_ = g.fs.Remove(shimPath)
	if err := g.fs.WriteFile(shimPath, buf.Bytes(), 0666); err != nil {
		return fmt.Errorf("writing shim: %w", err)
	}
	if err := g.fs.Chmod(shimPath, 0755); err != nil {
		return fmt.Errorf("setting shim permissions: %w", err)
	}

	return nil
}

// IsGeneratedShim checks if the file at path is a shim script generated by us (or a 0-byte placeholder).
// If shimPath is a symbolic link, it returns true if expectedSymlinkTarget is provided and matches the link target.
func (g *Generator) IsGeneratedShim(shimPath string, expectedSymlinkTarget ...string) (bool, error) {
	st, err := g.fs.Lstat(shimPath)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("checking file stats: %w", err)
	}

	if st.Mode()&os.ModeSymlink != 0 {
		if len(expectedSymlinkTarget) == 0 || expectedSymlinkTarget[0] == "" {
			return false, nil
		}
		target, err := g.fs.Readlink(shimPath)
		if err != nil {
			return false, nil
		}
		return target == expectedSymlinkTarget[0], nil
	}

	if st.Size() == 0 {
		return true, nil
	}

	bytes, err := g.fs.ReadFile(shimPath)
	if err != nil {
		return false, fmt.Errorf("reading file: %w", err)
	}

	content := string(bytes)
	return strings.Contains(content, "# Generated by Dotfiles Management Tool"), nil
}
