import { dedentString } from "@dotfiles/utils";
import { CONFIG_FILE_NAME, ENV_DIR_VAR, ENV_NAME_VAR } from "./constants";

/**
 * Generates the PowerShell activation script content for a virtual environment.
 *
 * The script:
 * - Sets DOTFILES_ENV_DIR to the absolute path of the environment
 * - Sets DOTFILES_ENV_NAME to the environment name
 * - Provides a dotfiles-deactivate function to clean up
 * - Handles re-activation by deactivating first
 *
 * @param envDir - Absolute path to the environment directory
 * @param envName - Name of the environment
 * @returns PowerShell script content as a string
 */
export function generatePowerShellSourceScript(envDir: string, envName: string): string {
  return dedentString(`
    # ==============================================================================
    # Dotfiles Virtual Environment Activation Script (PowerShell)
    # ==============================================================================
    # This file is automatically generated. Do not edit directly.
    #
    # Usage:
    #   . .\\${envName}\\source.ps1
    #   . ${envName}/source.ps1
    #
    # To deactivate:
    #   dotfiles-deactivate
    # ==============================================================================

    function global:dotfiles-deactivate {
      if ($env:${ENV_DIR_VAR}) {
        # Restore original XDG_CONFIG_HOME
        if ($env:_DOTFILES_OLD_XDG_CONFIG_HOME) {
          $env:XDG_CONFIG_HOME = $env:_DOTFILES_OLD_XDG_CONFIG_HOME
          Remove-Item Env:_DOTFILES_OLD_XDG_CONFIG_HOME -ErrorAction SilentlyContinue
        } else {
          Remove-Item Env:XDG_CONFIG_HOME -ErrorAction SilentlyContinue
        }
        Remove-Item Env:${ENV_DIR_VAR} -ErrorAction SilentlyContinue
        Remove-Item Env:${ENV_NAME_VAR} -ErrorAction SilentlyContinue
        Remove-Item Function:dotfiles-deactivate -ErrorAction SilentlyContinue
        Write-Host "Deactivated dotfiles environment"
      }
    }

    # If already active, deactivate first
    if ($env:${ENV_DIR_VAR}) {
      dotfiles-deactivate
    }

    # Resolve the directory containing this script
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    if (-not $scriptDir) {
      # Fallback to hardcoded path
      $scriptDir = "${envDir}"
    }

    # Save old XDG_CONFIG_HOME for restoration on deactivate
    if ($env:XDG_CONFIG_HOME) {
      $env:_DOTFILES_OLD_XDG_CONFIG_HOME = $env:XDG_CONFIG_HOME
    }

    # Export environment variables
    $env:${ENV_DIR_VAR} = $scriptDir
    $env:${ENV_NAME_VAR} = "${envName}"
    $env:XDG_CONFIG_HOME = "$scriptDir\\.config"

    Write-Host "Activated dotfiles environment: ${envName}"
    Write-Host "  Directory: $env:${ENV_DIR_VAR}"
    Write-Host "  Config: $env:${ENV_DIR_VAR}\\${CONFIG_FILE_NAME}"
  `);
}
