import { dedentString } from '@dotfiles/utils';
import { CONFIG_FILE_NAME, ENV_DIR_VAR, ENV_NAME_VAR } from './constants';

/**
 * Generates the shell activation script content for a virtual environment.
 *
 * The script:
 * - Sets DOTFILES_ENV_DIR to the absolute path of the environment
 * - Sets DOTFILES_ENV_NAME to the environment name
 * - Provides a dotfiles-deactivate function to clean up
 * - Handles re-activation by deactivating first
 *
 * @param envDir - Absolute path to the environment directory
 * @param envName - Name of the environment
 * @returns Shell script content as a string
 */
export function generateSourceScript(envDir: string, envName: string): string {
  // Use a heredoc-style approach for better readability
  return dedentString(`
    #!/bin/sh
    # ==============================================================================
    # Dotfiles Virtual Environment Activation Script
    # ==============================================================================
    # This file is automatically generated. Do not edit directly.
    #
    # Usage:
    #   source ${envName}/source
    #   . ./${envName}/source
    #
    # To deactivate:
    #   dotfiles-deactivate
    # ==============================================================================

    # Deactivate function to clean up environment
    dotfiles-deactivate() {
      if [ -n "\${${ENV_DIR_VAR}:-}" ]; then
        # Restore original XDG_CONFIG_HOME
        if [ -n "\${_DOTFILES_OLD_XDG_CONFIG_HOME:-}" ]; then
          export XDG_CONFIG_HOME="\${_DOTFILES_OLD_XDG_CONFIG_HOME}"
          unset _DOTFILES_OLD_XDG_CONFIG_HOME
        else
          unset XDG_CONFIG_HOME
        fi
        unset ${ENV_DIR_VAR}
        unset ${ENV_NAME_VAR}
        unset -f dotfiles-deactivate 2>/dev/null
        echo "Deactivated dotfiles environment"
      fi
    }

    # If already active, deactivate first
    if [ -n "\${${ENV_DIR_VAR}:-}" ]; then
      dotfiles-deactivate
    fi

    # Resolve the directory containing this script
    # Support both sourced and direct execution
    if [ -n "\${BASH_SOURCE[0]:-}" ]; then
      _dotfiles_script_dir="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
    elif [ -n "\${ZSH_VERSION:-}" ]; then
      _dotfiles_script_dir="$(cd "$(dirname "\${(%):-%x}")" && pwd)"
    else
      # Fallback to the hardcoded path
      _dotfiles_script_dir="${envDir}"
    fi

    # Save old XDG_CONFIG_HOME for restoration on deactivate
    if [ -n "\${XDG_CONFIG_HOME:-}" ]; then
      export _DOTFILES_OLD_XDG_CONFIG_HOME="\${XDG_CONFIG_HOME}"
    fi

    # Export environment variables
    export ${ENV_DIR_VAR}="\${_dotfiles_script_dir}"
    export ${ENV_NAME_VAR}="${envName}"
    export XDG_CONFIG_HOME="\${_dotfiles_script_dir}/.config"

    # Clean up temporary variable
    unset _dotfiles_script_dir

    echo "Activated dotfiles environment: ${envName}"
    echo "  Directory: \${${ENV_DIR_VAR}}"
    echo "  Config: \${${ENV_DIR_VAR}}/${CONFIG_FILE_NAME}"
  `);
}
