import type { YamlConfig } from '@modules/config';
import { createYamlConfigFromObject, } from '@modules/config-loader';
import type { IFileSystem } from '@modules/file-system';
import { TestLogger, createMemFileSystem } from '@testing-helpers';
import type { ToolConfig } from '@types';
import { beforeEach, describe, expect, it } from 'bun:test';
import path from 'node:path';
import type { IShellInitGenerator } from '../IShellInitGenerator';
import { ShellInitGenerator } from '../ShellInitGenerator';

describe('ShellInitGenerator', () => {
  let mockFileSystem: IFileSystem;
  let mockAppConfig: YamlConfig;
  let generator: IShellInitGenerator;
  let logger: TestLogger;

  const DEFAULT_COMPLETIONS_DIR = '/test/home/.dotfiles/.generated/completions';
  const DEFAULT_BIN_DIR = '/test/home/.dotfiles/.generated/bin';
  const DEFAULT_DOTFILES_DIR = '/test/home/.dotfiles';

  beforeEach(async () => {
    const { fs } = await createMemFileSystem({});
    mockFileSystem = fs;
    logger = new TestLogger();
    mockAppConfig = await createYamlConfigFromObject(
      logger,
      fs,
      {
        paths: {
          dotfilesDir: DEFAULT_DOTFILES_DIR, // Keep specific for test consistency
          completionsDir: DEFAULT_COMPLETIONS_DIR,
          binariesDir: DEFAULT_BIN_DIR,
          generatedDir: path.join(DEFAULT_DOTFILES_DIR, '.generated'), // Ensure consistency
        },
      },
      { platform: 'linux', arch: 'x64', homeDir: '/home/test' },
      {}
    );
    generator = new ShellInitGenerator(logger, mockFileSystem, mockAppConfig);
  });

  const getExpectedHeader = (dotfilesDir: string) => [
    '# ==========================================================================',
    '# THIS FILE IS AUTOMATICALLY GENERATED BY THE DOTFILES MANAGEMENT TOOL',
    '# DO NOT EDIT THIS FILE DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN',
    '# ==========================================================================',
    '',
    `# Generated on: ${expect.any(String)}`, // Date will vary
    `# Dotfiles directory: ${dotfilesDir}`,
    '',
  ];

  const getExpectedFooter = () => ['# === End of Generated File ===\n'];

  it('should generate a basic init file with no tool configs and return its path', async () => {
    const expectedPath = path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh');
    const resultPath = await generator.generate({});
    expect(resultPath).toBe(expectedPath);

    const content = await mockFileSystem.readFile(expectedPath);

    const expectedContent = [
      ...getExpectedHeader(DEFAULT_DOTFILES_DIR),
      '# === PATH Modifications ===',
      `export PATH="${DEFAULT_BIN_DIR}:$PATH"`,
      '\n\n', // two \n from path section's \n\n, then footer adds one more before its content
      ...getExpectedFooter(),
    ].join('\n');

    expect(
      content.replace(/# Generated on: .*?\n/, `# Generated on: ${expect.any(String)}\n`)
    ).toBe(expectedContent);
    expect(mockFileSystem.ensureDir).toHaveBeenCalledWith(DEFAULT_COMPLETIONS_DIR);
  });

  it('should use custom output path if provided and return it', async () => {
    const customPath = '/custom/path/to/my-init.zsh';
    const resultPath = await generator.generate({}, { outputPath: customPath });
    expect(resultPath).toBe(customPath);
    expect(mockFileSystem.writeFile).toHaveBeenCalledWith(customPath, expect.any(String));
    expect(mockFileSystem.ensureDir).toHaveBeenCalledWith('/custom/path/to');
  });

  it('should attempt file operations and return path (simulating dry run with MemFS)', async () => {
    // With the refactor, ShellInitGenerator always attempts to write.
    // The "dry run" nature comes from the IFileSystem implementation (MemFileSystem here).
    const toolConfigs: Record<string, ToolConfig> = {
      testTool: {
        name: 'testTool',
        binaries: ['tt'],
        version: '1.0.0',
        zshInit: ['export TEST_TOOL_VAR="hello"'],
        installationMethod: 'none',
        installParams: undefined,
      },
    };
    const expectedPath = path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh');
    // No dryRun option passed to generate
    const resultPath = await generator.generate(toolConfigs, {});
    expect(resultPath).toBe(expectedPath);

    // It should now ATTEMPT to write, and MemFileSystem will capture it.
    expect(mockFileSystem.ensureDir).toHaveBeenCalledWith(DEFAULT_COMPLETIONS_DIR);
    expect(mockFileSystem.writeFile).toHaveBeenCalledWith(
      expectedPath,
      expect.stringContaining('export TEST_TOOL_VAR="hello"')
    );

    // Verify content in MemFileSystem
    const content = await mockFileSystem.readFile(expectedPath);
    expect(content).toContain('export TEST_TOOL_VAR="hello"');
  });

  it('should include PATH modifications from tool configs', async () => {
    const toolConfigs: Record<string, ToolConfig> = {
      toolA: {
        name: 'toolA',
        binaries: ['ta'],
        version: '1.0',
        zshInit: ['export PATH="/opt/toolA/bin:$PATH"'],
        installationMethod: 'none',
        installParams: undefined,
      },
      toolB: {
        name: 'toolB',
        binaries: ['tb'],
        version: '1.0',
        zshInit: ['path+=("/opt/toolB/bin")'],
        installationMethod: 'none',
        installParams: undefined,
      },
    };
    const resultPath = await generator.generate(toolConfigs);
    expect(resultPath).toBe(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));
    const content = await mockFileSystem.readFile(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));

    expect(content).toContain('# === PATH Modifications ===');
    expect(content).toContain(`export PATH="${DEFAULT_BIN_DIR}:$PATH"`);
    expect(content).toContain('export PATH="/opt/toolA/bin:$PATH"');
    expect(content).toContain('path+=("/opt/toolB/bin")');
  });

  it('should include environment variables from tool configs', async () => {
    const toolConfigs: Record<string, ToolConfig> = {
      toolA: {
        name: 'toolA',
        binaries: ['ta'],
        version: '1.0',
        zshInit: ['export TOOL_A_ENABLED=true'],
        installationMethod: 'none',
        installParams: undefined,
      },
      toolB: {
        name: 'toolB',
        binaries: ['tb'],
        version: '1.0',
        zshInit: ['export TOOL_B_MODE="debug"'],
        installationMethod: 'none',
        installParams: undefined,
      },
    };
    const resultPath = await generator.generate(toolConfigs);
    expect(resultPath).toBe(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));
    const content = await mockFileSystem.readFile(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));

    expect(content).toContain('# === Environment Variables ===');
    expect(content).toContain('export TOOL_A_ENABLED=true');
    expect(content).toContain('export TOOL_B_MODE="debug"');
  });

  it('should include tool-specific initializations from zshInit', async () => {
    const toolConfigs: Record<string, ToolConfig> = {
      toolA: {
        name: 'toolA',
        binaries: ['ta'],
        version: '1.0',
        zshInit: ['alias ta="toolA --extended"'],
        installationMethod: 'none',
        installParams: undefined,
      },
      toolB: {
        name: 'toolB',
        binaries: ['tb'],
        version: '1.0',
        zshInit: ['source /opt/toolB/init.sh'],
        installationMethod: 'none',
        installParams: undefined,
      },
    };
    const resultPath = await generator.generate(toolConfigs);
    expect(resultPath).toBe(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));
    const content = await mockFileSystem.readFile(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));

    expect(content).toContain('# === Tool-Specific Initializations ===');
    expect(content).toContain('# --- toolA ---');
    expect(content).toContain('alias ta="toolA --extended"');
    expect(content).toContain('# --- toolB ---');
    expect(content).toContain('source /opt/toolB/init.sh');
  });

  it('should set up Zsh completions correctly', async () => {
    const toolConfigs: Record<string, ToolConfig> = {
      toolA: {
        name: 'toolA',
        binaries: ['ta'],
        version: '1.0',
        completions: {
          zsh: { source: 'completion/toolA.zsh', name: '_toolA_custom' },
        },
        installationMethod: 'none',
        installParams: undefined,
      },
      toolB: {
        name: 'toolB',
        binaries: ['tb'],
        version: '1.0',
        completions: {
          zsh: { source: 'completions/_toolB' }, // Default name _toolB
        },
        installationMethod: 'none',
        installParams: undefined,
      },
    };
    const resultPath = await generator.generate(toolConfigs);
    expect(resultPath).toBe(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));
    const content = await mockFileSystem.readFile(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));

    expect(content).toContain('# === Shell Completions Setup ===');
    expect(content).toContain('typeset -U fpath');
    expect(content).toContain(
      `fpath=(${JSON.stringify(path.join(DEFAULT_COMPLETIONS_DIR, 'zsh'))} $fpath)`
    );
  });

  it('should not add "typeset -U fpath" if fpath is already managed in zshInit', async () => {
    const toolConfigs: Record<string, ToolConfig> = {
      toolA: {
        name: 'toolA',
        binaries: ['ta'],
        version: '1.0',
        zshInit: ['typeset -U fpath', 'fpath=("/my/custom/fpath" $fpath)'],
        completions: { zsh: { source: '_toolA' } },
        installationMethod: 'none',
        installParams: undefined,
      },
    };
    const resultPath = await generator.generate(toolConfigs);
    expect(resultPath).toBe(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));
    const content = await mockFileSystem.readFile(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));

    const occurrences = (content.match(/typeset -U fpath/g) || []).length;
    expect(occurrences).toBe(1);
    expect(content).toContain('typeset -U fpath');
    expect(content).toContain('fpath=("/my/custom/fpath" $fpath)');
    // The completion specific fpath add should still be there for its own directory
    expect(content).toContain(
      `fpath=(${JSON.stringify(path.join(DEFAULT_COMPLETIONS_DIR, 'zsh'))} $fpath)`
    );
  });

  it('should handle mixed configurations for multiple tools', async () => {
    const toolConfigs: Record<string, ToolConfig> = {
      alpha: {
        name: 'alpha',
        binaries: ['a'],
        version: '1.0',
        zshInit: ['export ALPHA_MODE=on', 'export PATH="/opt/alpha/bin:$PATH"'],
        completions: { zsh: { source: '_alpha' } },
        installationMethod: 'none',
        installParams: undefined,
      },
      beta: {
        name: 'beta',
        binaries: ['b'],
        version: '2.1',
        zshInit: ['alias b="beta -v"'],
        installationMethod: 'none',
        installParams: undefined,
      },
      gamma: {
        name: 'gamma',
        binaries: ['g'],
        version: '0.5',
        completions: {
          zsh: { source: 'gamma_completion.sh', targetDir: '/usr/local/share/zsh/site-functions' },
        },
        zshInit: ['export GAMMA_LEVEL=5'],
        installationMethod: 'none',
        installParams: undefined,
      },
    };
    const resultPath = await generator.generate(toolConfigs);
    expect(resultPath).toBe(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));
    const content = await mockFileSystem.readFile(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));

    // PATH
    expect(content).toContain('export PATH="/opt/alpha/bin:$PATH"');
    expect(content).toContain(`export PATH="${DEFAULT_BIN_DIR}:$PATH"`);

    // Env Vars
    expect(content).toContain('export ALPHA_MODE=on');
    expect(content).toContain('export GAMMA_LEVEL=5');

    // Tool Inits
    expect(content).toContain('# --- alpha ---');
    expect(content).toContain('# --- beta ---');
    expect(content).toContain('alias b="beta -v"');
    expect(content).toContain('# --- gamma ---');

    // Completions
    expect(content).toContain('typeset -U fpath');
    expect(content).toContain(
      `fpath=(${JSON.stringify(path.join(DEFAULT_COMPLETIONS_DIR, 'zsh'))} $fpath)`
    ); // For alpha
    expect(content).toContain(
      `fpath=(${JSON.stringify('/usr/local/share/zsh/site-functions')} $fpath)`
    ); // For gamma
  });

  it('should correctly order the sections', async () => {
    const toolConfigs: Record<string, ToolConfig> = {
      myTool: {
        name: 'myTool',
        binaries: ['mt'],
        version: '1.0',
        zshInit: [
          'export MY_VAR=123',
          'export PATH="/opt/mytool/bin:$PATH"',
          'alias mt="myTool --doit"',
        ],
        completions: { zsh: { source: '_myTool' } },
        installationMethod: 'none',
        installParams: undefined,
      },
    };
    const resultPath = await generator.generate(toolConfigs);
    expect(resultPath).toBe(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));
    const content = await mockFileSystem.readFile(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));

    const pathSectionIndex = content.indexOf('# === PATH Modifications ===');
    const envSectionIndex = content.indexOf('# === Environment Variables ===');
    const initSectionIndex = content.indexOf('# === Tool-Specific Initializations ===');
    const compSectionIndex = content.indexOf('# === Shell Completions Setup ===');

    expect(pathSectionIndex).toBeGreaterThan(-1);
    expect(envSectionIndex).toBeGreaterThan(-1);
    expect(initSectionIndex).toBeGreaterThan(-1);
    expect(compSectionIndex).toBeGreaterThan(-1);

    expect(pathSectionIndex).toBeLessThan(envSectionIndex);
    expect(envSectionIndex).toBeLessThan(initSectionIndex);
    expect(initSectionIndex).toBeLessThan(compSectionIndex);
  });

  it('should deduplicate identical lines within sections', async () => {
    const toolConfigs: Record<string, ToolConfig> = {
      toolA: {
        name: 'toolA',
        binaries: ['ta'],
        version: '1.0',
        zshInit: ['export DUP_VAR="val"', 'export PATH="/dup/path:$PATH"'],
        installationMethod: 'none',
        installParams: undefined,
      },
      toolB: {
        name: 'toolB',
        binaries: ['tb'],
        version: '1.0',
        zshInit: ['export DUP_VAR="val"', 'export PATH="/dup/path:$PATH"'],
        installationMethod: 'none',
        installParams: undefined,
      },
    };
    const resultPath = await generator.generate(toolConfigs);
    expect(resultPath).toBe(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));
    const content = await mockFileSystem.readFile(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));

    // Count occurrences
    expect((content.match(/export DUP_VAR="val"/g) || []).length).toBe(1);
    expect((content.match(/export PATH="\/dup\/path:\$PATH"/g) || []).length).toBe(1);
  });

  it('should handle tool config being undefined in the input record gracefully', async () => {
    const toolConfigs: Record<string, ToolConfig | undefined> = {
      toolA: {
        name: 'toolA',
        binaries: ['ta'],
        version: '1.0',
        zshInit: ['export TOOL_A_VAR="set"'],
        installationMethod: 'none',
        installParams: undefined,
      },
      toolB: undefined, // This tool's config is undefined
      toolC: {
        name: 'toolC',
        binaries: ['tc'],
        version: '1.0',
        zshInit: ['export TOOL_C_VAR="active"'],
        installationMethod: 'none',
        installParams: undefined,
      },
    };
    const resultPath = await generator.generate(toolConfigs as Record<string, ToolConfig>);
    expect(resultPath).toBe(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));
    const content = await mockFileSystem.readFile(path.join(DEFAULT_COMPLETIONS_DIR, 'init.zsh'));

    expect(content).toContain('export TOOL_A_VAR="set"');
    expect(content).toContain('export TOOL_C_VAR="active"');
  });
  it('should return null if writeFile fails', async () => {
    const { fs, spies } = await createMemFileSystem();
    spies.writeFile.mockRejectedValueOnce(new Error('Disk full'));
    const logger = new TestLogger();
    const generatorWithFailingWrite = new ShellInitGenerator(logger, fs, mockAppConfig);
    const resultPath = await generatorWithFailingWrite.generate({});
    expect(resultPath).toBeNull();
  });
});
