# ==============================================================================
# Dotfiles Virtual Environment Activation Script (PowerShell)
# ==============================================================================
# This file is automatically generated. Do not edit directly.
#
# Usage:
#   . .\activated-env\source.ps1
#   . activated-env/source.ps1
#
# To deactivate:
#   dotfiles-deactivate
# ==============================================================================

function global:dotfiles-deactivate {
  if ($env:DOTFILES_ENV_DIR) {
    # Restore original XDG_CONFIG_HOME
    if ($env:_DOTFILES_OLD_XDG_CONFIG_HOME) {
      $env:XDG_CONFIG_HOME = $env:_DOTFILES_OLD_XDG_CONFIG_HOME
      Remove-Item Env:_DOTFILES_OLD_XDG_CONFIG_HOME -ErrorAction SilentlyContinue
    } else {
      Remove-Item Env:XDG_CONFIG_HOME -ErrorAction SilentlyContinue
    }
    Remove-Item Env:DOTFILES_ENV_DIR -ErrorAction SilentlyContinue
    Remove-Item Env:DOTFILES_ENV_NAME -ErrorAction SilentlyContinue
    Remove-Item Function:dotfiles-deactivate -ErrorAction SilentlyContinue
    Write-Host "Deactivated dotfiles environment"
  }
}

# If already active, deactivate first
if ($env:DOTFILES_ENV_DIR) {
  dotfiles-deactivate
}

# Resolve the directory containing this script
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $scriptDir) {
  # Fallback to hardcoded path
  $scriptDir = "/Users/alex/Development/github/dotfiles-tool-installer.worktrees/hostname/packages/e2e-test/src/__tests__/activated-env"
}

# Save old XDG_CONFIG_HOME for restoration on deactivate
if ($env:XDG_CONFIG_HOME) {
  $env:_DOTFILES_OLD_XDG_CONFIG_HOME = $env:XDG_CONFIG_HOME
}

# Export environment variables
$env:DOTFILES_ENV_DIR = $scriptDir
$env:DOTFILES_ENV_NAME = "activated-env"
$env:XDG_CONFIG_HOME = "$scriptDir\.config"

Write-Host "Activated dotfiles environment: activated-env"
Write-Host "  Directory: $env:DOTFILES_ENV_DIR"
Write-Host "  Config: $env:DOTFILES_ENV_DIR\config.ts"