#!/usr/bin/env bun

import path from 'node:path';
import fs from 'node:fs/promises'; // Use promises API
import { config as appConfig } from './config';
import { loadToolConfigs } from './config-loader';
import { createLogger } from './utils/logger';

const logger = createLogger('generator');

async function mainGenerator() {
  logger('Starting dotfiles generator...');

  try {
    // 1. Load all tool configurations
    const toolConfigs = await loadToolConfigs();
    logger('Loaded %d tool configurations.', toolConfigs.size);

    // Ensure generated directory exists
    if (!appConfig.GENERATED_DIR) {
      throw new Error('GENERATED_DIR is not defined in the application configuration.');
    }
    await fs.mkdir(appConfig.GENERATED_DIR, { recursive: true });
    logger('Ensured generated directory exists: %s', appConfig.GENERATED_DIR);

    // 2. Read the shim template
    const shimTemplatePath = path.join(__dirname, 'templates', 'shim.sh');
    const shimTemplateContent = await fs.readFile(shimTemplatePath, 'utf-8');
    logger('Read shim template from: %s', shimTemplatePath);

    // Ensure target directory for shims exists
    if (!appConfig.TARGET_DIR) {
      throw new Error('TARGET_DIR is not defined in the application configuration.');
    }
    await fs.mkdir(appConfig.TARGET_DIR, { recursive: true });
    logger('Ensured target directory for shims exists: %s', appConfig.TARGET_DIR);

    // 3. Generate and write shims for each tool and binary
    for (const [toolName, toolConfig] of toolConfigs.entries()) {
      if (!toolConfig.binaries || toolConfig.binaries.length === 0) {
        logger('Tool %s has no binaries defined. Skipping shim generation.', toolName);
        continue;
      }

      for (const binaryName of toolConfig.binaries) {
        const shimContent = shimTemplateContent
          .replace(/{{TOOL_NAME}}/g, toolName)
          .replace(/{{BINARY_NAME}}/g, binaryName);

        const shimPath = path.join(appConfig.TARGET_DIR, binaryName);
        logger('Writing shim for %s to %s', binaryName, shimPath);
        await fs.writeFile(shimPath, shimContent, 'utf-8');

        // Set executable permissions
        await fs.chmod(shimPath, 0o755);
        logger('Set executable permissions for shim: %s', shimPath);
      }
    }

    // 4. Generate the consolidated Zsh init file
    const zshInitDir = path.join(appConfig.GENERATED_DIR, 'zsh');
    await fs.mkdir(zshInitDir, { recursive: true });
    const zshInitPath = path.join(zshInitDir, 'init.zsh');
    let zshInitContent = '# Generated by dotfiles-generator\n\n';

    for (const [toolName, toolConfig] of toolConfigs.entries()) {
      if (toolConfig.zshContent && toolConfig.zshContent.length > 0) {
        zshInitContent += `# --- ${toolName} --- \n`;
        zshInitContent += toolConfig.zshContent.join('\n') + '\n\n';
      }
    }

    logger('Writing Zsh init file to: %s', zshInitPath);
    await fs.writeFile(zshInitPath, zshInitContent, 'utf-8');

    // 5. Create configured symbolic links
    for (const [toolName, toolConfig] of toolConfigs.entries()) {
      if (!toolConfig.symlinks || toolConfig.symlinks.length === 0) {
        logger('Tool %s has no symlinks defined. Skipping symlink creation.', toolName);
        continue;
      }

      for (const symlink of toolConfig.symlinks) {
        // Resolve source path relative to dotfiles directory
        if (!appConfig.DOTFILES_DIR) {
          throw new Error('DOTFILES_DIR is not defined in the application configuration.');
        }
        const sourcePath = path.join(appConfig.DOTFILES_DIR, symlink.source);

        // Resolve target path relative to home directory
        const homeDir = process.env.HOME;
        if (!homeDir) {
          throw new Error('HOME environment variable is not set.');
        }
        const targetPath = path.join(homeDir, symlink.target);

        logger('Creating symlink from %s to %s', sourcePath, targetPath);

        // Ensure target directory exists
        await fs.mkdir(path.dirname(targetPath), { recursive: true });

        // Remove existing target if it exists
        try {
          await fs.unlink(targetPath);
        } catch (error: any) {
          if (error.code !== 'ENOENT') {
            logger('Error removing existing symlink target %s: %o', targetPath, error);
            throw error;
          }
        }

        // Create the symlink
        await fs.symlink(sourcePath, targetPath);
        logger('Created symlink: %s -> %s', sourcePath, targetPath);
      }
    }

    // 6. Create/update the manifest file
    const manifestPath = path.join(appConfig.GENERATED_DIR, 'manifest.json');
    const manifestContent = {
      generatedShims: [] as { toolName: string; binaryName: string; path: string }[],
      createdSymlinks: [] as { toolName: string; source: string; target: string }[],
      // Add other generated artifacts here
    };

    // Collect information about generated shims
    for (const [toolName, toolConfig] of toolConfigs.entries()) {
      if (toolConfig.binaries) {
        for (const binaryName of toolConfig.binaries) {
          manifestContent.generatedShims.push({
            toolName,
            binaryName,
            path: path.join(appConfig.TARGET_DIR, binaryName),
          });
        }
      }
      // Collect information about created symlinks
      if (toolConfig.symlinks) {
        for (const symlink of toolConfig.symlinks) {
          const homeDir = process.env.HOME;
          if (!homeDir) {
            throw new Error('HOME environment variable is not set.');
          }
          manifestContent.createdSymlinks.push({
            toolName,
            source: path.join(appConfig.DOTFILES_DIR!, symlink.source), // Use non-null assertion as checked earlier
            target: path.join(homeDir, symlink.target),
          });
        }
      }
    }

    logger('Writing manifest file to: %s', manifestPath);
    await fs.writeFile(manifestPath, JSON.stringify(manifestContent, null, 2), 'utf-8');
    logger('Manifest file created/updated.');

    logger('Generator finished.');
  } catch (error) {
    logger('Error during generator execution: %o', error);
    console.error(
      `Dotfiles generator failed: ${error instanceof Error ? error.message : String(error)}`
    );
    process.exit(1);
  }
}

// Entry point logic
if (require.main === module) {
  mainGenerator().catch((err) => {
    console.error('Unhandled error in mainGenerator:', err);
    process.exit(1);
  });
}

import { Command } from 'commander';
const program = new Command();

program
  .command('generate')
  .description('Generates shims, Zsh init file, and symlinks')
  .option('--dry-run', 'Perform a dry run without writing files')
  .action(async (options: { dryRun?: boolean }) => {
    logger('Running generate command...');
    // TODO: Implement dry run logic
    await mainGenerator();
  });

program
  .command('cleanup')
  .description('Removes generated shims, Zsh init file, and symlinks')
  .action(async () => {
    logger('Running cleanup command...');
    const manifestPath = path.join(appConfig.GENERATED_DIR!, 'manifest.json'); // Use non-null assertion

    try {
      // Read and parse the manifest file
      const manifestContent = JSON.parse(await fs.readFile(manifestPath, 'utf-8'));
      logger('Loaded manifest file from: %s', manifestPath);

      // Remove generated shims
      if (manifestContent.generatedShims) {
        for (const shim of manifestContent.generatedShims) {
          try {
            logger('Removing shim: %s', shim.path);
            await fs.unlink(shim.path);
            logger('Removed shim: %s', shim.path);
          } catch (error: any) {
            if (error.code !== 'ENOENT') {
              logger('Error removing shim %s: %o', shim.path, error);
              // Decide whether to throw or continue on error
            } else {
              logger('Shim already removed: %s', shim.path);
            }
          }
        }
      }

      // Remove created symlinks
      if (manifestContent.createdSymlinks) {
        for (const symlink of manifestContent.createdSymlinks) {
          try {
            logger('Removing symlink: %s', symlink.target);
            await fs.unlink(symlink.target);
            logger('Removed symlink: %s', symlink.target);
          } catch (error: any) {
            if (error.code !== 'ENOENT') {
              logger('Error removing symlink %s: %o', symlink.target, error);
              // Decide whether to throw or continue on error
            } else {
              logger('Symlink already removed: %s', symlink.target);
            }
          }
        }
      }

      // TODO: Remove generated Zsh init file and generated binaries directory?
      // This might be part of a more aggressive cleanup or a separate command.

      logger('Cleanup command finished.');
    } catch (error: any) {
      if (error.code !== 'ENOENT') {
        logger('Error during cleanup command: %o', error);
        console.error(
          `Dotfiles cleanup failed: ${error instanceof Error ? error.message : String(error)}`
        );
        process.exit(1);
      } else {
        logger('Manifest file not found. No cleanup needed.');
      }
    }
  });

program
  .command('detect-conflicts')
  .description('Detects potential conflicts with existing files in the target directory')
  .action(async () => {
    logger('Running detect-conflicts command...');
    if (!appConfig.TARGET_DIR) {
      throw new Error('TARGET_DIR is not defined in the application configuration.');
    }

    try {
      // Get the list of files in the target directory
      const existingFiles = new Set(await fs.readdir(appConfig.TARGET_DIR));
      logger(
        'Found %d existing files in target directory: %s',
        existingFiles.size,
        appConfig.TARGET_DIR
      );

      // Get the list of shims that would be generated
      const toolConfigs = await loadToolConfigs();
      const generatedShims = new Set<string>();
      for (const [toolName, toolConfig] of toolConfigs.entries()) {
        if (toolConfig.binaries) {
          for (const binaryName of toolConfig.binaries) {
            generatedShims.add(binaryName);
          }
        }
      }
      logger('Identified %d shims to be generated.', generatedShims.size);

      // Find conflicts (files that exist and would be generated)
      const conflicts = Array.from(existingFiles).filter((file) => generatedShims.has(file));

      if (conflicts.length > 0) {
        logger('Detected %d potential conflicts:', conflicts.length);
        console.warn('Potential conflicts detected in %s:', appConfig.TARGET_DIR);
        for (const conflict of conflicts) {
          console.warn(`- ${conflict}`);
        }
        console.warn('These files would be overwritten by the generator.');
      } else {
        logger('No potential conflicts detected.');
        console.log('No potential conflicts detected in %s.', appConfig.TARGET_DIR);
      }

      logger('Detect-conflicts command finished.');
    } catch (error) {
      logger('Error during detect-conflicts command: %o', error);
      console.error(
        `Dotfiles detect-conflicts failed: ${error instanceof Error ? error.message : String(error)}`
      );
      process.exit(1);
    }
  });

program
  .command('guess-lost-shims')
  .description('Identifies shims in the target directory that are not in the manifest')
  .action(async () => {
    logger('Running guess-lost-shims command...');
    if (!appConfig.TARGET_DIR) {
      throw new Error('TARGET_DIR is not defined in the application configuration.');
    }
    const manifestPath = path.join(appConfig.GENERATED_DIR!, 'manifest.json'); // Use non-null assertion

    try {
      // Read and parse the manifest file
      const manifestContent = JSON.parse(await fs.readFile(manifestPath, 'utf-8'));
      logger('Loaded manifest file from: %s', manifestPath);

      // Get the list of shims in the manifest
      const manifestShims = new Set(manifestContent.generatedShims.map((shim: any) => shim.path)); // Use any for now

      // Get the list of files in the target directory
      const existingFiles = await fs.readdir(appConfig.TARGET_DIR);
      logger(
        'Found %d existing files in target directory: %s',
        existingFiles.length,
        appConfig.TARGET_DIR
      );

      // Find lost shims (files that exist in target directory but are not in the manifest)
      const lostShims = existingFiles.filter((file) => {
        const fullPath = path.join(appConfig.TARGET_DIR!, file); // Use non-null assertion
        return !manifestShims.has(fullPath);
      });

      if (lostShims.length > 0) {
        logger('Detected %d potential lost shims:', lostShims.length);
        console.warn('Potential lost shims detected in %s:', appConfig.TARGET_DIR);
        for (const lostShim of lostShims) {
          console.warn(`- ${lostShim}`);
        }
        // TODO: Implement TUI for presenting options (remove, ignore, etc.)
      } else {
        logger('No potential lost shims detected.');
        console.log('No potential lost shims detected in %s.', appConfig.TARGET_DIR);
      }

      logger('Guess-lost-shims command finished.');
    } catch (error: any) {
      if (error.code !== 'ENOENT') {
        logger('Error during guess-lost-shims command: %o', error);
        console.error(
          `Dotfiles guess-lost-shims failed: ${error instanceof Error ? error.message : String(error)}`
        );
        process.exit(1);
      } else {
        logger('Manifest file not found. Cannot guess lost shims.');
        console.warn('Manifest file not found at %s. Run `generate` first.', manifestPath);
      }
    }
  });

program.parse(process.argv);
