import path from 'node:path';
import type { ToolConfig, CompletionConfig, ShellType } from '@types';
import type { IFileSystem } from '@modules/file-system';
import type { IShellInitGenerator, GenerateShellInitOptions } from './IShellInitGenerator';
import type { TsLogger } from '@modules/logger';
import type { YamlConfig } from '@modules/config';
import { DebugTemplates } from '@modules/shared/ErrorTemplates';

export class ShellInitGenerator implements IShellInitGenerator {
  private readonly fs: IFileSystem;
  private readonly appConfig: YamlConfig;
  private readonly logger: TsLogger;

  constructor(parentLogger: TsLogger, fileSystem: IFileSystem, appConfig: YamlConfig) {
    this.logger = parentLogger.getSubLogger({ name: 'ShellInitGenerator' });
    this.logger.debug(DebugTemplates.shellInit.constructorDebug(), fileSystem, appConfig);
    this.fs = fileSystem;
    this.appConfig = appConfig;
  }

  async generate(
    toolConfigs: Record<string, ToolConfig>,
    options?: GenerateShellInitOptions
  ): Promise<string | null> {
    this.logger.debug(DebugTemplates.shellInit.generateDebug(), toolConfigs, options, this.fs.constructor.name);
    // dryRun is removed; IFileSystem handles behavior
    const outputPath =
      options?.outputPath ?? path.join(this.appConfig.paths.completionsDir, 'init.zsh');
    this.logger.debug(DebugTemplates.shellInit.outputPath(), outputPath);

    const header = [
      '# ==========================================================================',
      '# THIS FILE IS AUTOMATICALLY GENERATED BY THE DOTFILES MANAGEMENT TOOL',
      '# DO NOT EDIT THIS FILE DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN',
      '# ==========================================================================',
      '',
      `# Dotfiles directory: ${this.appConfig.paths.dotfilesDir}`,
      '',
    ];

    const pathModifications: string[] = [];
    const environmentVariables: string[] = [];
    const toolSpecificInits: string[] = [];
    const completionSetup: string[] = [];

    // Add .dotfiles/.generated/bin to PATH by default
    pathModifications.push(`export PATH="${this.appConfig.paths.binariesDir}:$PATH"`);

    for (const toolName in toolConfigs) {
      const config = toolConfigs[toolName];
      this.logger.debug(DebugTemplates.shellInit.processingTool(), toolName, config);

      if (!config) {
        this.logger.debug(DebugTemplates.shellInit.skippingUndefined(), toolName);
        continue;
      }
      if (config.zshInit && config.zshInit.length > 0) {
        toolSpecificInits.push(`\n# --- ${toolName} ---`);
        config.zshInit.forEach((line) => {
          // Heuristic to identify PATH modifications and environment variables
          if (
            line.trim().startsWith('export PATH=') ||
            line.trim().startsWith('path+=') ||
            line.trim().startsWith('fpath+=')
          ) {
            pathModifications.push(line);
          } else if (line.trim().startsWith('export ') && line.includes('=')) {
            environmentVariables.push(line);
          } else {
            toolSpecificInits.push(line);
          }
        });
      }

      if (config.completions) {
        this.processCompletions(toolName, config.completions, completionSetup, pathModifications);
      }
    }

    let content = header.join('\n') + '\n';

    if (pathModifications.length > 0) {
      content += '# === PATH Modifications ===\n';
      // Deduplicate and ensure .dotfiles/.generated/bin is first if present
      const uniquePaths = [...new Set(pathModifications)];
      const generatedBinPathLine = uniquePaths.find((p) =>
        p.includes(this.appConfig.paths.binariesDir)
      );
      if (generatedBinPathLine) {
        content += generatedBinPathLine + '\n';
        uniquePaths.splice(uniquePaths.indexOf(generatedBinPathLine), 1);
      }
      content += uniquePaths.join('\n') + '\n\n';
    }

    if (environmentVariables.length > 0) {
      content += '# === Environment Variables ===\n';
      content += [...new Set(environmentVariables)].join('\n') + '\n\n';
    }

    if (toolSpecificInits.length > 0) {
      content += '# === Tool-Specific Initializations ===\n';
      content += toolSpecificInits.join('\n') + '\n\n';
    }

    if (completionSetup.length > 0) {
      content += '# === Shell Completions Setup ===\n';
      // Ensure fpath is initialized if not already
      const allInitLines = [...pathModifications, ...toolSpecificInits];
      if (!allInitLines.some((p) => p.includes('typeset -U fpath'))) {
        completionSetup.unshift('typeset -U fpath');
      }
      content += [...new Set(completionSetup)].join('\n') + '\n\n';
    }

    content += '\n# === End of Generated File ===\n';

    // File system operations' behavior (dry or real) is determined by the injected IFileSystem.
    try {
      await this.fs.ensureDir(path.dirname(outputPath));
      await this.fs.writeFile(outputPath, content);
      return outputPath;
    } catch (error: any) {
      this.logger.debug(DebugTemplates.shellInit.writeError(), outputPath, this.fs.constructor.name, error.message);
      return null; // Return null if an error occurs during file writing
    }
  }

  private processCompletions(
    toolName: string,
    completions: CompletionConfig,
    completionSetupLines: string[],
    currentPathModifications: string[]
  ): void {
    this.logger.debug(DebugTemplates.shellInit.processCompletions(), toolName, completions);
    const processShellCompletion = (
      shell: ShellType,
      shellConfig?: { source: string; name?: string; targetDir?: string }
    ) => {
      if (shellConfig && shell === 'zsh') {
        // Only Zsh supported for now by this generator
        const completionDir =
          shellConfig.targetDir ?? path.join(this.appConfig.paths.completionsDir, shell);
        // const completionName = shellConfig.name ?? `_${toolName}`; // This var is unused for now
        // const completionSourcePath = path.join(completionDir, completionName); // This var is unused for now

        // Add completion directory to fpath if not already there
        const fpathAdd = `fpath=(${JSON.stringify(completionDir)} $fpath)`;
        if (
          !completionSetupLines.includes(fpathAdd) &&
          !currentPathModifications.some((p: string) => p.includes(completionDir))
        ) {
          completionSetupLines.push(fpathAdd);
        }

        // Check if the completion file itself needs to be sourced (less common for fpath)
        // Typically, for Zsh, just adding to fpath is enough if files are named correctly (_toolname).
        // Sourcing might be needed if the file itself contains `compdef` or similar.
        // For now, we assume standard fpath behavior. If `shellConfig.source` implies a script to be sourced,
        // it should be part of `zshInit` instead.
        this.logger.debug(DebugTemplates.shellInit.fpathAdded(), completionDir, toolName);
      }
    };

    processShellCompletion('zsh', completions.zsh);
    // Future: processShellCompletion('bash', completions.bash);
    // Future: processShellCompletion('fish', completions.fish);
  }
}
