/**
 * @file generator/src/modules/generator-shell-init/ShellInitGenerator.ts
 * @description Implementation of the shell initialization file generator.
 *
 * ## Development Plan (for ShellInitGenerator.ts)
 *
 * ### Tasks:
 * - [x] Implement `ShellInitGenerator` class adhering to `IShellInitGenerator`.
 * - [x] Constructor should accept `IFileSystem` and `AppConfig`.
 * - [x] Implement the `generate` method:
 *   - [x] Update `generate` method to return `Promise<string | null>`.
 *   - [x] Determine the output path for the Zsh init file.
 *   - [x] Iterate through `toolConfigs` to gather information:
 *     - [x] Paths to add to `PATH`.
 *     - [x] Environment variables to set.
 *     - [x] Shell code snippets to include (from `ToolConfig.zshInit`).
 *     - [x] Completion paths/scripts to set up (from `ToolConfig.completions`).
 *   - [x] Construct the content of the Zsh init file.
 *   - [x] Write the generated content to the output file using `IFileSystem.writeFile()` (behavior determined by injected `IFileSystem` type).
 * - [x] Add JSDoc comments.
 * - [x] Add structured logging using `createLogger`.
 * - [x] Refactor dry run mechanism:
 *   - [x] Remove internal `dryRun` logic.
 *   - [x] Rely on injected `IFileSystem` for dry/real run behavior.
 * - [ ] Write unit tests (`__tests__/ShellInitGenerator.test.ts`).
 * - [x] Cleanup all linting errors and warnings.
 * - [x] Cleanup all comments that are no longer relevant (leaving development plan).
 * - [ ] Update the memory bank with the new information when all tasks are complete (part of the overall module task).
 */

import path from 'node:path';
import type { AppConfig, ToolConfig, CompletionConfig, ShellType } from '@types';
import type { IFileSystem } from '@modules/file-system';
import type { IShellInitGenerator, GenerateShellInitOptions } from './IShellInitGenerator';
import { createLogger } from '@modules/logger';

const log = createLogger('ShellInitGenerator');

export class ShellInitGenerator implements IShellInitGenerator {
  private readonly fs: IFileSystem;
  private readonly appConfig: AppConfig;

  constructor(fileSystem: IFileSystem, appConfig: AppConfig) {
    log('constructor: fileSystem=%o, appConfig=%o', fileSystem, appConfig);
    this.fs = fileSystem;
    this.appConfig = appConfig;
  }

  async generate(
    toolConfigs: Record<string, ToolConfig>,
    options?: GenerateShellInitOptions
  ): Promise<string | null> {
    log(
      'generate: toolConfigs=%o, options=%o, FileSystem: %s',
      toolConfigs,
      options,
      this.fs.constructor.name
    );
    // dryRun is removed; IFileSystem handles behavior
    const outputPath = options?.outputPath ?? path.join(this.appConfig.zshInitDir, 'init.zsh');
    log('generate: outputPath=%s', outputPath);

    const header = [
      '# ==========================================================================',
      '# THIS FILE IS AUTOMATICALLY GENERATED BY THE DOTFILES MANAGEMENT TOOL',
      '# DO NOT EDIT THIS FILE DIRECTLY - YOUR CHANGES WILL BE OVERWRITTEN',
      '# ==========================================================================',
      '',
      `# Generated on: ${new Date().toISOString()}`,
      `# Dotfiles directory: ${this.appConfig.dotfilesDir}`,
      '',
    ];

    const pathModifications: string[] = [];
    const environmentVariables: string[] = [];
    const toolSpecificInits: string[] = [];
    const completionSetup: string[] = [];

    // Add .dotfiles/.generated/bin to PATH by default
    pathModifications.push(`export PATH="${this.appConfig.binDir}:$PATH"`);

    for (const toolName in toolConfigs) {
      const config = toolConfigs[toolName];
      log('generate: processing tool=%s, config=%o', toolName, config);

      if (!config) {
        log('generate: skipping undefined config for toolName=%s', toolName);
        continue;
      }
      if (config.zshInit && config.zshInit.length > 0) {
        toolSpecificInits.push(`\n# --- ${toolName} ---`);
        config.zshInit.forEach((line) => {
          // Heuristic to identify PATH modifications and environment variables
          if (
            line.trim().startsWith('export PATH=') ||
            line.trim().startsWith('path+=') ||
            line.trim().startsWith('fpath+=')
          ) {
            pathModifications.push(line);
          } else if (line.trim().startsWith('export ') && line.includes('=')) {
            environmentVariables.push(line);
          } else {
            toolSpecificInits.push(line);
          }
        });
      }

      if (config.completions) {
        this.processCompletions(toolName, config.completions, completionSetup, pathModifications);
      }
    }

    let content = header.join('\n') + '\n';

    if (pathModifications.length > 0) {
      content += '# === PATH Modifications ===\n';
      // Deduplicate and ensure .dotfiles/.generated/bin is first if present
      const uniquePaths = [...new Set(pathModifications)];
      const generatedBinPathLine = uniquePaths.find((p) => p.includes(this.appConfig.binDir));
      if (generatedBinPathLine) {
        content += generatedBinPathLine + '\n';
        uniquePaths.splice(uniquePaths.indexOf(generatedBinPathLine), 1);
      }
      content += uniquePaths.join('\n') + '\n\n';
    }

    if (environmentVariables.length > 0) {
      content += '# === Environment Variables ===\n';
      content += [...new Set(environmentVariables)].join('\n') + '\n\n';
    }

    if (toolSpecificInits.length > 0) {
      content += '# === Tool-Specific Initializations ===\n';
      content += toolSpecificInits.join('\n') + '\n\n';
    }

    if (completionSetup.length > 0) {
      content += '# === Shell Completions Setup ===\n';
      // Ensure fpath is initialized if not already
      if (!pathModifications.some((p) => p.includes('fpath=(') || p.includes('typeset -U fpath'))) {
        completionSetup.unshift('typeset -U fpath');
      }
      content += [...new Set(completionSetup)].join('\n') + '\n\n';
    }

    content += '\n# === End of Generated File ===\n';

    // File system operations' behavior (dry or real) is determined by the injected IFileSystem.
    try {
      log(
        'generate: Writing to %s using %s with content:\n%s',
        outputPath,
        this.fs.constructor.name,
        content
      );
      await this.fs.ensureDir(path.dirname(outputPath));
      await this.fs.writeFile(outputPath, content);
      log(
        'generate: Successfully wrote Zsh init file to %s using %s',
        outputPath,
        this.fs.constructor.name
      );
      return outputPath;
    } catch (error: any) {
      log(
        'generate: ERROR: Failed to write Zsh init file to %s using %s. Error: %s',
        outputPath,
        this.fs.constructor.name,
        error.message
      );
      return null; // Return null if an error occurs during file writing
    }
  }

  private processCompletions(
    toolName: string,
    completions: CompletionConfig,
    completionSetupLines: string[],
    currentPathModifications: string[]
  ): void {
    log('processCompletions: toolName=%s, completions=%o', toolName, completions);
    const processShellCompletion = (
      shell: ShellType,
      shellConfig?: { source: string; name?: string; targetDir?: string }
    ) => {
      if (shellConfig && shell === 'zsh') {
        // Only Zsh supported for now by this generator
        const completionDir =
          shellConfig.targetDir ?? path.join(this.appConfig.completionsDir, shell);
        // const completionName = shellConfig.name ?? `_${toolName}`; // This var is unused for now
        // const completionSourcePath = path.join(completionDir, completionName); // This var is unused for now

        // Add completion directory to fpath if not already there
        const fpathAdd = `fpath=(${JSON.stringify(completionDir)} $fpath)`;
        if (
          !completionSetupLines.includes(fpathAdd) &&
          !currentPathModifications.some((p: string) => p.includes(completionDir))
        ) {
          completionSetupLines.push(fpathAdd);
        }

        // Check if the completion file itself needs to be sourced (less common for fpath)
        // Typically, for Zsh, just adding to fpath is enough if files are named correctly (_toolname).
        // Sourcing might be needed if the file itself contains `compdef` or similar.
        // For now, we assume standard fpath behavior. If `shellConfig.source` implies a script to be sourced,
        // it should be part of `zshInit` instead.
        log('processCompletions: Added %s to fpath for tool %s', completionDir, toolName);
      }
    };

    processShellCompletion('zsh', completions.zsh);
    // Future: processShellCompletion('bash', completions.bash);
    // Future: processShellCompletion('fish', completions.fish);
  }
}
