import type { IFileSystem } from "@dotfiles/file-system";

export interface IGeneratedShimOptions {
  expectedSymlinkTarget?: string;
}

/**
 * Checks if a file is a shim generated by the dotfiles management tool.
 *
 * @param fs - The filesystem interface to use.
 * @param filePath - The path to the file to check.
 * @param options - Optional ownership expectations for symlink-based shims.
 * @returns True if the file is one of our generated shims, false otherwise.
 */
export async function isGeneratedShim(
  fs: IFileSystem,
  filePath: string,
  options: IGeneratedShimOptions = {},
): Promise<boolean> {
  try {
    try {
      const stats = await fs.lstat(filePath);
      if (stats.isSymbolicLink()) {
        if (!options.expectedSymlinkTarget) {
          return false;
        }

        const symlinkTarget = await fs.readlink(filePath);
        return symlinkTarget === options.expectedSymlinkTarget;
      }
    } catch {
      // lstat failed — fall through to content check
    }

    const content = await fs.readFile(filePath, "utf8");
    return content.includes("# Generated by Dotfiles Management Tool");
  } catch {
    return false;
  }
}
