import type { ProjectConfig } from '@dotfiles/config';
import type {
  ShellCompletionConfig,
  ShellCompletionConfigInput,
  ShellScript,
  ShellType,
  ToolConfig,
} from '@dotfiles/core';
import { getScriptContent, isAlwaysScript, isOnceScript } from '@dotfiles/core';
import path from 'node:path';
import { AlwaysScriptFormatter, FunctionScriptFormatter, OnceScriptFormatter } from '../script-formatters';
import { OnceScriptInitializer } from '../script-initializers';
import {
  generateDefaultPathModification,
  generateEndOfFile,
  generateFileHeader,
  generateHoistingAttribution,
  generateHoistingExplanation,
  generateSectionHeader,
  generateToolHeader,
} from '../shellTemplates';
import type { IAdditionalShellFile, IShellGenerator, IShellInitContent } from './IShellGenerator';

/**
 * Interface for shell-specific string generation strategy.
 * Each shell type implements this to handle shell-specific syntax.
 */
export interface IShellStringProducer {
  /**
   * Extracts shell-specific init scripts from tool config.
   */
  extractInitScripts(toolConfig: ToolConfig): ShellScript[];

  /**
   * Processes completions configuration into shell-specific setup strings.
   * Only processes resolved configs (not callbacks).
   */
  processCompletions(toolName: string, completions: ShellCompletionConfig): string[];

  /**
   * Processes environment variables into shell-specific export statements.
   */
  processEnvironmentVariables(toolConfig: ToolConfig): string[];

  /**
   * Processes aliases into shell-specific alias commands.
   */
  processAliases(toolConfig: ToolConfig): string[];

  /**
   * Generates shell-specific completion setup if needed.
   */
  generateCompletionSetup?(allCompletionSetup: string[], allToolInits: string[]): string[];
}

/**
 * Abstract base class for shell generators that contains all shared logic.
 * Shell-specific implementations only need to provide a string producer strategy.
 */
export abstract class BaseShellGenerator implements IShellGenerator {
  abstract readonly shellType: ShellType;
  abstract readonly fileExtension: string;

  protected readonly projectConfig: ProjectConfig;
  protected readonly stringProducer: IShellStringProducer;

  constructor(projectConfig: ProjectConfig, stringProducer: IShellStringProducer) {
    this.projectConfig = projectConfig;
    this.stringProducer = stringProducer;
  }

  protected abstract getShellConfig(
    toolConfig: ToolConfig,
  ): { completions?: ShellCompletionConfigInput; functions?: Record<string, string>; } | undefined;

  extractShellContent(toolName: string, toolConfig: ToolConfig): IShellInitContent {
    const content: IShellInitContent = {
      configFilePath: toolConfig.configFilePath,
      toolInit: [],
      pathModifications: [],
      environmentVariables: [],
      completionSetup: [],
      onceScripts: [],
      alwaysScripts: [],
      functions: {},
    };

    // Use string producer to extract shell-specific scripts
    const scripts = this.stringProducer.extractInitScripts(toolConfig);
    scripts.forEach((script: ShellScript) => {
      if (isOnceScript(script)) {
        content.onceScripts.push(script);
      } else if (isAlwaysScript(script)) {
        content.alwaysScripts.push(script);
      }
    });

    // Process declarative environment variables
    const envVars = this.stringProducer.processEnvironmentVariables(toolConfig);
    content.environmentVariables.push(...envVars);

    // Process declarative aliases as tool init
    const aliases = this.stringProducer.processAliases(toolConfig);
    content.toolInit.push(...aliases);

    // Process shell-specific config
    const shellConfig = this.getShellConfig(toolConfig);
    if (shellConfig?.completions) {
      const resolvedConfig = this.resolveCompletionConfig(shellConfig.completions);
      if (resolvedConfig) {
        const completionSetup = this.stringProducer.processCompletions(toolName, resolvedConfig);
        content.completionSetup.push(...completionSetup);
      }
    }

    // Extract shell functions
    if (shellConfig?.functions) {
      content.functions = { ...shellConfig.functions };
    }

    return content;
  }

  /**
   * Resolves a completion config input to a static config for shell init processing.
   * For callbacks, returns a minimal config with default settings since the actual
   * completion generation happens separately in GeneratorOrchestrator.
   */
  private resolveCompletionConfig(input: ShellCompletionConfigInput): ShellCompletionConfig | undefined {
    // If it's a function, return a minimal config to set up fpath
    // The actual completion content is generated by GeneratorOrchestrator
    if (typeof input === 'function') {
      const defaultConfig: ShellCompletionConfig = { source: 'callback' };
      return defaultConfig;
    }

    // If it's a string, treat as source path
    if (typeof input === 'string') {
      const config: ShellCompletionConfig = { source: input };
      return config;
    }

    // Otherwise it's already a config object
    return input;
  }

  processCompletions(toolName: string, completions: ShellCompletionConfig): string[] {
    return this.stringProducer.processCompletions(toolName, completions);
  }

  generateFileContent(toolContents: Map<string, IShellInitContent>): string {
    const allPathModifications: string[] = [];
    const allEnvironmentVariables: string[] = [];
    const allCompletionSetup: string[] = [];
    let hasOnceScripts = false;

    // Initialize formatters
    const onceInitializer = new OnceScriptInitializer();

    // Add default PATH modification first
    allPathModifications.push(generateDefaultPathModification(this.shellType, this.projectConfig.paths.targetDir));

    // Collect hoisted content from all tools
    this.collectHoistedContent(toolContents, allPathModifications, allEnvironmentVariables, allCompletionSetup);

    // Check if any tools have once scripts
    for (const [, content] of toolContents) {
      if (content.onceScripts.length > 0) {
        hasOnceScripts = true;
        break;
      }
    }

    let fileContent = `${generateFileHeader(this.shellType, this.projectConfig.paths.dotfilesDir)}\n`;

    // Add once script initialization if any tools use once scripts
    if (hasOnceScripts) {
      const initialization = onceInitializer.initialize(this.shellType, this.projectConfig.paths.shellScriptsDir);
      fileContent += `${initialization.content}\n\n`;
    }

    // Add PATH modifications section with hoisting comments
    fileContent += this.generateHoistedSection(
      'PATH Modifications',
      allPathModifications,
      toolContents,
      'pathModifications',
    );

    // Add environment variables section with hoisting comments
    fileContent += this.generateHoistedSection(
      'Environment Variables',
      allEnvironmentVariables,
      toolContents,
      'environmentVariables',
    );

    // Add tool-specific initializations section with all tool content grouped together
    fileContent += this.generateToolSection(toolContents);

    // Add shell completions setup section
    if (allCompletionSetup.length > 0) {
      fileContent += `${generateSectionHeader(this.shellType, 'Shell Completions Setup')}\n`;

      // Use string producer for shell-specific completion setup if available
      const completionSetupStrings = this.stringProducer.generateCompletionSetup
        ? this.stringProducer.generateCompletionSetup(allCompletionSetup, [])
        : [...new Set(allCompletionSetup)];

      fileContent += `${completionSetupStrings.join('\n')}\n\n`;
    }

    fileContent += `\n${generateEndOfFile(this.shellType)}`;

    return fileContent;
  }

  getDefaultOutputPath(): string {
    return path.join(this.projectConfig.paths.shellScriptsDir, `main${this.fileExtension}`);
  }

  getAdditionalFiles(toolContents: Map<string, IShellInitContent>): IAdditionalShellFile[] {
    const additionalFiles: IAdditionalShellFile[] = [];
    const onceFormatter = new OnceScriptFormatter(
      this.projectConfig.paths.shellScriptsDir,
      this.projectConfig.paths.homeDir,
    );

    for (const [toolName, content] of toolContents) {
      for (let i = 0; i < content.onceScripts.length; i++) {
        const script = content.onceScripts[i];
        if (script) {
          const formatted = onceFormatter.format(script, toolName, this.shellType, i);
          if (formatted.outputPath) {
            additionalFiles.push({
              content: formatted.content,
              outputPath: formatted.outputPath,
            });
          }
        }
      }
    }

    return additionalFiles;
  }

  /**
   * Collects hoisted content from all tools (PATH, env vars, completions).
   * Tool-specific content (toolInit, alwaysScripts) is handled in generateToolSection.
   */
  private collectHoistedContent(
    toolContents: Map<string, IShellInitContent>,
    allPathModifications: string[],
    allEnvironmentVariables: string[],
    allCompletionSetup: string[],
  ): void {
    for (const [, content] of toolContents) {
      allPathModifications.push(...content.pathModifications);
      allEnvironmentVariables.push(...content.environmentVariables);
      allCompletionSetup.push(...content.completionSetup);
    }
  }

  /**
   * Generates the tool section with all content grouped under tool headers.
   * Each tool gets a header followed by its always scripts and tool init content.
   */
  private generateToolSection(toolContents: Map<string, IShellInitContent>): string {
    const hasContent = this.hasAnyToolContent(toolContents);
    if (!hasContent) {
      return '';
    }

    let section = `${generateSectionHeader(this.shellType, 'Tool-Specific Initializations')}\n`;

    for (const [toolName, content] of toolContents) {
      const toolSection = this.generateSingleToolContent(toolName, content);
      section += toolSection;
    }

    return `${section}\n`;
  }

  /**
   * Checks if any tool in the map has content to render.
   */
  private hasAnyToolContent(toolContents: Map<string, IShellInitContent>): boolean {
    for (const [, content] of toolContents) {
      if (this.hasToolContent(content)) {
        return true;
      }
    }
    return false;
  }

  /**
   * Checks if a single tool's content has any renderable content.
   */
  private hasToolContent(content: IShellInitContent): boolean {
    const hasFunctions = Object.keys(content.functions).length > 0;
    return content.toolInit.length > 0 || content.alwaysScripts.length > 0 || hasFunctions;
  }

  /**
   * Generates the content section for a single tool.
   */
  private generateSingleToolContent(toolName: string, content: IShellInitContent): string {
    if (!this.hasToolContent(content)) {
      return '';
    }

    const alwaysFormatter = new AlwaysScriptFormatter(this.projectConfig.paths.homeDir);
    const functionFormatter = new FunctionScriptFormatter(this.projectConfig.paths.homeDir);

    let section = generateToolHeader(this.shellType, content.configFilePath);

    // Add always scripts for this tool
    const formattedAlwaysScripts = content.alwaysScripts.map(
      (script) => alwaysFormatter.format(script, toolName, this.shellType).content,
    );

    if (formattedAlwaysScripts.length > 0) {
      section += `\n${formattedAlwaysScripts.join('\n\n')}`;
    }

    // Add shell functions for this tool
    const formattedFunctions = Object.entries(content.functions).map(
      ([funcName, funcBody]) => functionFormatter.format(funcName, funcBody, this.shellType).content,
    );

    if (formattedFunctions.length > 0) {
      section += `\n${formattedFunctions.join('\n')}`;
    }

    // Add tool init (aliases, etc.)
    if (content.toolInit.length > 0) {
      section += `\n${content.toolInit.join('\n')}`;
    }

    section += '\n';
    return section;
  }

  /**
   * Generates a hoisted section with comments indicating original source.
   */
  private generateHoistedSection(
    sectionTitle: string,
    items: string[],
    toolContents: Map<string, IShellInitContent>,
    contentType: keyof IShellInitContent,
  ): string {
    if (items.length === 0) return '';

    let section = `${generateSectionHeader(this.shellType, sectionTitle)}\n`;

    // Add hoisting explanation comment
    section += `${generateHoistingExplanation(this.shellType, sectionTitle)}\n`;

    // For PATH modifications, ensure generated bin directory is first
    if (sectionTitle === 'PATH Modifications') {
      const uniquePaths = [...new Set(items)];
      const generatedBinPathLine = uniquePaths.find((p) => p.includes(this.projectConfig.paths.binariesDir));
      if (generatedBinPathLine) {
        section += `${generatedBinPathLine}\n`;
        uniquePaths.splice(uniquePaths.indexOf(generatedBinPathLine), 1);
      }

      // Add remaining paths with source attribution
      for (const item of uniquePaths) {
        const sourceTools = this.findSourceTools(item, toolContents, contentType);
        const attribution = generateHoistingAttribution(this.shellType, sourceTools);
        if (attribution) {
          section += `${attribution}\n`;
        }
        section += `${item}\n`;
      }
    } else {
      // For other sections, add items with source attribution
      const uniqueItems = [...new Set(items)];
      for (const item of uniqueItems) {
        const sourceTools = this.findSourceTools(item, toolContents, contentType);
        const attribution = generateHoistingAttribution(this.shellType, sourceTools);
        if (attribution) {
          section += `${attribution}\n`;
        }
        section += `${item}\n`;
      }
    }

    return `${section}\n`;
  }

  /**
   * Finds which tools contributed a specific item to a content type.
   * Returns relative paths to the tool config files (e.g., "tools/fly.tool.ts").
   */
  private findSourceTools(
    item: string,
    toolContents: Map<string, IShellInitContent>,
    contentType: keyof IShellInitContent,
  ): string[] {
    const sourceTools: string[] = [];

    for (const [, content] of toolContents) {
      const contentArray = content[contentType];
      if (Array.isArray(contentArray)) {
        // Handle both plain strings and ShellScript branded types
        const hasMatch = contentArray.some((arrayItem) => {
          if (typeof arrayItem === 'string') {
            return arrayItem === item;
          }
          // For ShellScript branded types, compare the content
          return getScriptContent(arrayItem as ShellScript) === item;
        });
        if (hasMatch && content.configFilePath) {
          // Return relative path from toolConfigsDir to the config file
          const relativePath = path.relative(this.projectConfig.paths.toolConfigsDir, content.configFilePath);
          sourceTools.push(relativePath);
        }
      }
    }

    return sourceTools;
  }
}
